### ISSUE TITLE
Timepoint transformation crash

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1010]
Hi,

I like to work with timepoint assignment ransformations.

this project:
`/g/schwab/Beckwith_MSB/Microscopy_data/SBEM_data/220509_MSB26_sample2_liveCellCLEM/220509_MSB26_sample2_MoBIE` 

validates correctly according to the current spec. I also inspected the timepoint transfromations and they seem OK.
However, the viewer always crashes with:

```
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: class org.embl.mobie.lib.serialize.transformation.TimepointsTransformation declares multiple JSON fields named sources
	at org.embl.mobie.lib.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:64)
	at org.embl.mobie.lib.serialize.transformation.TransformationListAdapter.deserialize(TransformationListAdapter.java:74)
	at org.embl.mobie.lib.serialize.transformation.TransformationListAdapter.deserialize(TransformationListAdapter.java:48)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at com.google.gson.Gson.fromJson(Gson.java:905)
	at org.embl.mobie.lib.serialize.DatasetJsonParser.parseDataset(DatasetJsonParser.java:45)
	at org.embl.mobie.lib.MoBIE.openAndViewDataset(MoBIE.java:616)
	at org.embl.mobie.lib.MoBIE.openAndViewDataset(MoBIE.java:552)
	at org.embl.mobie.lib.MoBIE.<init>(MoBIE.java:176)
	at org.embl.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:56)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
Caused by: java.lang.IllegalArgumentException: class org.embl.mobie.lib.serialize.transformation.TimepointsTransformation declares multiple JSON fields named sources
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:171)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:101)
	at com.google.gson.Gson.getAdapter(Gson.java:501)
	at com.google.gson.Gson.fromJson(Gson.java:990)
	at com.google.gson.Gson.fromJson(Gson.java:1062)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:163)
	at org.embl.mobie.lib.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:59)
	... 27 more
```

I don't understand what `multiple JSON fields named sources`  means, I can spot only one each.

**Comment by tischi** [comment]
Should work now on MoBIE-beta.

**Comment by martinschorb** [comment]
define "work" please

```
Exception in thread "Thread-11" java.lang.UnsupportedOperationException: Transformations of type org.embl.mobie.lib.serialize.transformation.TimepointsTransformation are not yet implemented.
	at org.embl.mobie.lib.view.ViewManager.initData(ViewManager.java:455)
	at org.embl.mobie.lib.view.ViewManager.show(ViewManager.java:249)
	at org.embl.mobie.lib.ui.UserInterfaceHelper.lambda$createViewSelectionPanel$17(UserInterfaceHelper.java:779)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martinschorb** [comment]
Sorry, I forgot to specify:
the error appears when loading one of the `clem` views that actually include a `TimepointsTransformation`.

**Comment by tischi** [comment]
@martinschorb OK, it seems I did not use this in a long time and some core internals have changed. I have to put a bit of work into it. I hope I will manage today.

**Comment by tischi** [comment]
In fact, this surely is the wrong way around as it would map several time points into `0`.
You have to turn it around.

**Comment by tischi** [comment]
my mistake you did it the right way around

**Comment by tischi** [comment]
works now:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/2157566/229803166-7f5d3a04-e2cb-4459-9682-95827e93dfce.png">

**Comment by martinschorb** [comment]
cool!
Let's meet to chat about further implementing multi-timepoint sources. I have some ideas there...

**Comment by martinschorb** [comment]
> Registration could be improved ;-)

That's why there is a view `clem-registered` 😆
