### ISSUE TITLE
Project Creator, future development?

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1024]
Hi,

what is the future of the Project Creator?
I just realized that the current MoBIE release version produces

`"specVersion": "0.2.0",` in `project.json`.

**Comment by martinschorb** [comment]
the current `beta` does the same.

**Comment by martinschorb** [comment]
when trying to migrate this project (which opens fine in MoBIE Viewer), I get:
```
Migrate dataset: MSB30_4
Traceback (most recent call last):
  File "/g/emcf/software/python/miniconda/envs/mobie/bin/mobie.migrate_project", line 33, in <module>
    sys.exit(load_entry_point('mobie', 'console_scripts', 'mobie.migrate_project')())
  File "/g/emcf/schorb/code/mobie-utils-python/mobie/migration/migrate_project.py", line 35, in main
    migrate_project_v3(args.root)
  File "/g/emcf/schorb/code/mobie-utils-python/mobie/migration/migrate_v3/migrate_project.py", line 20, in migrate_project
    migrate_dataset(ds_folder)
  File "/g/emcf/schorb/code/mobie-utils-python/mobie/migration/migrate_v3/migrate_dataset.py", line 129, in migrate_dataset
    validate_dataset(folder, require_local_data=False, require_remote_data=False)
  File "/g/emcf/schorb/code/mobie-utils-python/mobie/validation/dataset.py", line 24, in validate_dataset
    validate_with_schema(dataset_metadata, "dataset")
  File "/g/emcf/schorb/code/mobie-utils-python/mobie/validation/utils.py", line 51, in validate_with_schema
    jsonschema.validate(instance=metadata, schema=schema)
  File "/g/emcf/software/python/miniconda/envs/mobie/lib/python3.10/site-packages/jsonschema/validators.py", line 1022, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('name' was unexpected)
```

**Comment by martinschorb** [comment]
so it seems that what the Project Creator produces does not meet any spec...

**Comment by constantinpape** [comment]
@martinschorb could you zip this project and send it to me? Then I can change what would actually need to change to make it adhere to the spec again.

**Comment by martinschorb** [comment]
All metadata is here:

https://github.com/mobie/parallel_CLEM

I have not yet uploadeded the image data to s3. Let me know if you need that as well...

**Comment by constantinpape** [comment]
Here's what would need to change: https://github.com/mobie/parallel_CLEM/pull/1
That looks manageable to me. My guess is that the converter is actually writing v0.3 spec already, but:
- that it writes `v0.2` in the spec is an oversight
- the serialization of `name` is caused by some changes in the json serialization
- the change in the color string was quite recent

**Comment by martinschorb** [comment]
Cool.
My suggestion then would be to:
- try and fix this, such that the Project Creator generates a valid current `v3`  spec.
- freeze everything at that state and move to the next version number of the spec for all developments.
- make sure there is ongoing future support for ` v3`  projects in the Viewer and mobie-python (migration should be sufficient)
- then we can at least leave the Project Creator included in the viewer for the intermediate future.

**Comment by martinschorb** [comment]
I also noticed that there is no Github release associated with the publication. We should create one that matches what we describe in there.

**Comment by constantinpape** [comment]
Just fyi @martinschorb: we are working on CI and bringing the ProjectCreator up-to-date here: #1028
