### ISSUE TITLE
Project creator broken

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1031]
Hi,

images generated by the Project creater do no longer open in MoBIE Beta. The project validates correctly.

- open `leaf` from ImageJ sample images
- convert to 8 bit
- create a MoBIE project with the Project Creator
- add a dataset and the current image as source.
- fails with both `image` and `segmentation` source type.

```
Exception in thread "Thread-52" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.embl.mobie.lib.ThreadHelper.waitUntilFinished(ThreadHelper.java:110)
	at org.embl.mobie.MoBIE.initDataSources(MoBIE.java:1041)
	at org.embl.mobie.lib.view.ViewManager.initData(ViewManager.java:348)
	at org.embl.mobie.lib.view.ViewManager.show(ViewManager.java:251)
	at org.embl.mobie.MoBIE.openAndViewDataset(MoBIE.java:765)
	at org.embl.mobie.MoBIE.openAndViewDataset(MoBIE.java:690)
	at org.embl.mobie.MoBIE.openMoBIEProject(MoBIE.java:240)
	at org.embl.mobie.MoBIE.<init>(MoBIE.java:172)
	at org.embl.mobie.command.open.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:57)
	at org.embl.mobie.lib.create.ui.ProjectsCreatorPanel.lambda$addButtonsPanel$8(ProjectsCreatorPanel.java:317)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.embl.mobie.lib.ThreadHelper.waitUntilFinished(ThreadHelper.java:102)
	... 10 more
Caused by: java.lang.NullPointerException
	at org.embl.mobie.MoBIE.initImage(MoBIE.java:1176)
	at org.embl.mobie.MoBIE.initDataSource(MoBIE.java:1052)
	at org.embl.mobie.MoBIE.lambda$initDataSources$0(MoBIE.java:1036)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by constantinpape** [comment]
Have you checked the project with the validator from mobie-python?

**Comment by martinschorb** [comment]
yes, validates correctly for the image case.
I get some weird error for the segmentation which I currently try to understand.

```
Found duplicate table columns {'anchor_y', 'anchor_x', 'bb_max_y', 'bb_min_z', 'bb_max_x', 'bb_max_z', 'bb_min_x', 'bb_min_y', 'anchor_z'} in tables: ['default.tsv']
```

However, the table has no duplicate columns.

```
label_id	anchor_x	anchor_y	anchor_z	bb_min_x	bb_min_y	bb_min_z	bb_max_x	bb_max_y	bb_max_z
...
```

 Maybe it is because there are overlapping labels (from the original image which is not a label mask). Then the error message is misleading.

**Comment by constantinpape** [comment]
Can you zip the project and upload it?

**Comment by martinschorb** [comment]
[data.zip](https://github.com/mobie/mobie-viewer-fiji/files/11395587/data.zip)

here you go...

**Comment by martinschorb** [comment]
It does not seem to be a problem with that particular image:

Tested again from scratch with this file for both image and segmentation input:

[labels.tif.zip](https://github.com/mobie/mobie-viewer-fiji/files/11397372/labels.tif.zip)

The project validates with the image source only but throws the same error when either adding the segmentation or creating a new project with just the segmentation.

And the viewer throws the `NullPointerException` regardless of what the project contains.

**Comment by constantinpape** [comment]
@martinschorb : regarding the error message from the validator: it is correct and is thrown because of this in the view:
```
            "additionalTables": [
              "default.tsv"
            ],  
```
`default.tsv` should not be in the `additionalTables` list, because it is not an additional table to be loaded.

Besides this issue the project opens just fine for me in the latest MoBIE-beta:

![image](https://user-images.githubusercontent.com/4263537/236301125-b18ba863-d5e1-48f2-902c-232f8fa55672.png)

How did you try to open it? Maybe you're using an outdated MoBIE?

**Comment by constantinpape** [comment]
@tischi we need to update this line: https://github.com/mobie/mobie-viewer-fiji/blob/10cbbda587bf89c2fc9f90c104dcb03b81974907/src/main/java/org/embl/mobie/lib/serialize/display/SegmentationDisplay.java#L119 so that `default.tsv` is not serialized, i.e. filter it out from `tables` before setting the `additonalTables`.

**Comment by tischi** [comment]
Unfortunately my commit also contains a bunch of other things, but I think it should fix it. I will upload it to MoBIE-beta later today.

**Comment by martinschorb** [comment]
seems to be fixed, thanks!
