### ISSUE TITLE
absolute dataset path in xml does not work

### ISSUE THREAD

**Issue by jhennies** [mobie/mobie-viewer-fiji#1048]
@tischi 

Exception in thread "Thread-24" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /media/julian/Data/tmp/cebra_em_update_mobie/test00/data/CebraINF/images/bdv-n5/media/julian/Data/datasets/20140801_hela-wt_xy5z8nm_as.n5/setup0/attributes.json
	at org.embl.mobie.lib.ThreadHelper.waitUntilFinished(ThreadHelper.java:110)
	at org.embl.mobie.MoBIE.initDataSources(MoBIE.java:725)
	at org.embl.mobie.lib.view.ViewManager.initData(ViewManager.java:349)
	at org.embl.mobie.lib.view.ViewManager.show(ViewManager.java:252)
	at org.embl.mobie.lib.ui.UserInterfaceHelper.lambda$createViewSelectionPanel$17(UserInterfaceHelper.java:780)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /media/julian/Data/tmp/cebra_em_update_mobie/test00/data/CebraINF/images/bdv-n5/media/julian/Data/datasets/20140801_hela-wt_xy5z8nm_as.n5/setup0/attributes.json
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.embl.mobie.lib.ThreadHelper.waitUntilFinished(ThreadHelper.java:102)
	... 5 more
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /media/julian/Data/tmp/cebra_em_update_mobie/test00/data/CebraINF/images/bdv-n5/media/julian/Data/datasets/20140801_hela-wt_xy5z8nm_as.n5/setup0/attributes.json
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.open(N5ImageLoader.java:228)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:264)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:117)
	at bdv.AbstractSpimSource.<init>(AbstractSpimSource.java:156)
	at bdv.SpimSource.<init>(SpimSource.java:44)
	at org.embl.mobie.lib.image.SpimDataImage.createSourcePair(SpimDataImage.java:155)
	at org.embl.mobie.lib.image.SpimDataImage.open(SpimDataImage.java:150)
	at org.embl.mobie.lib.image.SpimDataImage.getSourcePair(SpimDataImage.java:96)
	at org.embl.mobie.MoBIE.initDataSource(MoBIE.java:742)
	at org.embl.mobie.MoBIE.lambda$initDataSources$0(MoBIE.java:720)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.nio.file.NoSuchFileException: /media/julian/Data/tmp/cebra_em_update_mobie/test00/data/CebraINF/images/bdv-n5/media/julian/Data/datasets/20140801_hela-wt_xy5z8nm_as.n5/setup0/attributes.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at org.janelia.saalfeldlab.n5.N5FSReader$LockedFileChannel.<init>(N5FSReader.java:69)
	at org.janelia.saalfeldlab.n5.N5FSReader$LockedFileChannel.openForReading(N5FSReader.java:58)
	at org.janelia.saalfeldlab.n5.N5FSReader.getAttributes(N5FSReader.java:161)
	at org.janelia.saalfeldlab.n5.AbstractGsonReader.getAttribute(AbstractGsonReader.java:128)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.createSetupImgLoader(N5ImageLoader.java:270)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.open(N5ImageLoader.java:215)
	... 14 more

**Comment by tischi** [comment]
@martinschorb @constantinpape did you recently (ever) use the **absolute** path feature of the XML?

```
<n5 type="absolute">/media/julian/Data/datasets/20140801_hela-wt_xy5z8nm_as.n5</n5>
```

Apparently it broke at some point, probably due to changes in mobie-io.

@KateMoreva do you know anything about this?

**Comment by constantinpape** [comment]
I haven't used this myself ever. So I am also not sure if it ever worked.
