### ISSUE TITLE
Opening a single file triple (image, labels, table) fails

### ISSUE THREAD

**Issue by k-dominik** [mobie/mobie-viewer-fiji#1052]
Heya @tischi,

I'm trying to check out some very simple data: a 2D tiff image file, a corresponding label image (ilastik hdf5) and a `.csv` table from ilastik (see also attached zip). When I go via the menu _MoBiE -> Open -> Open Image and Labels_ and add those files there, I get the following error. Am I using it wrong?

<details>
<summary>traceback</summary>

```
images: [/Users/kutra/data/2d_cells_apoptotic_1channel.tif]
labels: [/Users/kutra/data/2d_cells_apoptotic_1channel_Object Identities.h5]
tables: [/Users/kutra/data/2d_cells_apoptotic_1channel_table.csv]
[ERROR] Command errored: Open Image and Labels...
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.embl.mobie.lib.files.LabelFileSources.<init>(LabelFileSources.java:95)
	at org.embl.mobie.lib.files.SourcesFromPathsCreator.<init>(SourcesFromPathsCreator.java:35)
	at org.embl.mobie.MoBIE.<init>(MoBIE.java:182)
	at org.embl.mobie.command.open.OpenImageAndLabelsCommand.run(OpenImageAndLabelsCommand.java:79)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

</details>

Attachements:
* [mobie_example_data.zip](https://github.com/mobie/mobie-viewer-fiji/files/12122322/mobie_example_data.zip)

**Comment by tischi** [comment]
@k-dominik currently for ilastik tables I am assuming those column names:

```
public class IlastikSegmentColumnNames implements SegmentColumnNames
{
	private static final String NONE = "None";
	private static final String LABEL_ID = "labelimageId";
	private static final String[] ANCHOR = { "Object_Center_0", "Object_Center_1", "Object_Center_2" };
	private static final String[] BB_MIN = { "Bounding_Box_Minimum_0", "Bounding_Box_Minimum_1", "Bounding_Box_Minimum_2" };
	private static final String[] BB_MAX = { "Bounding_Box_Maximum_0", "Bounding_Box_Maximum_1", "Bounding_Box_Maximum_2" };
	private static final String TIMEPOINT = "frame";
```

That does not seem to match the table that you attached.  

For instance, in the attached table there are column names such as:

- `Bounding Box Minimum_1`, missing some of the `_` that I currently assume
- `labelimage_oid`, different from the `labelimageId` that I currently have

Do you know what is going on?

**Comment by tischi** [comment]
Issue branch: `issue1052`

**Comment by k-dominik** [comment]
new branch `ilastik_tables`

**Comment by tischi** [comment]
@k-dominik is that issue still valid?

**Comment by k-dominik** [comment]
How amazing is this - the current MOBIE-beta works!!

<img width="294" alt="image" src="https://github.com/mobie/mobie-viewer-fiji/assets/24434157/f45ddeec-f5f0-4e4b-b40d-f6ec19b567cb">
