### ISSUE TITLE
Open MoBIE Project Advanced still checking for old file

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#108]
Hi,

it seems that `Open MoBIE Project Advanced` is still checking for a `versions.json` instead of a `datasets.json` file.

```
[ERROR] Module threw exception
java.lang.UnsupportedOperationException: Could not open or parse versions file: /Volumes/emcf/Hamburg_XRay/20200515/Mobie/data
	at de.embl.cba.mobie.dataset.DatasetsParser.datasetsFromDataSource(DatasetsParser.java:29)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:65)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:49)
	at de.embl.cba.mobie.command.OpenMoBIEProjectAdvancedCommand.run(OpenMoBIEProjectAdvancedCommand.java:22)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I don't know if I have the latest version since Fiji update is down atm.

**Comment by tischi** [comment]
Thanks! I never got around implementing the new open advanced functionality. 
I will do it asap!

**Comment by constantinpape** [comment]
I just tested this and for me it works.
I can open [this](https://github.com/mobie/autophagosomes-clem-datasets/tree/master/data) in advanced mode.

**Comment by martinschorb** [comment]
From the group share it fails for me...

`/Volumes/emcf/Hamburg_XRay/20200515/Mobie/data`

**Comment by martinschorb** [comment]
do you have the latest jar somewhere, so I can test it with that version? I don't know what I am on here, and the updater still doesn't work.

**Comment by martinschorb** [comment]
So, indeed, this one seems to be something else, maybe it's wrong with that dataset.
```
java.io.FileNotFoundException: /Volumes/emcf/Hamburg_XRay/Mobie/data/null/images/images.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at de.embl.cba.tables.FileAndUrlUtils.getInputStream(FileAndUrlUtils.java:103)
	at de.embl.cba.mobie.image.ImagesJsonParser.getJsonReader(ImagesJsonParser.java:56)
	at de.embl.cba.mobie.image.ImagesJsonParser.parseImagesJson(ImagesJsonParser.java:38)
	at de.embl.cba.mobie.image.ImagesJsonParser.getImagePropertiesMap(ImagesJsonParser.java:27)
	at de.embl.cba.mobie.image.SourcesModel.fetchSources(SourcesModel.java:67)
	at de.embl.cba.mobie.image.SourcesModel.<init>(SourcesModel.java:47)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:74)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:49)
	at de.embl.cba.mobie.command.OpenMoBIEProjectAdvancedCommand.run(OpenMoBIEProjectAdvancedCommand.java:22)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at de.embl.cba.mobie.image.SourcesModel.addSources(SourcesModel.java:81)
	at de.embl.cba.mobie.image.SourcesModel.fetchSources(SourcesModel.java:68)
	at de.embl.cba.mobie.image.SourcesModel.<init>(SourcesModel.java:47)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:74)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:49)
	at de.embl.cba.mobie.command.OpenMoBIEProjectAdvancedCommand.run(OpenMoBIEProjectAdvancedCommand.java:22)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Module threw exception
java.lang.UnsupportedOperationException
	at de.embl.cba.mobie.image.SourcesModel.fetchSources(SourcesModel.java:72)
	at de.embl.cba.mobie.image.SourcesModel.<init>(SourcesModel.java:47)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:74)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:49)
	at de.embl.cba.mobie.command.OpenMoBIEProjectAdvancedCommand.run(OpenMoBIEProjectAdvancedCommand.java:22)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martinschorb** [comment]
this `null` directory doesn't exist. Here's what I have in the n5:

```
drwx------  1 schorb  staff  16384 Jul  3 11:37 TAH01
drwx------  1 schorb  staff  16384 Jul  3 11:37 TAH02
drwx------  1 schorb  staff  16384 Jul  2 16:12 TAT01
drwx------  1 schorb  staff  16384 Jul  2 16:13 TAT02
-rwx------  1 schorb  staff     74 Jul  2 16:33 datasets.json
```

**Comment by martinschorb** [comment]
with the json looking good to me:

```
{
  "datasets": [
    "TAT01",
    "TAH01",
    "TAT02",
    "TAH02"
  ]
}
```

**Comment by constantinpape** [comment]
@martinschorb can you try to add a default dataset like here:
https://github.com/mobie/autophagosomes-clem-datasets/blob/master/data/datasets.json#L8

**Comment by martinschorb** [comment]
Yes, that's it! Works

@constantinpape doesn't your converter create this entry for the initial dataset?

**Comment by constantinpape** [comment]
> @constantinpape doesn't your converter create this entry for the initial dataset?

No, I think you still need to set `is_default=True`. But it would make sense to change it such that the first dataset is declared as default even if `is_default=False`. I will change it.

**Comment by martinschorb** [comment]
Where does MoBIE take the default minmax from? These datasets open with (0,255) which seems to be some default setting even though they are 16bit data.

**Comment by constantinpape** [comment]
> Where does MoBIE take the default minmax from? These datasets open with (0,255) which seems to be some default setting even though they are 16bit data.

Yes, I haven't gotten around to change this to something more clever that infers this from the data.
For now, you can do one of this:
1. When you call [add_image_data](https://github.com/mobie/mobie-utils-python/blob/master/mobie/image_data.py#L10), you can pass `settings={'type': 'image', 'contrastLimits': [<MINVAL>, <MAXVAL>], 'color': 'white'}` (of course you can also choose another color).
2. Change it manually in the `images.json` file: https://github.com/mobie/covid-em-datasets/blob/master/data/Covid19-S4-Area3/images/images.json#L4-L7

**Comment by tischi** [comment]
We could also add a new convention that if those values are, e.g. `-1, -1` MoBIE does an auto-contrast.
However, since we are lazy-loading from big image data this may be a bit slow, but we could test it.

**Comment by martinschorb** [comment]
@nicokiaru has a pretty fast auto-contrast in bdv-playground.

Have you already thought about how much effort it would be to use BDV-PG as a backend for mobie? Then we could use all the nice multi-source functionality as well.

**Comment by tischi** [comment]
> Have you already thought about how much effort it would be to use BDV-PG as a backend for mobie? Then we could use all the nice multi-source functionality as well.

Of course, this is the dream! Not sure when I get around to do this though, but it definitely is on my agenda!

**Comment by constantinpape** [comment]
> We could also add a new convention that if those values are, e.g. `-1, -1` MoBIE does an auto-contrast.
> However, since we are lazy-loading from big image data this may be a bit slow, but we could test it.

Good idea. Initially, you could also set the contrast to `0, min(DTYPE)` for integers and `0, 1` for floats.

**Comment by martinschorb** [comment]
Hi,

I tried to provide correct min/max values in the `images.json` for each dataset. 
The viewer however seems to ignore those and reverts back to the 0/255 defaults.

**Comment by constantinpape** [comment]
> Hi,
> 
> I tried to provide correct min/max values in the `images.json` for each dataset.
> The viewer however seems to ignore those and reverts back to the 0/255 defaults.

Ok, I think then @tischi needs to check what happens in the viewer.

**Comment by constantinpape** [comment]
This should all be resolved.
