### ISSUE TITLE
cannot serialize org.embl.mobie.lib.bdv.MobieBdvSupplier;

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1097]
Hi @nicokiaru,

The below error happens during the build and can be resolved with `mvn clean compile`.

However, while this used to happen sporadically, it now happens almost every 2nd build and is really annoying.

Do you have any idea how to fix this more robustly?

```
Exception in thread "main" com.google.gson.JsonParseException: cannot serialize org.embl.mobie.lib.bdv.MobieBdvSupplier; did you forget to register a subtype?
	at sc.fiji.persist.RuntimeTypeAdapterFactory$1.write(RuntimeTypeAdapterFactory.java:331)
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:196)
	at com.google.gson.Gson.toJson(Gson.java:842)
	at com.google.gson.Gson.toJson(Gson.java:812)
	at com.google.gson.Gson.toJson(Gson.java:759)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.setDefaultBdvSupplier(SourceAndConverterBdvDisplayService.java:133)
	at org.embl.mobie.lib.bdv.view.SliceViewer.createBdv(SliceViewer.java:215)
	at org.embl.mobie.lib.bdv.view.SliceViewer.getBdvHandle(SliceViewer.java:121)
	at org.embl.mobie.lib.bdv.view.SliceViewer.<init>(SliceViewer.java:94)
	at org.embl.mobie.lib.view.ViewManager.<init>(ViewManager.java:101)
	at org.embl.mobie.MoBIE.buildUI(MoBIE.java:419)
	at org.embl.mobie.MoBIE.initUIandShowView(MoBIE.java:274)
	at org.embl.mobie.MoBIE.openImagesAndLabels(MoBIE.java:223)
	at org.embl.mobie.MoBIE.<init>(MoBIE.java:175)
```

**Comment by tischi** [comment]
Thanks @NicoKiaru, I did something similar and that indeed seems to help!
