### ISSUE TITLE
trouble opening files via regex

### ISSUE THREAD

**Issue by k-dominik** [mobie/mobie-viewer-fiji#1101]
I currently have troubles opening files via regexes in MoBiE:

I go via the menu: _MoBiE_ -> _open_ -> _Open Image and Labels..._ and get the following error

```java
[ERROR] Command errored: Open Image and Labels...
java.lang.IndexOutOfBoundsException: Index (1) is greater than or equal to list size (1)
	at it.unimi.dsi.fastutil.bytes.ByteArrayList.getByte(ByteArrayList.java:267)
	at tech.tablesaw.columns.strings.ByteDictionaryMap.getValueForIndex(ByteDictionaryMap.java:142)
	at tech.tablesaw.api.StringColumn.get(StringColumn.java:185)
	at tech.tablesaw.columns.strings.AbstractStringColumn.getString(AbstractStringColumn.java:42)
	at tech.tablesaw.table.Relation.getString(Relation.java:713)
	at tech.tablesaw.table.Relation.getString(Relation.java:701)
	at org.embl.mobie.lib.files.FileSourcesDataSetter.addGridView(FileSourcesDataSetter.java:158)
	at org.embl.mobie.lib.files.FileSourcesDataSetter.addDataAndDisplaysAndViews(FileSourcesDataSetter.java:115)
	at org.embl.mobie.MoBIE.openImagesAndLabels(MoBIE.java:221)
	at org.embl.mobie.MoBIE.<init>(MoBIE.java:175)
	at org.embl.mobie.command.open.OpenImageAndLabelsCommand.run(OpenImageAndLabelsCommand.java:79)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

example regex for these files would be `iso-.*.png`

[example-png-no-open.zip](https://github.com/mobie/mobie-viewer-fiji/files/14332069/example-png-no-open.zip)

**Comment by tischi** [comment]
WOW, there were many things broken 🤯 ...not sure when this happened; MoBIE needs tests....

If all your images look the same then this would work now:

<img width="1465" alt="image" src="https://github.com/mobie/mobie-viewer-fiji/assets/2157566/37f4deed-3e73-4056-a3a7-e6371e27c773">

---------

Would you have more complex scenarios for me to test, maybe also something with labels and/or pixel probabilities?

**Comment by k-dominik** [comment]
I'll produce something!

**Comment by tischi** [comment]
In fact, we have something already for single images:

https://github.com/mobie/mobie-viewer-fiji/blob/main/src/test/java/org/embl/mobie/command/OpenIlastik2DImageAndSegmentationCommandTest.java

Another issue here is that the test are not run....

**Comment by k-dominik** [comment]
Hi Tischi,

I created some data that could be used for testing. It contains `raw` (raw data) `pc` (pixel classification prediction maps) and `oc` (object classification label image + tables):

<details><summary>data layout</summary>

```
.
├── README.txt
├── oc                                          # object classification results
│   ├── iso.2602_Object Identities.h5
│   ├── iso.2602_table.csv
│   ├── iso.2603_Object Identities.h5
│   ├── iso.2603_table.csv
│   ├── iso.2604_Object Identities.h5
│   └── iso.2604_table.csv
├── pc                                          # pixel classification results
│   ├── iso.2602_Probabilities.h5
│   ├── iso.2603_Probabilities.h5
│   └── iso.2604_Probabilities.h5
└── raw                                         # raw data
    ├── iso.2602.png
    ├── iso.2603.png
    └── iso.2604.png
```

</details>


I have confirmed that I can  open these individually in MoBiE (_not_ using regexes).

[MoBiE-ilastik-example-output-multiple.zip](https://github.com/mobie/mobie-viewer-fiji/files/14342329/MoBiE-ilastik-example-output-multiple.zip)

**Comment by tischi** [comment]
Thanks! Great test case!

Spaces in file names... `iso.2603_Object Identities.h5` not ideal... ;-)

**Comment by k-dominik** [comment]
I know, but that is default output of ilastik (unfortunately). Plus I thought it adds to the challenge :). While you can enforce no spaces for your own work, people will be adding spaces :D

**Comment by tischi** [comment]
Works:

```
		final OpenMultipleImagesAndLabelsCommand command = new OpenMultipleImagesAndLabelsCommand();
		command.image0 = new File( "src/test/resources/ilastik-multiple/raw/iso.*.png" );
		command.image1 = new File( "src/test/resources/ilastik-multiple/pc/iso..*_Probabilities.h5" );
		command.labels0 = new File( "src/test/resources/ilastik-multiple/oc/iso..*_Object Identities.h5" );
		command.table0 = new File( "src/test/resources/ilastik-multiple/oc/iso..*_table.csv" );
		command.run();
```


<img width="1469" alt="image" src="https://github.com/mobie/mobie-viewer-fiji/assets/2157566/6d242af7-b83d-473d-ab1a-6a30107a7b9b">

**Comment by tischi** [comment]
[This is still not ideal.](https://github.com/mobie/mobie-viewer-fiji/issues/1103).
