### ISSUE TITLE
Open HCS Dataset fails if it encounters unknown directories

### ISSUE THREAD

**Issue by tibuch** [mobie/mobie-viewer-fiji#1132]
Hello,

I have created a ome-zarr plate which contains additional directories in the directory tree. These directories are not part of the official NGFF spec and can simply be ignored. My zarr plate looks like this:
```
plate.zarr
├── C
│   ├── 07
│   │   └── 0
│   │       ├── 0
│   │       ├── 1
│   │       ├── 2
│   │       ├── 3
│   │       ├── 4
│   │       ├── 5
│   │       ├── 6
│   │       ├── histogram_ch0.npz   <-- is ignored
│   │       ├── histogram_ch1.npz
│   │       ├── histogram_ch2.npz
│   │       ├── histogram_ch3.npz
│   │       └── mask                <-- unexpected, but should be ignored
...
```

Log:
```
# MoBIE
Opening: /path/to/plate.zarr
Looking for image files...
Parsing 47 wells...
Initialising (1/47): C/07
Initialising (2/47): F/22
Initialising (5/47): D/03
Initialising (3/47): E/20
Initialising (6/47): D/04
Initialising (8/47): D/08
Initialising (4/47): E/19
Initialising (12/47): F/17
Initialising (16/47): G/05
Initialising (32/47): J/18
Parsed 47 wells in 230 ms, using up to 11 thread(s).
Found 47 image files in 534 ms.
HCS pattern: OMEZarr
Image data format: ome.zarr
Parsing metadata...
Fetching metadata for setup 0 from /path/to/plate.zarr/D/08/0/mask
```

Exception:
```
(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_172 [64-bit]; Linux 5.15.0-82-generic; 1723MB of 16000MB (10%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:128)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.getMatchedGroupIndex(Matcher.java:1314)
	at java.util.regex.Matcher.group(Matcher.java:572)
	at org.embl.mobie.lib.hcs.HCSPattern.getWellGroup(HCSPattern.java:292)
	at org.embl.mobie.lib.hcs.Plate.buildPlateMap(Plate.java:279)
	at org.embl.mobie.lib.hcs.Plate.<init>(Plate.java:163)
	at org.embl.mobie.MoBIE.openHCSDataset(MoBIE.java:263)
	at org.embl.mobie.MoBIE.<init>(MoBIE.java:153)
	at org.embl.mobie.command.open.OpenHCSDatasetCommand.run(OpenHCSDatasetCommand.java:87)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	... 6 more
```

I tried to debug and potential fix but encountered #1131.

**Comment by tischi** [comment]
Thanks for looking into this. 
I answered in the other issue.

**Comment by tibuch** [comment]
I was too quick in assuming that my zarr file was correct :upside_down_face: 

In my well attributes `plate.zarr/C/07/.zattrs` I pointed to `0/mask` instead of `0`. The correct version, which works as expected is:
```
{
    "well": {
        "images": [
            {
                "path": "0"
            }
        ],
        "version": "0.4"
    }
}
```

**Comment by tischi** [comment]
As a nice side-effect we have not ij-utils 0.7.0 on maven 😅
