### ISSUE TITLE
Beta - edit MoBIE project broken

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1134]
Hi,

- `git clone https://github.com/mobie/clem-example-project`
- edit MobIE project with the new folder (works in release MoBIE)
```
[ERROR] Command errored: Edit MoBIE Project...
org.janelia.saalfeldlab.n5.N5Exception$N5IOException: No container exists at /home/martin/code/imaging/clem-example-project/data/yeast/images/local/./em-segmentation.n5
	at org.janelia.saalfeldlab.n5.N5KeyValueReader.<init>(N5KeyValueReader.java:144)
	at org.janelia.saalfeldlab.n5.N5KeyValueReader.<init>(N5KeyValueReader.java:86)
	at org.janelia.saalfeldlab.n5.N5FSReader.<init>(N5FSReader.java:68)
	at org.janelia.saalfeldlab.n5.N5FSReader.<init>(N5FSReader.java:131)
	at bdv.img.n5.N5ImageLoader.open(N5ImageLoader.java:137)
	at bdv.img.n5.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:195)
	at bdv.img.n5.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:81)
	at bdv.AbstractSpimSource.<init>(AbstractSpimSource.java:156)
	at bdv.SpimSource.<init>(SpimSource.java:44)
	at org.embl.mobie.io.imagedata.SpimDataImageData.getSourcePair(SpimDataImageData.java:70)
	at org.embl.mobie.lib.MoBIEHelper.fetchVoxelDimensions(MoBIEHelper.java:210)
	at org.embl.mobie.lib.create.ProjectCreator.readVoxelUnitFromImage(ProjectCreator.java:238)
	at org.embl.mobie.lib.create.ProjectCreator.<init>(ProjectCreator.java:105)
	at org.embl.mobie.lib.create.ui.ProjectsCreatorUI.<init>(ProjectsCreatorUI.java:98)
	at org.embl.mobie.command.write.EditMoBIEProjectCommand.run(EditMoBIEProjectCommand.java:62)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by tischi** [comment]
@K-Meech same here, could you please have a look whether that works for you?

**Comment by tischi** [comment]
That would be lovely @K-Meech !

**Comment by tischi** [comment]
@K-Meech do you have any timeline for this? To be honest, I would like to release still this week.

@martinschorb do you have a sense for how many people would actually run into this? My feeling is that currently you may be the main user of this feature...

**Comment by K-Meech** [comment]
@tischi I started looking at this last week, but it's a harder fix than I first thought. The issue is that in the old version (when using n5 xml), a locally cloned copy of a remote project will still contain all the xmls with voxel size/unit information. For an ome-zarr file, this metadata is inside the image itself, and so the voxel size info will not be available for a remote project.

The project creator would have to be changed to allow opening of local or remote images to extract the voxel size / voxel unit information. (while still prioritising local as it's faster to open + means the project creator doesn't need an internet connection for most projects). Should be possible - but I could only get to this next week!

I was curious what the main use-case is for editing a project in the project creator that has no local images. Is it mainly to add new datasets / edit their names?

**Comment by tischi** [comment]
@K-Meech why, at all, does the Project Creator need the voxels sizes of the remote images when being in Editing mode?

**Comment by K-Meech** [comment]
It needs to know the unit being used for the voxel size, to ensure any additional images that are added use the same.

**Comment by tischi** [comment]
I see, that unit is not in the dataset.json? Maybe we should add it there as this is something global...? 

Something else, please work from now on against the current main branch, as I just merged...
Can't release yet because of https://github.com/mobie/mobie-viewer-fiji/issues/1139 ...

**Comment by K-Meech** [comment]
As far as I can see, there's no unit metdata in the `dataset.json`. Might be a good idea to add it though! (It'd be a lot easier to retrieve for this kind of thing...)

**Comment by constantinpape** [comment]
I agree that we can add the reference unit to the metadata. If you make a suggestion for how to do it I can add it to the spec.

**Comment by K-Meech** [comment]
Great - thanks! Maybe just `voxelUnit` as a string field at the top level of the `dataset.json`? The idea is the same unit should be used for all images in the dataset, so I don't think we'd need a field in each source?

**Comment by tischi** [comment]
That would work for me; so this would live next to `is2D` right? I think that woud be very appropriate!

```
public class Dataset
{
	private boolean is2D = false;
	private ViewerTransform defaultLocation = new PositionViewerTransform( new double[]{0,0,0}, 0 );
	private Map< String, DataSource > sources = new HashMap<>();
	private Map< String, View > views = new LinkedHashMap<>();
        ....
```
