### ISSUE TITLE
Test not running for RemoteMetadataCreator ? 

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1140]
Hi @K-Meech,

- `main` branch
- `mvn test`

I am getting:

```
testImage added to project
Adding metadata for dataset: test
Adding metadata for image: testImage
Image: testImage for dataset:test has no relative path. 
You can't 'link' to images outside the project folder, when uploading to s3
Error - aborting, and removing all ome.zarr.s3 remote metadata
java.io.IOException: Image: testImage for dataset:test has no relative path. 
You can't 'link' to images outside the project folder, when uploading to s3
        at org.embl.mobie.lib.create.RemoteMetadataCreator.addRemoteMetadataForImage(RemoteMetadataCreator.java:104)
        at org.embl.mobie.lib.create.RemoteMetadataCreator.addRemoteMetadataForDataset(RemoteMetadataCreator.java:134)
        at org.embl.mobie.lib.create.RemoteMetadataCreator.addAllRemoteMetadata(RemoteMetadataCreator.java:145)
        at org.embl.mobie.lib.create.RemoteMetadataCreator.createOMEZarrRemoteMetadata(RemoteMetadataCreator.java:178)
        at org.embl.mobie.lib.create.RemoteMetadataCreatorTest.createRemoteMetadataWithImagesOutsideProject(RemoteMetadataCreatorTest.java:134)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImp
````

Could you please have a look?

**Comment by K-Meech** [comment]
@tischi so this is actually expected. [This test in `RemoteMetadataCreatorTest`](https://github.com/mobie/mobie-viewer-fiji/blob/main/src/test/java/org/embl/mobie/lib/create/RemoteMetadataCreatorTest.java#L118) is trying to add remote metadata for a project containing linked images from outside the project (using absolute paths). In this case we [want the project creator to complain](https://github.com/mobie/mobie-viewer-fiji/blob/2413fbaf9ee403d3d4400eff0181e7274b6326ad/src/main/java/org/embl/mobie/lib/create/RemoteMetadataCreator.java#L101) as these images won't get uploaded with the project to S3 - that's why the error message says `Image: testImage for dataset:test has no relative path. 
You can't 'link' to images outside the project folder, when uploading to s3`. This is the expected behaviour that I'm testing for + the test is passing.
