### ISSUE TITLE
BigWarp registration broken

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1172]
Hi,

the BigWarp integration is broken.

- current MoBIE (release)
- open Platybrowser
- right click, registration - BigWarp

```
[ERROR] Command errored: Registration - BigWarp
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:583)
	at org.scijava.module.DefaultMutableModuleItem.setChoices(DefaultMutableModuleItem.java:227)
	at org.embl.mobie.command.context.AbstractRegistrationCommand.initialize(AbstractRegistrationCommand.java:44)
	at org.embl.mobie.command.context.BigWarpRegistrationCommand.initialize(BigWarpRegistrationCommand.java:70)
	at org.scijava.module.process.InitPreprocessor.process(InitPreprocessor.java:59)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:103)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:154)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by tischi** [comment]
When are you teaching?

**Comment by martinschorb** [comment]
Friday

**Comment by martinschorb** [comment]
I will mostly focus on basic functionality and manual registration, but it would be nice to quickly demo BW as well.

**Comment by tischi** [comment]
Should work now, could you please test it?

**Comment by martinschorb** [comment]
no success for me:
MoBIE-viewer is 5.1.6

```
[ERROR] Command errored: Registration - BigWarp
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.embl.mobie.command.context.AbstractRegistrationCommand.initialize(AbstractRegistrationCommand.java:47)
	at org.embl.mobie.command.context.BigWarpRegistrationCommand.initialize(BigWarpRegistrationCommand.java:70)
	at org.scijava.module.process.InitPreprocessor.process(InitPreprocessor.java:59)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:103)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:154)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by tischi** [comment]
I think I found it, but could it be that you had only one image open at the time that you tried that? So, there would not be much to register, is it 😉 ?

**Comment by tischi** [comment]
Please try again...

**Comment by martinschorb** [comment]
> I think I found it, but could it be that you had only one image open at the time that you tried that? So, there would not be much to register, is it 😉 ?

yes, true... ;-)

**Comment by martinschorb** [comment]
it looks like `F2`, `F3` and some other shortcuts don't seem to work. But it could also be that the BigWarp controls have changed with some updates and the help does not yet account for that.
