### ISSUE TITLE
Opening a MoBIE dataset with credentials fails

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#1180]
Opening a MoBIE dataset with S3 Credentials fails for the current MoBIE version from the Fiji update site, see the error message below.

Note: a dataset without credentials opens correctly for me (tested with platybrowser).

@tischi I will share the credentials for this project with you via mail.

```
[ERROR] Command errored: Open MoBIE Project With S3 Credentials...
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: bdv/util/RandomAccessibleIntervalMipmapSource4D
	at org.embl.mobie.lib.ThreadHelper.waitUntilFinished(ThreadHelper.java:112)
	at org.embl.mobie.MoBIE.initDataSources(MoBIE.java:644)
	at org.embl.mobie.lib.view.ViewManager.initData(ViewManager.java:363)
	at org.embl.mobie.lib.view.ViewManager.show(ViewManager.java:258)
	at org.embl.mobie.MoBIE.openAndViewDataset(MoBIE.java:412)
	at org.embl.mobie.MoBIE.openAndViewDataset(MoBIE.java:362)
	at org.embl.mobie.MoBIE.openMoBIEProject(MoBIE.java:219)
	at org.embl.mobie.MoBIE.<init>(MoBIE.java:138)
	at org.embl.mobie.command.open.project.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:63)
	at org.embl.mobie.command.open.project.OpenMoBIEProjectWithS3CredentialsCommand.run(OpenMoBIEProjectWithS3CredentialsCommand.java:56)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: bdv/util/RandomAccessibleIntervalMipmapSource4D
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.embl.mobie.lib.ThreadHelper.waitUntilFinished(ThreadHelper.java:104)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: bdv/util/RandomAccessibleIntervalMipmapSource4D
	at org.janelia.saalfeldlab.n5.bdv.N5Viewer.createSource(N5Viewer.java:875)
	at org.janelia.saalfeldlab.n5.bdv.N5Viewer.buildN5Sources(N5Viewer.java:654)
	at org.janelia.saalfeldlab.n5.bdv.N5Viewer.buildN5Sources(N5Viewer.java:490)
	at org.embl.mobie.io.imagedata.N5ImageData.open(N5ImageData.java:196)
	at org.embl.mobie.io.imagedata.N5ImageData.getSourcePair(N5ImageData.java:77)
	at org.embl.mobie.lib.image.ImageDataImage.createSourcePair(ImageDataImage.java:176)
	at org.embl.mobie.lib.image.ImageDataImage.open(ImageDataImage.java:171)
	at org.embl.mobie.lib.image.ImageDataImage.getSourcePair(ImageDataImage.java:112)
	at org.embl.mobie.MoBIE.initDataSource(MoBIE.java:662)
	at org.embl.mobie.MoBIE.lambda$initDataSources$1(MoBIE.java:639)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more
Caused by: java.lang.ClassNotFoundException: bdv.util.RandomAccessibleIntervalMipmapSource4D
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
```

**Comment by tischi** [comment]
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: bdv/util/RandomAccessibleIntervalMipmapSource4D
```

I think this error is due to some jars that are not up to date (other users also reported this).

Please download a fresh Fiji and install MoBIE and try again.

**Comment by constantinpape** [comment]
Yes, that has fixed it.
