### ISSUE TITLE
'Open Project' is not using aws credentials in default location any more

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#1181]
It is not possible to open a project that needs credentials via the `Open Project ...` menu in case the AWS credentials are stored in the default credentials location, e.g. `~/aws/credentials` on linux. It fails with a permission error (see below).
Right now it is only possible to open such projects via `Open Project with S3 Credentials ...` by entering the credentials manually there.

I assume this was broken when switching to the new n5 library.

It would be nice to have support for loading the default credentials again @tischi , since this makes frequent opening of projects quite a bit more convenient. You can test this with the credentials I shared with you earlier. (But it's not a priority since it is still possible to open the projects.)

```
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: tx00000176bc9dbed744744-0066a10690-526e7a01-default; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5470)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5417)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1373)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1347)
	at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1428)
	at org.embl.mobie.io.util.IOHelper.exists(IOHelper.java:321)
	at org.embl.mobie.MoBIE.setProjectImageAndTableRootLocations(MoBIE.java:370)
	at org.embl.mobie.MoBIE.openMoBIEProject(MoBIE.java:214)
	at org.embl.mobie.MoBIE.<init>(MoBIE.java:138)
	at org.embl.mobie.command.open.project.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:63)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by tischi** [comment]
@constantinpape if you have time and if you have an OME-Zarr on S3 with credentials it would be interesting to know whether opening this in Fiji via `Plugins › BigDataViewer › HDF5/N5/Zarr/OME-NGFF Viewer` works with credentials stored at `~/aws/credentials`.

**Comment by tischi** [comment]
@constantinpape this should be fixed now. Can you confirm?
