### ISSUE TITLE
Adding segmentations via the project creator throws an error

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#1194]
Tests are currently failing due to: `ImagesCreatorTest/addSegmentation`. This correctly flags an issue with adding segmentations via the project creator. To reproduce:
- Open project creator
- Add a dataset
- Add 'current displayed image'
- Select 'Segmentation' under 'Image Type' and ok

Errors with:
```
Exception in thread "Thread-13" java.lang.NullPointerException
	at org.embl.mobie.lib.create.ImagesCreator.addDefaultTableForImage(ImagesCreator.java:375)
	at org.embl.mobie.lib.create.ImagesCreator.updateTableAndJsonsForNewSegmentation(ImagesCreator.java:437)
	at org.embl.mobie.lib.create.ImagesCreator.addImage(ImagesCreator.java:174)
	at org.embl.mobie.lib.create.ui.ProjectsCreatorUI.addCurrentImageDialog(ProjectsCreatorUI.java:685)
	at org.embl.mobie.lib.create.ui.ProjectsCreatorUI.addImageDialog(ProjectsCreatorUI.java:431)
	at org.embl.mobie.lib.create.ui.ProjectsCreatorUI.lambda$null$4(ProjectsCreatorUI.java:290)
	at java.lang.Thread.run(Thread.java:750)
```

Seems to be failing due to this line: `imageDataFormat.setS3SecretAndAccessKey(MoBIE.getInstance().getSettings().values.getS3AccessAndSecretKey() );`

**Comment by tischi** [comment]
Thanks @K-Meech, do you want me to try to fix this or were you going to?

**Comment by tischi** [comment]
Thanks @K-Meech, do you want me to try to fix this or were you going to?

**Comment by tischi** [comment]
Thanks @K-Meech, do you want me to try to fix this or were you going to?

**Comment by K-Meech** [comment]
If you have time - that would be great @tischi !

**Comment by tischi** [comment]
Hi @K-Meech, this should be fixed now. Please reopen if the issue persists.
