### ISSUE TITLE
MoBIE access to credential protected bucket not working

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#1199]
The access to buckets protected with credentials via "Open MoBIE Project With S3 Credentials" is not working anymore. 
It fails with a permission error (see full backtrace below). It used to work a few weeks or so ago when we last tried.
We have verified that the bucket can be accessed, so the problem is on the MoBIE side.

@tischi I will send you the details to reproduce via mail.

cc @Marei33

```
[ERROR] Command errored: Open MoBIE Project With S3 Credentials...
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: tx00000b5ca47d68f3e4f29-00675b0134-526d6c4d-default; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5470)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5417)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1373)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1347)
	at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1428)
	at org.embl.mobie.io.util.IOHelper.exists(IOHelper.java:321)
	at org.embl.mobie.MoBIE.setProjectImageAndTableRootLocations(MoBIE.java:387)
	at org.embl.mobie.MoBIE.openMoBIEProject(MoBIE.java:233)
	at org.embl.mobie.MoBIE.<init>(MoBIE.java:155)
	at org.embl.mobie.command.open.project.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:63)
	at org.embl.mobie.command.open.project.OpenMoBIEProjectWithS3CredentialsCommand.run(OpenMoBIEProjectWithS3CredentialsCommand.java:56)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by tischi** [comment]
All right I think I found the issue.
I refactored the code to use the credentials differently and now they only work for opening OME-Zarr.
I have to implement again that they are also used for other files...

**Comment by tischi** [comment]
@constantinpape could you please update Fiji and try again?

**Comment by constantinpape** [comment]
Yep, it works again.
