### ISSUE TITLE
Mobie viewer crash

### ISSUE THREAD

**Issue by Cubbun** [mobie/mobie-viewer-fiji#1200]
After the update the newest version of the 12th of December 2024. the viewer is not opening any more. When I choose a project and open in MoBIE I get the following messages and it is then stuck until I force shutdown Fiji.

The console gives me:

```
[INFO] Reading available sites from https://imagej.net/
[INFO] Reading available sites from https://imagej.net/
Exception in thread "Thread-24" java.lang.NullPointerException
	at org.embl.mobie.MoBIE.<init>(MoBIE.java:120)
	at org.embl.mobie.command.open.project.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:63)
	at org.embl.mobie.lib.create.ui.ProjectsCreatorUI.lambda$null$7(ProjectsCreatorUI.java:346)
	at java.lang.Thread.run(Thread.java:750)
	
```
	
The Log gives me:

`( Initialised AmazonS3ClientBuilder in 1075 ms. )`

Kind regards

**Comment by tischi** [comment]
Thanks @Cubbun!

I can confirm this! I will fix it today.

**Comment by tischi** [comment]
Does it work again @Cubbun ?

**Comment by Cubbun** [comment]
Perfect thanks.
