### ISSUE TITLE
Mobie project cannot be loaded from git branch

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#128]
It's currently not possible to load a mobie project from a branch other than master.
Both in `Open MoBIE Project` and `Experts->Open Advanced` throw an error if one gives a link to a non master branch:
```
[ERROR] Module threw exception
java.lang.UnsupportedOperationException: Could not open or parse datasets file: https://raw.githubusercontent.com/mobie/covid-tomo-datasets/tree/norm-bookmarks/master/data/datasets.json
	at de.embl.cba.mobie.dataset.DatasetsParser.datasetsFromDataSource(DatasetsParser.java:29)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:78)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:62)
	at de.embl.cba.mobie.ui.command.OpenMoBIEProjectAdvancedCommand.run(OpenMoBIEProjectAdvancedCommand.java:22)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```
It would be really helpful to support this again to test changes on a branch.

I think it's ok to only support this in the expert mode though and instead of supporting pasting the full url we could also add another gui element to select the branch.

**Comment by tischi** [comment]
> I think it's ok to only support this in the expert mode though and instead of supporting pasting the full url we could also add another gui element to select the branch.

Yes, I think there was an issue somewhere where we already discuss some UI for this... 
I will implement ASAP, but probably only have time on Tuesday...

**Comment by tischi** [comment]
This should be fixed via this: https://github.com/mobie/mobie/issues/8

**Comment by constantinpape** [comment]
@tischi
Is this on MoBIE beta already?
I just checked and I can't see how to load a project from a git branch.

**Comment by tischi** [comment]
> Is this on MoBIE beta already?

No, I have nothing currently.

**Comment by constantinpape** [comment]
Ok, let me know when the new changes can be tested.
