### ISSUE TITLE
Specifying paths for new projects

### ISSUE THREAD

**Issue by HernandoMV** [mobie/mobie-viewer-fiji#170]
Error when opening projects created using Mobie:
There seems to be something weird with the path and/or what it is trying to find. Inside 'images' folder there is 'local', 'remote', and 'images.json'

```
Adding source: template25...
C:\Users\herny\Desktop\SWC\Data\Anatomy\ARA_MoBIE/data\ARA25\images\null
mpicbg.spim.data.SpimDataIOException: java.io.FileNotFoundException: C:\Users\herny\Desktop\SWC\Data\Anatomy\ARA_MoBIE\data\ARA25\images\null (The system cannot find the file specified)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:88)
	at de.embl.cba.bdv.utils.BdvUtils.openSpimData(BdvUtils.java:1404)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:89)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:66)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:137)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:48)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:609)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:224)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:473)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:450)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:425)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:71)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:50)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:86)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:60)
	at de.embl.cba.mobie.ui.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:18)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: C:\Users\herny\Desktop\SWC\Data\Anatomy\ARA_MoBIE\data\ARA25\images\null (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:329)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1266)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:84)
	... 24 more
[ERROR] Module threw exception
java.lang.NullPointerException
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:292)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:92)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:66)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:137)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:48)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:609)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:224)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:473)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:450)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:425)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:71)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:50)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:86)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:60)
	at de.embl.cba.mobie.ui.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:18)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Adding source: template25...
C:\Users\herny\Desktop\SWC\Data\Anatomy\ARA_MoBIE\/data\ARA25\images\null
mpicbg.spim.data.SpimDataIOException: java.io.FileNotFoundException: C:\Users\herny\Desktop\SWC\Data\Anatomy\ARA_MoBIE\data\ARA25\images\null (The system cannot find the file specified)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:88)
	at de.embl.cba.bdv.utils.BdvUtils.openSpimData(BdvUtils.java:1404)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:89)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:66)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:137)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:48)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:609)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:224)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:473)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:450)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:425)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:71)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:50)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:86)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:60)
	at de.embl.cba.mobie.ui.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:18)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: C:\Users\herny\Desktop\SWC\Data\Anatomy\ARA_MoBIE\data\ARA25\images\null (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:329)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1266)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:84)
	... 24 more
[ERROR] Module threw exception
java.lang.NullPointerException
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:292)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:92)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:66)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:137)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:48)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:609)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:224)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:473)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:450)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:425)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:71)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:50)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:86)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:60)
	at de.embl.cba.mobie.ui.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:18)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by K-Meech** [comment]
Hey Hernando - can you give me a bit more info? Does this error immediately when you open it in mobie? Or when you are viewing a certain image?
Also, if you go inside the mobie folder, and inside 'images' and 'local' - do you see your image files there? (they should be .h5 or .n5)

**Comment by HernandoMV** [comment]
Yes, this error happens regardless of the format and the images are there. It happens immediately when I try to open the project through MoBIE.

**Comment by K-Meech** [comment]
To open a local MoBIE project, you have to use the command "Open MoBIE Project Expert Mode" (not the "Open MoBIE Project" you usually use)
In the window that pops up, you then put the file path to your project as the project location, image data location and table data location. Also, change the Image Data Storage Modality to 'File System'
Hopefully, this fixes it! I could open your project on my computer with this setup.

**Comment by HernandoMV** [comment]
Amazing. It does work! Thanks!
