### ISSUE TITLE
Crash on clean Fiji install

### ISSUE THREAD

**Issue by MicPhotonIGBMC** [mobie/mobie-viewer-fiji#176]
**Report on the workshop Fiji-MOBIE crash (Image Data: data management, standard image file format for sharing big image data, and image data repositories)**

1- Clean install of Fiji (Windows 10), updated, only MOBIE activated (+ ImageJ, Fiji and Java8 default update sites)
2- Trying Plugins › BigDataViewer › OME ZARR › Open OME ZARR From S3 (Advanced)...
https://s3.embl.de/i2k-2020/em-raw.ome.zarr

Errors below

Thank you for the great tool
Bertrand

[Exception.txt](https://github.com/mobie/mobie-viewer-fiji/files/5893941/Exception.txt)

Exception window (Exception.txt)

****************************************************************
Console
[ERROR] Module threw exception
java.lang.NullPointerException
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.getMultiscale(N5OMEZarrImageLoader.java:235)
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.initSetups(N5OMEZarrImageLoader.java:166)
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.fetchSequenceDescriptionAndViewRegistrations(N5OMEZarrImageLoader.java:125)
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.<init>(N5OMEZarrImageLoader.java:118)
	at de.embl.cba.mobie.n5.zarr.N5S3OMEZarrImageLoader.<init>(N5S3OMEZarrImageLoader.java:84)
	at de.embl.cba.mobie.n5.zarr.OMEZarrS3Reader.readKey(OMEZarrS3Reader.java:42)
	at de.embl.cba.mobie.n5.zarr.OMEZarrS3Reader.readURL(OMEZarrS3Reader.java:57)
	at de.embl.cba.mobie.n5.zarr.ui.OpenOMEZARRFromS3Command.openAndShow(OpenOMEZARRFromS3Command.java:39)
	at de.embl.cba.mobie.n5.zarr.ui.OpenOMEZARRFromS3AdvancedCommand.run(OpenOMEZARRFromS3AdvancedCommand.java:28)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Reading available sites from https://imagej.net/
****************************************************************
[Exception.txt](https://github.com/mobie/mobie-viewer-fiji/files/5893933/Exception.txt)

Log
[Fri Jan 29 13:50:52 CET 2021] [ERROR] [] Module threw exception
java.lang.NullPointerException
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.getMultiscale(N5OMEZarrImageLoader.java:235)
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.initSetups(N5OMEZarrImageLoader.java:166)
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.fetchSequenceDescriptionAndViewRegistrations(N5OMEZarrImageLoader.java:125)
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.<init>(N5OMEZarrImageLoader.java:118)
	at de.embl.cba.mobie.n5.zarr.N5S3OMEZarrImageLoader.<init>(N5S3OMEZarrImageLoader.java:84)
	at de.embl.cba.mobie.n5.zarr.OMEZarrS3Reader.readKey(OMEZarrS3Reader.java:42)
	at de.embl.cba.mobie.n5.zarr.OMEZarrS3Reader.readURL(OMEZarrS3Reader.java:57)
	at de.embl.cba.mobie.n5.zarr.ui.OpenOMEZARRFromS3Command.openAndShow(OpenOMEZARRFromS3Command.java:39)
	at de.embl.cba.mobie.n5.zarr.ui.OpenOMEZARRFromS3AdvancedCommand.run(OpenOMEZARRFromS3AdvancedCommand.java:28)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Fri Jan 29 13:52:05 CET 2021] [INFO] [] Reading available sites from https://imagej.net/

**Comment by tischi** [comment]
@MicPhotonIGBMC 
Thank you very much for the detailed report!

I tried to reproduce it and if I put a URL there that does not exist I get the same error.
However, the URL you posted seems entirely correct.

Best guess I have is some issues with the `/` vs `\` on Mac vs Windows (I have a Mac)

@K-Meech 
Could you please try this (you have Windows 10, isn't it?):
- Plugins › BigDataViewer › OME ZARR › Open OME ZARR From S3 (Advanced)...
- https://s3.embl.de/i2k-2020/em-raw.ome.zarr

**Comment by K-Meech** [comment]
@tischi This works for me on Windows 10 - so I'm not sure what the issue is. Doesn't appear to be Windows specific

**Comment by tischi** [comment]
ok, I will try to implement better error logs, maybe that helps.

**Comment by tischi** [comment]
@MicPhotonIGBMC 
I updated MoBIE to produce a more informative error message.
Could you please try again?
Another suspicion I could have is that maybe just the internet connection was not working properly when you tried last time? 
Please also try the "PlatyBrowser" plugin (also comes with the MoBIE update site). Does that work?

**Comment by MicPhotonIGBMC** [comment]
Good evening,

Sorry for the delay to test the fix.  I tried again as suggested
*** Plugins › BigDataViewer › OME ZARR › Open OME ZARR From S3 (Advanced)...
*** https://s3.embl.de/i2k-2020/em-raw.ome.zarr

And now it does work

Thank you very much for sorting the issue.

Bertrand

**Comment by tischi** [comment]
OK! Thanks!
