### ISSUE TITLE
OME ZARR Improve error message

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#178]
Currently, if one puts a non existing key such as `https://s3.embl.de/i2k-2020/em-raw.ome.za` one gets a rather confusing error message (see below). It would be good if it would throw something like "The key X in bucket Y could not be found"

cc @MicPhotonIGBMC

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.NullPointerException
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.getMultiscale(N5OMEZarrImageLoader.java:235)
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.initSetups(N5OMEZarrImageLoader.java:166)
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.fetchSequenceDescriptionAndViewRegistrations(N5OMEZarrImageLoader.java:125)
	at de.embl.cba.mobie.n5.zarr.N5OMEZarrImageLoader.<init>(N5OMEZarrImageLoader.java:118)
	at de.embl.cba.mobie.n5.zarr.N5S3OMEZarrImageLoader.<init>(N5S3OMEZarrImageLoader.java:84)
```

**Comment by tischi** [comment]
Should be improved now.

**Comment by constantinpape** [comment]
I think the current error message `java.lang.UnsupportedOperationException: Could not find multiscales at service endpoint: https://s3.embl.de; bucket: i2k-2020; container path: em-raw.ome.za; path: ; attribute: multiscales` is good.
