### ISSUE TITLE
Bug (Windows) opening datasets

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#208]
Hi,

no matter when providing a repo or loading one of the pre-defined published datasets, I end up with:

```
[ERROR] Module threw error
java.lang.NoSuchFieldError: valueLimits
	at de.embl.cba.mobie.image.ImagePropertiesToMetadataAdapter.setMetadataFromMutableImageProperties(ImagePropertiesToMetadataAdapter.java:21)
	at de.embl.cba.mobie.image.SourcesModel.addSources(SourcesModel.java:97)
	at de.embl.cba.mobie.image.SourcesModel.fetchSources(SourcesModel.java:70)
	at de.embl.cba.mobie.image.SourcesModel.<init>(SourcesModel.java:47)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:75)
	at de.embl.cba.mobie.ui.command.OpenMoBIEPublishedProjectCommand.selectProject(OpenMoBIEPublishedProjectCommand.java:41)
	at de.embl.cba.mobie.ui.command.OpenMoBIEPublishedProjectCommand.run(OpenMoBIEPublishedProjectCommand.java:24)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by tischi** [comment]
What are you using MoBIE or MoBIE-beta?
It could be that MoBIE is in fact ahead of MoBIE-beta, could this be?
@K-Meech

**Comment by martinschorb** [comment]
That's the release from the ImageJ update site.

**Comment by K-Meech** [comment]
I just tried MoBIE & MoBIE-beta on Windows, and both work for me.
@martinschorb - is your imageJ updated? Also, do you have any other update sites enabled? e.g. for my Crosshair plugin, or one of tischi's older update sites?

**Comment by martinschorb** [comment]
The Fiji says that it's up-to-date. I have EMBL-CBA and BDV-Playground installed as well. this is the basic Fiji on the EMCF VM.

**Comment by K-Meech** [comment]
@tischi Does EMBL-CBA or BDV-playground ship an old version of imagej-utils? That could be the problem.
@martinschorb I imagine if you try it in a clean fiji installation everything should run smoothly

**Comment by martinschorb** [comment]
@tischi when I remove EMBL-CBA, the whole Fiji dies and does not start up again. I also realized that it removed a lot of MoBIE jars when removing EMBL-CBA. So they seem to somehow lock each other up.

**Comment by tischi** [comment]
Just download a new Fiji and install the MoBIE update site.

What do you use EMBL-CBA for? This is completely outdated.

In fact, I will remove the update site from Fiji!
