### ISSUE TITLE
Can't open Platybrowser on current master

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#209]
When trying to open the platybrowser on the current master, it fails with the following error:

```
Adding source: sbem-6dpf-1-whole-raw...
Exception in thread "AWT-EventQueue-1" java.lang.NoClassDefFoundError: bdv/BehaviourTransformEventHandler3D
	at bdv.util.BdvOptions$Values.<init>(BdvOptions.java:277)
	at bdv.util.BdvOptions.<init>(BdvOptions.java:51)
	at bdv.util.BdvOptions.options(BdvOptions.java:59)
	at de.embl.cba.mobie.ui.SourcesDisplayManager.addSourceToBDV(SourcesDisplayManager.java:459)
	at de.embl.cba.mobie.ui.SourcesDisplayManager.showIntensitySource(SourcesDisplayManager.java:444)
	at de.embl.cba.mobie.ui.SourcesDisplayManager.show(SourcesDisplayManager.java:415)
	at de.embl.cba.mobie.bookmark.BookmarkManager.show(BookmarkManager.java:93)
	at de.embl.cba.mobie.bookmark.BookmarkManager.setView(BookmarkManager.java:58)
	at de.embl.cba.mobie.ui.MoBIE.lambda$new$0(MoBIE.java:78)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: bdv.BehaviourTransformEventHandler3D
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 24 more
```

Maybe some dependencies not up-to-date?

**Comment by constantinpape** [comment]
yes, it's there:
```
		<!-- Java 8	Update Site	-->
		<imglib2.version>5.11.1</imglib2.version>
		<imglib2-cache.version>1.0.0-beta-16</imglib2-cache.version>
		<bigdataviewer-core.version>10.2.0</bigdataviewer-core.version>
		<bigdataviewer-vistools.version>1.0.0-beta-28</bigdataviewer-vistools.version>
```
