### ISSUE TITLE
Create dataset converter error

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#210]
Hi,

I am trying to convert from a current image to N5 and I am running into:

during `writing level 2` 

```
[ERROR] Module threw error
java.lang.NoSuchMethodError: net.imglib2.cache.img.ReadOnlyCachedCellImgOptions.cellDimensions([I)Lnet/imglib2/cache/img/ReadOnlyCachedCellImgOptions;
	at bdv.export.n5.WriteSequenceToN5$N5DatasetIO.getImage(WriteSequenceToN5.java:368)
	at bdv.export.ExportScalePyramid.writeScalePyramid(ExportScalePyramid.java:299)
	at bdv.export.n5.WriteSequenceToN5.writeScalePyramid(WriteSequenceToN5.java:255)
	at bdv.export.n5.WriteSequenceToN5.writeN5File(WriteSequenceToN5.java:206)
	at bdv.ij.ExportImagePlusAsN5PlugIn.run(ExportImagePlusAsN5PlugIn.java:274)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

- Fresh Fiji (Win64)
- all updated
- MoBIE release from update site, no other additional plugins

**Comment by K-Meech** [comment]
@martinschorb - do you get the same error if you do Plugins > BigDataViewer > Export Current Image as XML/N5?

**Comment by martinschorb** [comment]
I am trying to find out what goes on. With custom parameters (-> no downsampling) there is no error.
When I give it wrong parameters, (subsampling factors and chunk size not the same dimensions) it enters an infinite loop of error popups.

**Comment by K-Meech** [comment]
Could you email me the link to the image on the server? Then I can look at it locally too. It sounds like an error with the BigDataViewer export plugin, so we'd have to make an issue on their repository: https://github.com/bigdataviewer/bigdataviewer_fiji

**Comment by martinschorb** [comment]
Hi, it is a rather generic volume (from a tomogram reconstruction, MRC imported using BioFormats).

`emcf/schorb/data/join2mobie/`

**Comment by martinschorb** [comment]
Situation:

- Fresh Fiji, export using BDV, exportas N5/XML works.
- Add MoBIE update site, install MoBIE, restart
- BDV export throws:

``` 
[ERROR] Module threw error
java.lang.NoSuchMethodError: net.imglib2.cache.img.ReadOnlyCachedCellImgOptions.cellDimensions([I)Lnet/imglib2/cache/img/ReadOnlyCachedCellImgOptions;
	at bdv.export.n5.WriteSequenceToN5$N5DatasetIO.getImage(WriteSequenceToN5.java:368)
	at bdv.export.ExportScalePyramid.writeScalePyramid(ExportScalePyramid.java:299)
	at bdv.export.n5.WriteSequenceToN5.writeScalePyramid(WriteSequenceToN5.java:255)
	at bdv.export.n5.WriteSequenceToN5.writeN5File(WriteSequenceToN5.java:206)
	at bdv.ij.ExportImagePlusAsN5PlugIn.run(ExportImagePlusAsN5PlugIn.java:274)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

So it has something to do with the MoBIE libraries.

**Comment by K-Meech** [comment]
Thanks for the info!
I think it's a mismatch between the imglib2 versions in the current mobie on that update site. Building the current master locally works.
@tischi Could we maybe update the mobie-beta update site to the current master?

**Comment by tischi** [comment]
@martinschorb 

1. Is this for the MoBIE update site or for MoBIE-beta?

@K-Meech and @martinschorb 

Could you try the following: Fresh Fiji, Update Fiji (_do not add any update sites_), export using BDV

The reason for doing this is that you need to Update Fiji once to get all the latest BDV versions (this is independent of MoBIE).

**Comment by martinschorb** [comment]
>     1. Is this for the MoBIE update site or for MoBIE-beta?

Update site


> Could you try the following: Fresh Fiji, Update Fiji (_do not add any update sites_), export using BDV

This is precisely what I did. And it works. The moment I add MoBIE, also the BDV export fails (see above).

**Comment by tischi** [comment]
OK, indeed the MoBIE update site is still shipping special versions of bdv libraries, which is now not necessary anymore since the official ones are working. I will work on making everything compatible again also on the update site...

**Comment by tischi** [comment]
OK, done (I hope).
Does it work now?

**Comment by martinschorb** [comment]
Works now, thanks!
