### ISSUE TITLE
Can't use 3d viewer from intellij

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#216]
I can't use the 3d viewer from intellij; it fails with

```
3D [dev] 1.6.0-scijava-2-pre11-daily-experimental daily

Exception in thread "Thread-14" java.lang.UnsatisfiedLinkError: Can't load library: /home/pape/Work/mobie/mobie-viewer-fiji/natives/linux-amd64//libgluegen-rt.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1820)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:624)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:421)
	at com.jogamp.common.os.Platform$1.run(Platform.java:317)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:287)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:147)
	at jogamp.opengl.ThreadingImpl$1.run(ThreadingImpl.java:83)
	at jogamp.opengl.ThreadingImpl$1.run(ThreadingImpl.java:66)
	at java.security.AccessController.doPrivileged(Native Method)
	at jogamp.opengl.ThreadingImpl.<clinit>(ThreadingImpl.java:66)
	at com.jogamp.opengl.Threading.disableSingleThreading(Threading.java:164)
	at org.scijava.java3d.JoglPipeline.initialize(JoglPipeline.java:130)
	at org.scijava.java3d.Pipeline.createPipeline(Pipeline.java:92)
	at org.scijava.java3d.MasterControl.loadLibraries(MasterControl.java:837)
	at org.scijava.java3d.VirtualUniverse.<clinit>(VirtualUniverse.java:274)
	at de.embl.cba.tables.view.Segments3dView.initUniverseAndListener(Segments3dView.java:593)
	at de.embl.cba.tables.view.Segments3dView.updateSelectedSegments(Segments3dView.java:269)
	at de.embl.cba.tables.view.Segments3dView.updateView(Segments3dView.java:246)
	at de.embl.cba.tables.view.Segments3dView.showSelectedSegments(Segments3dView.java:483)
	at de.embl.cba.mobie.ui.SourcesDisplayManager.updateSegments3dView(SourcesDisplayManager.java:90)
	at de.embl.cba.mobie.ui.UserInterfaceComponentsProvider$2.lambda$actionPerformed$0(UserInterfaceComponentsProvider.java:329)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tischi** [comment]
No idea, maybe ask on the forum or here: https://gitter.im/fiji/fiji

**Comment by constantinpape** [comment]
I can't reproduce this now because I get the same error as in #410:
```
com.jogamp.opengl.GLException: Not a GL2 implementation
	at jogamp.opengl.es1.GLES1Impl.getGL2(GLES1Impl.java:4929)
	at org.scijava.java3d.JoglPipeline.createNewContext(JoglPipeline.java:6429)
	at org.scijava.java3d.Canvas3D.createNewContext(Canvas3D.java:4602)
	at org.scijava.java3d.Canvas3D.createNewContext(Canvas3D.java:2376)
	at org.scijava.java3d.Renderer.doWork(Renderer.java:881)
	at org.scijava.java3d.J3dThread.run(J3dThread.java:271)
J3dI18N: Error looking up: Renderer7
Exception occurred in RenderingErrorListener:
java.lang.RuntimeException
	at ij3d.ImageWindow3D$ErrorListener.errorOccurred(ImageWindow3D.java:351)
	at org.scijava.java3d.VirtualUniverse.notifyRenderingErrorListeners(VirtualUniverse.java:1198)
	at org.scijava.java3d.NotificationThread.processNotifications(NotificationThread.java:86)
	at org.scijava.java3d.NotificationThread.run(NotificationThread.java:104)
```
