### ISSUE TITLE
Opening platybrowser project with new spec

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#247]
I tried to open the platybrowser dataset from branch `spec-v2`:
https://github.com/mobie/platybrowser-datasets/tree/spec-v2

This throws:
```
SourceAndConverterBdvDisplayService:BdvHandle found.
https://raw.githubusercontent.com/mobie/platybrowser-datasets/spec-v2/data/0.0.0/null
java.io.FileNotFoundException: https://raw.githubusercontent.com/mobie/platybrowser-datasets/spec-v2/data/0.0.0/null
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at java.net.URL.openStream(URL.java:1045)
	at de.embl.cba.tables.FileAndUrlUtils.getInputStream(FileAndUrlUtils.java:160)
	at de.embl.cba.bdv.utils.BdvUtils.openSpimData(BdvUtils.java:1279)
	at de.embl.cba.mobie2.MoBIE2.getSourceAndConverter(MoBIE2.java:192)
	at de.embl.cba.mobie2.view.ViewerManager.lambda$showImageDisplay$1(ViewerManager.java:165)
	at de.embl.cba.mobie2.view.ImageSliceView.show(ImageSliceView.java:55)
	at de.embl.cba.mobie2.view.ImageSliceView.<init>(ImageSliceView.java:45)
	at de.embl.cba.mobie2.view.ViewerManager.showImageDisplay(ViewerManager.java:165)
	at de.embl.cba.mobie2.view.ViewerManager.showSourceDisplay(ViewerManager.java:122)
	at de.embl.cba.mobie2.view.ViewerManager.show(ViewerManager.java:103)
	at de.embl.cba.mobie2.MoBIE2.<init>(MoBIE2.java:72)
	at de.embl.cba.mobie2.command.OpenMoBIEProjectBranchCommand.run(OpenMoBIEProjectBranchCommand.java:27)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Module threw exception
java.lang.NullPointerException
	at bdv.spimdata.WrapBasicImgLoader.wrapImgLoaderIfNecessary(WrapBasicImgLoader.java:64)
	at sc.fiji.bdvpg.sourceandconverter.SourceAndConverterHelper.createSourceAndConverters(SourceAndConverterHelper.java:175)
	at de.embl.cba.mobie2.MoBIE2.getSourceAndConverter(MoBIE2.java:193)
	at de.embl.cba.mobie2.view.ViewerManager.lambda$showImageDisplay$1(ViewerManager.java:165)
	at de.embl.cba.mobie2.view.ImageSliceView.show(ImageSliceView.java:55)
	at de.embl.cba.mobie2.view.ImageSliceView.<init>(ImageSliceView.java:45)
	at de.embl.cba.mobie2.view.ViewerManager.showImageDisplay(ViewerManager.java:165)
	at de.embl.cba.mobie2.view.ViewerManager.showSourceDisplay(ViewerManager.java:122)
	at de.embl.cba.mobie2.view.ViewerManager.show(ViewerManager.java:103)
	at de.embl.cba.mobie2.MoBIE2.<init>(MoBIE2.java:72)
	at de.embl.cba.mobie2.command.OpenMoBIEProjectBranchCommand.run(OpenMoBIEProjectBranchCommand.java:27)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I guess the underlying issue is that MoBIE tries to open the file `https://raw.githubusercontent.com/mobie/platybrowser-datasets/spec-v2/data/0.0.0/null`, which does not exist.
This is weird for two reasons:
- It should load [this file](https://github.com/mobie/platybrowser-datasets/blob/spec-v2/data/0.0.0/dataset.json), which is there.
- It should not load dataset `0.0.0`, but rather `1.0.1`. Because this is the default dataset, see [here](https://github.com/mobie/platybrowser-datasets/blob/spec-v2/data/project.json#L27).

**Comment by constantinpape** [comment]
@tischi any idea what is the issue here? I think this would be an important thing to fix next in order to transition everything to the new spec.

**Comment by tischi** [comment]
Thanks for the ping!
In ALMF virtual retreat yesterday and today.
Will tackle it on Monday!

**Comment by tischi** [comment]
I fixed it.
