### ISSUE TITLE
Create MoBIE project or Open MoBIE Project broken...

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#250]
Hi,

I do:

- create New MoBIE project
- select directory
- add a dataset
- add an image to that dataset

then I try to open that project

- Open MoBIE project
- give directory address

```
java.io.FileNotFoundException: ﻿/Users/schorb/code/mobie-multiview/mobie/data/datasets.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at de.embl.cba.tables.FileAndUrlUtils.getInputStream(FileAndUrlUtils.java:134)
	at de.embl.cba.mobie.dataset.DatasetsParser.datasetsFromFile(DatasetsParser.java:41)
	at de.embl.cba.mobie.dataset.DatasetsParser.fetchProjectDatasets(DatasetsParser.java:23)
	at de.embl.cba.mobie.ui.MoBIE.appendSpecificDatasetLocations(MoBIE.java:157)
	at de.embl.cba.mobie.ui.MoBIE.<init>(MoBIE.java:69)
	at de.embl.cba.mobie.ui.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:24)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	...
[ERROR] Module threw exception
java.lang.UnsupportedOperationException: Could not open or parse datasets file: ﻿/Users/schorb/code/mobie-multiview/mobie/data/datasets.json
	at de.embl.cba.mobie.dataset.DatasetsParser.fetchProjectDatasets(DatasetsParser.java:34)
	at de.embl.cba.mobie.ui.MoBIE.appendSpecificDatasetLocations(MoBIE.java:157)
	at de.embl.cba.mobie.ui.MoBIE.<init>(MoBIE.java:69)
	at de.embl.cba.mobie.ui.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:24)
	...
```

despite:

```
$ ls /Users/schorb/code/mobie-multiview/mobie/data/
Mtest		datasets.json

$ cat data/datasets.json 
{
	"datasets": [
		"Mtest"
	],
	"defaultDataset": "Mtest"
}
```

**Comment by martinschorb** [comment]
This is on MoBIE1 release MacOS.

**Comment by constantinpape** [comment]
> {
> 	"datasets": [
> 		"Mtest"
> 	],
> 	"defaultDataset": "Mtest"

This looks like invalid json, because the closing `}` is missing.

**Comment by martinschorb** [comment]
ooops, I forgot to copy that line.

**Comment by martinschorb** [comment]
Cannot reproduce in fresh Fiji
