### ISSUE TITLE
Create MoBIE project move image fails

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#251]
Hi,

- create new MoBIE project
- select directory
- add dataset
- add image
- select "move image"

```
Exception in thread "Thread-7" java.lang.ClassCastException: de.embl.cba.mobie.n5.N5FSImageLoader cannot be cast to bdv.img.n5.N5ImageLoader
	at de.embl.cba.mobie.projects.ProjectsCreator.getImageLocation(ProjectsCreator.java:59)
	at de.embl.cba.mobie.projects.ProjectsCreator.moveImage(ProjectsCreator.java:108)
	at de.embl.cba.mobie.projects.ProjectsCreator.addBdvFormatImage(ProjectsCreator.java:146)
	at de.embl.cba.mobie.projects.ProjectsCreatorPanel.addBdvFormatImageDialog(ProjectsCreatorPanel.java:352)
	at de.embl.cba.mobie.projects.ProjectsCreatorPanel.addImageDialog(ProjectsCreatorPanel.java:140)
	at de.embl.cba.mobie.projects.ProjectsCreatorPanel.lambda$null$4(ProjectsCreatorPanel.java:95)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martinschorb** [comment]
"Copy Image" leads to the same error:

```
Exception in thread "Thread-9" java.lang.ClassCastException: de.embl.cba.mobie.n5.N5FSImageLoader cannot be cast to bdv.img.n5.N5ImageLoader
	at de.embl.cba.mobie.projects.ProjectsCreator.getImageLocation(ProjectsCreator.java:59)
	at de.embl.cba.mobie.projects.ProjectsCreator.copyImage(ProjectsCreator.java:86)
	at de.embl.cba.mobie.projects.ProjectsCreator.addBdvFormatImage(ProjectsCreator.java:144)
	at de.embl.cba.mobie.projects.ProjectsCreatorPanel.addBdvFormatImageDialog(ProjectsCreatorPanel.java:352)
	at de.embl.cba.mobie.projects.ProjectsCreatorPanel.addImageDialog(ProjectsCreatorPanel.java:140)
	at de.embl.cba.mobie.projects.ProjectsCreatorPanel.lambda$null$4(ProjectsCreatorPanel.java:95)
	at java.lang.Thread.run(Thread.java:748)
```

Just tested with a fresh Fiji (fully updated) and only MoBIE release installed

**Comment by K-Meech** [comment]
Thanks for finding this @martinschorb. I'll fix this when I update the project creator for MoBIE2.
Do you need this urgently? If so, I can create the project for you with my local setup

**Comment by martinschorb** [comment]
Thanks for the offer. I can get along manually.

**Comment by K-Meech** [comment]
This should be fixed on the latest version of mobie-beta. @martinschorb - does it work for you now?

**Comment by K-Meech** [comment]
This should be fixed now. Re-open if there are more issues.
