### ISSUE TITLE
Can't view prospr genes in Platybrowser dataset

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#263]
Adding the first prospr gene 'ache' gives the following error:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at net.imglib2.type.numeric.ARGBType.set(ARGBType.java:233)
	at sc.fiji.bdvpg.converter.RealARGBColorConverter.setColor(RealARGBColorConverter.java:87)
	at de.embl.cba.mobie2.color.opacity.AdjustableOpacityColorConverter.setColor(AdjustableOpacityColorConverter.java:75)
	at sc.fiji.bdvpg.sourceandconverter.display.ColorChanger.accept(ColorChanger.java:63)
	at sc.fiji.bdvpg.sourceandconverter.display.ColorChanger.run(ColorChanger.java:57)
	at de.embl.cba.mobie2.view.ImageSliceView.show(ImageSliceView.java:72)
	at de.embl.cba.mobie2.view.ImageSliceView.<init>(ImageSliceView.java:43)
	at de.embl.cba.mobie2.view.ViewerManager.showImageDisplay(ViewerManager.java:206)
	at de.embl.cba.mobie2.view.ViewerManager.showSourceDisplay(ViewerManager.java:135)
	at de.embl.cba.mobie2.view.ViewerManager.show(ViewerManager.java:113)
	at de.embl.cba.mobie2.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:425)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by tischi** [comment]
@constantinpape 
This is the culprit: https://github.com/mobie/platybrowser-datasets/blob/cf7a12998ce569bdaaaf0f717cd9509d108f3319/data/1.0.1/dataset.json#L15

**Comment by tischi** [comment]
Otherwise I think I fixed it.
I recommend lowering the opacity of the segmentations to 0.5 or even lower for the bookmarks.

**Comment by constantinpape** [comment]
Yes, I have added `randomFromGlasbey` to the spec to support the prospr use-case in platy.
Here, the idea is to select a random color, for each new prospr source, in order to have them displayed in a good way.

If you think that's to complicated for now we can also remove it from the spec again and I assign a fixed random color mapping.

**Comment by tischi** [comment]
I see, I just remembered that 😄 
I will support it! Leave it as is!
