### ISSUE TITLE
Issues with bookmarks in Platybrowser

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#264]
Many of the Platybrowser bookmarks don't display correctly. Some examples:

- 'Figure 1C: Adult eye' / 'Figure 1B: Epithelial cell': clicking 'view' gives no response

- 'Figure 5C: Gene clustering full body': shows the correct sources, but doesn't change the orientation of the view or colour by the correct column
- 'Figure 3B: Morphology clustering full body':  errors with:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at net.imglib2.type.numeric.ARGBType.set(ARGBType.java:233)
	at sc.fiji.bdvpg.converter.RealARGBColorConverter.setColor(RealARGBColorConverter.java:87)
	at de.embl.cba.mobie2.color.opacity.AdjustableOpacityColorConverter.setColor(AdjustableOpacityColorConverter.java:75)
	at sc.fiji.bdvpg.sourceandconverter.display.ColorChanger.accept(ColorChanger.java:63)
	at sc.fiji.bdvpg.sourceandconverter.display.ColorChanger.run(ColorChanger.java:57)
	at de.embl.cba.mobie2.view.ImageSliceView.show(ImageSliceView.java:72)
	at de.embl.cba.mobie2.view.ImageSliceView.<init>(ImageSliceView.java:43)
	at de.embl.cba.mobie2.view.ViewerManager.showImageDisplay(ViewerManager.java:206)
	at de.embl.cba.mobie2.view.ViewerManager.showSourceDisplay(ViewerManager.java:135)
	at de.embl.cba.mobie2.view.ViewerManager.show(ViewerManager.java:113)
	at de.embl.cba.mobie2.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:425)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by tischi** [comment]
I think I fixed most of it.
@constantinpape I would recommend lowering the opacity in the segmentations in the bookmarks to 0.5 or even lower.

**Comment by constantinpape** [comment]
> @constantinpape I would recommend lowering the opacity in the segmentations in the bookmarks to 0.5 or even lower.

The segmentations all have an opacity of 0.5 already.
@K-Meech @tischi let me know if you think there is a better value for all segmentations in the bookmarks, I can easily updated it now.

**Comment by tischi** [comment]
Oops, then it's my code not reading the opacity from the bookmarks 😉

**Comment by tischi** [comment]
I think for Fig 2B: Epithelial cells segmentation opacity 0.25 looks better than 0.5

**Comment by K-Meech** [comment]
There are still some issues with the platy bookmarks e.g.:

- Figure 5C
- Figure 3B
- Figure 3G and Suppl. Fig 3D 
don't display the segmentations with 'color by column'
