### ISSUE TITLE
Error opening remote dataset on branch

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#272]
In MoBIE 2 (latest playground branch), opening a remote dataset on a branch other than master fails.

e.g. Running 'OpenRemoteYeastCLEM' with the branch spec-v2 errors with:
```
Exception in thread "main" java.io.FileNotFoundException: https://raw.githubusercontent.com/mobie/yeast-clem-datasets/data/spec-v2/project.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at java.net.URL.openStream(URL.java:1067)
	at de.embl.cba.tables.FileAndUrlUtils.getInputStream(FileAndUrlUtils.java:160)
	at de.embl.cba.tables.FileAndUrlUtils.read(FileAndUrlUtils.java:174)
	at de.embl.cba.mobie2.serialize.ProjectJsonParser.parseProject(ProjectJsonParser.java:19)
	at de.embl.cba.mobie2.MoBIE2.<init>(MoBIE2.java:59)
	at projects.OpenRemoteYeastCLEM.main(OpenRemoteYeastCLEM.java:16)
```
@tischi  I think this might be related to the changes you made to deal with presence / absence of the 'data' folder. The url generated should be ```https://raw.githubusercontent.com/mobie/yeast-clem-datasets/spec-v2/data/project.json``` rather than ```https://raw.githubusercontent.com/mobie/yeast-clem-datasets/data/spec-v2/project.json```

**Comment by tischi** [comment]
Thanks! Should work now.

**Comment by tischi** [comment]
@K-Meech I pushed another commit trying to make this a bit clearer. Hope it helps...
Have fun! I am off now for one week 🌴 ⛰️

**Comment by K-Meech** [comment]
Perfect - thanks! Have a good holiday :)
