### ISSUE TITLE
Can't open spec-v2 projects with MoBIE beta

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#280]
Spec-v2 projects can't be opened with the current MoBIE beta, see the error message below.
This is probably the case because the version on MoBIE beta is not up to date with the latest spec changes, but it would be very helpful to update this soon to enable testing new projects.

```
SourceAndConverterBdvDisplayService:BdvHandle found.
/g/emcf/pape/plankton-sbem-project/data/emiliania/null
java.io.FileNotFoundException: /g/emcf/pape/plankton-sbem-project/data/emiliania/null (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at de.embl.cba.tables.FileAndUrlUtils.getInputStream(FileAndUrlUtils.java:162)
	at de.embl.cba.bdv.utils.BdvUtils.openSpimData(BdvUtils.java:1279)
	at de.embl.cba.mobie2.MoBIE2.openSourceAndConverter(MoBIE2.java:180)
	at de.embl.cba.mobie2.MoBIE2.lambda$openSourceAndConverters$0(MoBIE2.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-2-thread-1" Fetched 0 image source(s) in 31 ms, using 8 thread(s).java.lang.NullPointerException

	at bdv.spimdata.WrapBasicImgLoader.wrapImgLoaderIfNecessary(WrapBasicImgLoader.java:64)
	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.createSourceAndConverters(SourceAndConverterFromSpimDataCreator.java:51)
	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.<init>(SourceAndConverterFromSpimDataCreator.java:36)
	at de.embl.cba.mobie2.MoBIE2.openSourceAndConverter(MoBIE2.java:181)
	at de.embl.cba.mobie2.MoBIE2.lambda$openSourceAndConverters$0(MoBIE2.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Module threw exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at de.embl.cba.mobie2.ui.UserInterfaceHelper.createImageDisplaySettingsPanel(UserInterfaceHelper.java:272)
	at de.embl.cba.mobie2.ui.UserInterface.createDisplaySettingPanel(UserInterface.java:85)
	at de.embl.cba.mobie2.ui.UserInterface.addSourceDisplay(UserInterface.java:76)
	at de.embl.cba.mobie2.view.ViewerManager.showSourceDisplay(ViewerManager.java:157)
	at de.embl.cba.mobie2.view.ViewerManager.show(ViewerManager.java:117)
	at de.embl.cba.mobie2.MoBIE2.openDataset(MoBIE2.java:97)
	at de.embl.cba.mobie2.MoBIE2.<init>(MoBIE2.java:63)
	at de.embl.cba.mobie2.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:29)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
SourceAndConverterBdvDisplayService:BdvHandle found.
Overriding action Undo segment selections [ Ctrl Shift N ]
Overriding action Change random color seed
Fetched 1 image source(s) in 4110 ms, using 8 thread(s).
```

**Comment by tischi** [comment]
I can have a look at this now (cc @K-Meech).

**Comment by constantinpape** [comment]
> I can have a look at this now (cc @K-Meech).

I think we only need to release MoBIE beta with the latest changes from the playground branch to fix this.

**Comment by K-Meech** [comment]
I'm moving the last things around now. Then I'll make a PR for the whole playground branch :)

**Comment by tischi** [comment]
OK, @K-Meech, in this case could you please see whether you can open `/g/emcf/pape/plankton-sbem-project/data/emiliania` and, if yes, please just upload everything to MoBIE-beta?

**Comment by K-Meech** [comment]
Sure - will do!

**Comment by K-Meech** [comment]
@constantinpape I just updated MoBIE-beta with the new version - does it work for you now?

**Comment by constantinpape** [comment]
Thanks, works now!
