### ISSUE TITLE
Testing the new beta

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#284]
@tischi @constantinpape Are we ready for another round of testing? Or are there any incoming changes?

I can ping the main users, and post the mobie beta instructions/links to test projects.

**Comment by constantinpape** [comment]
It depends if we want to update all the spec-v2 projects to [the file format change](https://github.com/mobie/mobie.github.io/issues/49) beforehand.
I could update the projects today, but I don't know how much work this would be on the java side.

**Comment by K-Meech** [comment]
True - let's wait until this is done then. I'd also need to update the project creator to match this, but there shouldn't be any massive changes.

**Comment by K-Meech** [comment]
@tischi @constantinpape @vzinche @martinschorb @yanschwab
Hi everyone! 
A new version of MoBIE just went up on the MoBIE-beta update site. It would be great if you could test it, and give us some feedback. Please raise issues for any bugs you find: https://github.com/mobie/mobie-viewer-fiji/issues 

For anyone who hasn't used mobie-beta yet, the installation instructions are here: https://github.com/mobie/mobie-viewer-fiji/blob/master/MOBIE-BETA.md#mobie-beta Note that it is incompatible with the normal mobie update site, so you should use a separate Fiji!

Here are a few example projects to test:

Plugins > MoBIE > Open > Advanced > Open MoBIE Project Branch...

-project location: https://github.com/mobie/platybrowser-datasets
-project branch: spec-v2

-project location: https://github.com/mobie/zebrafish-lm-datasets
-project branch: spec-v2

-project location: https://github.com/mobie/arabidopsis-root-lm-datasets
-project branch: spec-v2

**Comment by constantinpape** [comment]
Thanks for making the release @K-Meech. Also pinging @HernandoMV.

Now would also be a good opportunity for those of you using the python project creator (@martinschorb @jhennies) to switch to the new spec version. This is currently in a PR https://github.com/mobie/mobie-utils-python/pull/21, but I will  merge it and make a new release there as soon as we update the MoBIE main update site.
The whole API has changed quite a bit, but should be much more consistent and easier to use now, see https://github.com/mobie/mobie-utils-python/blob/spec-v-02/examples/create_mobie_project.ipynb.

**Comment by martinschorb** [comment]
Hi,

are the editing tools ('Create new MoBIE project' etc.) functional in the Beta?
I have the problem that the dropdown in "add sources" is not active and stuck to "add current source", so I cannot add existing BDV data.

**Comment by martinschorb** [comment]
And I cannot open the spec 2 datasets we used for testing the crop functionality

`/g/emcf/pape/mobie-test-projects` 

which was working with the previous MoBIE-beta now gives (also when I try to set up another project with similar properties):

```
[ERROR] Module threw exception
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at de.embl.cba.mobie.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:46)
	at de.embl.cba.mobie.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:35)
	at de.embl.cba.mobie.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:13)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at de.embl.cba.mobie.serialize.DatasetJsonParser.parseDataset(DatasetJsonParser.java:26)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:163)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:102)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:71)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:32)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0]
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginArray(JsonTreeReader.java:72)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 31 more
[ERROR] Module threw exception
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at de.embl.cba.mobie.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:46)
	at de.embl.cba.mobie.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:35)
	at de.embl.cba.mobie.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:13)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at de.embl.cba.mobie.serialize.DatasetJsonParser.parseDataset(DatasetJsonParser.java:26)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:163)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:102)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:71)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:32)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0]
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginArray(JsonTreeReader.java:72)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 31 more
[ERROR] Module threw exception
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at de.embl.cba.mobie.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:46)
	at de.embl.cba.mobie.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:35)
	at de.embl.cba.mobie.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:13)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at de.embl.cba.mobie.serialize.DatasetJsonParser.parseDataset(DatasetJsonParser.java:26)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:163)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:102)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:71)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:32)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0]
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginArray(JsonTreeReader.java:72)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 31 more
[ERROR] Module threw exception
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at de.embl.cba.mobie.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:46)
	at de.embl.cba.mobie.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:35)
	at de.embl.cba.mobie.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:13)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at de.embl.cba.mobie.serialize.DatasetJsonParser.parseDataset(DatasetJsonParser.java:26)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:163)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:102)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:71)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:32)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0]
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginArray(JsonTreeReader.java:72)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 31 more
```

**Comment by K-Meech** [comment]
> are the editing tools ('Create new MoBIE project' etc.) functional in the Beta?
> I have the problem that the dropdown in "add sources" is not active and stuck to "add current source", so I cannot add existing BDV data.

@martinschorb Yes - all the editing tools should be functional in the beta.
I just checked with a fresh fiji, and this is not an issue for me (at least on Windows):

![Screenshot (285)](https://user-images.githubusercontent.com/24316371/122564322-1e9b2a80-d03d-11eb-8021-090624e59715.png)

Are you definitely on the latest version of mobie-beta? Any other update sites enabled?

**Comment by martinschorb** [comment]
OK,

- Mac
- fresh Fiji
- all updates
- add Mobie-beta
- Create new MoBIE project
- add dataset
- add source, no response in the dropdown to mouse actions. Using keyboard arrows to select works. Also the dropdowns in the main `Editing MoBIE Project` Window work with the mouse.

**Comment by martinschorb** [comment]
I don't know if this has something to do with the change/update in the Java GUI. The UI elements look different now. But that's probably a more general ImageJ issue...

**Comment by martinschorb** [comment]
Ok, it seems that `Create new MoBIE dataset` forgets to create the "dataset" subfolder.

```
java.io.FileNotFoundException: /Users/schorb/code/mobie-multiview/test0001/data/project.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
```

while the project JSON is:

```
/Users/schorb/code/mobie-multiview/test0001/Testcrop1/data/project.json
```

**Comment by martinschorb** [comment]
when I manually move the project data to the parent directory, MoBIE crashes when loading the image:
```
SourceAndConverterBdvDisplayService:BdvHandle found.
Overriding action Change random coloring seed [ Ctrl L ]
Fetched 0 image source(s) in 747 ms, using 8 thread(s).
Exception in thread "pool-2-thread-1" java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/schorb/code/mobie-multiview/test0001/data/t1/images/bdv-n5/../../../../../.././_KM140520_Grid3_c154.n5/setup0/attributes.json
	at bdv.img.n5.N5ImageLoader.open(N5ImageLoader.java:157)
	at bdv.img.n5.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:189)
	at bdv.img.n5.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:98)
	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.createSourceAndConverters(SourceAndConverterFromSpimDataCreator.java:94)
	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.<init>(SourceAndConverterFromSpimDataCreator.java:64)
	at de.embl.cba.mobie.MoBIE.openSourceAndConverter(MoBIE.java:252)
	at de.embl.cba.mobie.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:145)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /Users/schorb/code/mobie-multiview/test0001/data/t1/images/bdv-n5/../../../../../.././_KM140520_Grid3_c154.n5/setup0/attributes.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at org.janelia.saalfeldlab.n5.N5FSReader$LockedFileChannel.<init>(N5FSReader.java:69)
	at org.janelia.saalfeldlab.n5.N5FSReader$LockedFileChannel.openForReading(N5FSReader.java:58)
	at org.janelia.saalfeldlab.n5.N5FSReader.getAttributes(N5FSReader.java:161)
	at org.janelia.saalfeldlab.n5.AbstractGsonReader.getAttribute(AbstractGsonReader.java:128)
	at bdv.img.n5.N5ImageLoader.createSetupImgLoader(N5ImageLoader.java:196)
	at bdv.img.n5.N5ImageLoader.open(N5ImageLoader.java:145)
	... 9 more
[ERROR] Module threw exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at de.embl.cba.mobie.ui.UserInterfaceHelper.createImageDisplaySettingsPanel(UserInterfaceHelper.java:285)
	at de.embl.cba.mobie.ui.UserInterface.createDisplaySettingPanel(UserInterface.java:102)
	at de.embl.cba.mobie.ui.UserInterface.addSourceDisplay(UserInterface.java:93)
	at de.embl.cba.mobie.view.ViewerManager.showSourceDisplay(ViewerManager.java:208)
	at de.embl.cba.mobie.view.ViewerManager.show(ViewerManager.java:167)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:169)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:102)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:71)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:32)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by constantinpape** [comment]
> And I cannot open the spec 2 datasets we used for testing the crop functionality
> 
> `/g/emcf/pape/mobie-test-projects`

@martinschorb yes, the spec has changed quite a bit since we generated these (that's why it's still in beta).

I have updated the example project now, so it should work again.

**Comment by vzinche** [comment]
Is there any reason why 'label_id' column is not the first one anymore? I've always felt it is the most commonly used one

**Comment by constantinpape** [comment]
> Is there any reason why 'label_id' column is not the first one anymore? I've always felt it is the most commonly used one

What do you mean by this, can you post a screenshot?
Also, can you make separate issues for the problems encountered? If we discuss everything in this single issue things will get chaotic.

**Comment by vzinche** [comment]
Sorry, I am just not sure it's an issue

**Comment by constantinpape** [comment]
Just open an issue ;). We can still close it if it''s not relevant.

**Comment by martinschorb** [comment]
I will continue here (at least with this thing)...

the problem with the test project still persists.
