### ISSUE TITLE
Problems with example project with crop

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#313]
@tischi we have an example project with a crop transformation here:
`/g/emcf/pape/mobie-test-projects`. This project is valid according to the jsonschema, but it cannot be opened with the current MoBIE beta, see error message below.
Note that this project has a crop transform and uses the "sourceNamesAfterTransform" field, so maybe there is the issue. 
```
[ERROR] Module threw exception
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at de.embl.cba.mobie.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:46)
	at de.embl.cba.mobie.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:35)
	at de.embl.cba.mobie.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:13)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at de.embl.cba.mobie.serialize.DatasetJsonParser.parseDataset(DatasetJsonParser.java:26)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:163)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:102)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:71)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:32)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0]
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginArray(JsonTreeReader.java:72)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 31 more
```
(@martinschorb I moved this discussion from #284 here so that we can keep track of all the different issues with the current beta separately.)

**Comment by martinschorb** [comment]
FYI: This used to work with the previous MoBIE-Beta, see https://github.com/mobie/mobie.github.io/issues/44

**Comment by martinschorb** [comment]
I found that it is not related to the crop but rather the transform in the JSON.

```JSON
{
	"is2D": false,
	"timepoints": 1,
	"sources": {
		"_KM140520_Grid3_c154": {
			"image": {
				"imageData": {
					"bdv.n5": {
						"relativePath": "images/bdv-n5/_KM140520_Grid3_c154.xml"
					}
				}
			}
		}
	},
	"views": {
		"default": {
			"uiSelectionGroup": "bookmark",
			"sourceDisplays": [
				{
					"imageDisplay": {
						"color": "white",
						"contrastLimits": [
							-1270.0,
							127.0
						],
						"showImagesIn3d": false,
						"name": "_KM140520_Grid3_c154",
						"opacity": 1.0,
						"sources": [
							"_KM140520_Grid3_c154"
						]
					}
				}
			],
			"isExclusive": true
		},
		"_KM140520_Grid3_c154": {
			"uiSelectionGroup": "tomo1",
			"sourceDisplays": [
				{
					"imageDisplay": {
						"color": "white",
						"contrastLimits": [
							-127.0,
							127.0
						],
						"showImagesIn3d": false,
						"name": "_KM140520_Grid3_c154",
						"opacity": 1.0,
						"sources": [
							"_KM140520_Grid3_c154"
						]
					}
				}
			],
			"isExclusive": false
		}
	}
}
```
works nicely,
while

```JSON
{
	"is2D": false,
	"timepoints": 1,
	"sources": {
		"_KM140520_Grid3_c154": {
			"image": {
				"imageData": {
					"bdv.n5": {
						"relativePath": "images/bdv-n5/_KM140520_Grid3_c154.xml"
					}
				}
			}
		}
	},
	"views": {
		"default": {
			"uiSelectionGroup": "bookmark",
			"sourceDisplays": [
				{
					"imageDisplay": {
						"color": "white",
						"contrastLimits": [
							-1270.0,
							127.0
						],
						"showImagesIn3d": false,
						"name": "_KM140520_Grid3_c154",
						"opacity": 1.0,
						"sources": [
							"_KM140520_Grid3_c154"
						]
					}
				}
			],
			"isExclusive": true
		},
		"_KM140520_Grid3_c154": {
			"uiSelectionGroup": "tomo1",
			"sourceDisplays": [
				{
					"imageDisplay": {
						"color": "white",
						"contrastLimits": [
							-127.0,
							127.0
						],
						"showImagesIn3d": false,
						"name": "_KM140520_Grid3_c154",
						"opacity": 1.0,
						"sources": [
							"_KM140520_Grid3_c154"
						]
					}
				}
			],
			"sourceTransforms": [
        {
          "affine": {
            "parameters": [
              0.0,
              -1.0,
              0.0,
              0.0,
              1.0,
              0.0,
              0.0,
              0.0,
              0.0,
              0.0,
              1.0,
              0.0
            ],
            "sources": [
              "_KM140520_Grid3_c154"
            ]
          }
        }
			],
			"isExclusive": false
		}
	}
}
```

fails.

**Comment by martinschorb** [comment]
Do you spot what could be wrong?

**Comment by martinschorb** [comment]
no `sourceNamesAfterTransform` in the problematic JSON

**Comment by constantinpape** [comment]
I don't know exactly what the issue here is, but just to summarize: the test project at `/g/emcf/pape/mobie-test-projects` is well formed according to my python validator (which checks the json schema and also has some dynamic checks that make sure that the data referenced in the json metadata actually exists). However it fails to open in MoBIE (see error above).
So there are two possible reasons for this issue: 1.) something in MoBIE-Fiji is not working as expected 2.) the validator does not find an issue with the project. I think 1.) is more likely, but in any case the only way to figure out what's going wrong is to go through this in debug mode with breakpoints in intellij.
It would be great if you have some time to do this  @tischi or @K-Meech; I don't have a MoBIE dev env set-up on the EMBL share and don't have time to set it up this week.

**Comment by K-Meech** [comment]
I'll take a quick look, and see what the issue is

**Comment by K-Meech** [comment]
Ok - I think this is a mismatch between how ```sources``` are specified in transforms.

At the moment, all source transformers (affine, grid etc...) extend this class: https://github.com/mobie/mobie-viewer-fiji/blob/e3770674c598ffce4429008df3713e3c16575937/src/main/java/de/embl/cba/mobie/transform/AbstractSourceTransformer.java#L11 which has a sources field as a list of lists (```List< List<String> >```)

This is true for the grid source transform, but not for the rest, where it should instead be a ```List<String>```

@tischi Could you look into this?

**Comment by tischi** [comment]
I'll look into it...
But `sourceNamesAfterTransform` we support for all transforms, do we?

**Comment by tischi** [comment]
...and I guess for the GridTransform it should be `List< List< String > > sourceNamesAfterTransform`, right?

**Comment by constantinpape** [comment]
> But `sourceNamesAfterTransform` we support for all transforms, do we?

Yes.

> ...and I guess for the GridTransform it should be `List< List< String > > sourceNamesAfterTransform`, right?

Exactly. Although this is wrong in the jsonschema right now, I will fix it.

**Comment by martinschorb** [comment]
Will this fix be available on the Beta channel soon?

**Comment by tischi** [comment]
@K-Meech Could you please upload the latest changes once you fell it makes sense?

**Comment by K-Meech** [comment]
@martinschorb @tischi The latest changes are now on MoBIE-beta
