### ISSUE TITLE
Loading tables takes longer in new version? 

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#326]
I don't have any quantitative data here, but I feel like loading custom tables is taking at least twice longer now. 
For example, loading [a table like this](https://drive.google.com/file/d/1wLVG83D93X9zjB2yMDHkH6B4cIsKVX7b/view?usp=sharing) now takes 5 minutes, and I feel like it was much faster before.

**Comment by tischi** [comment]
Loading from GitHub? (the link is to a G-Drive)

**Comment by vzinche** [comment]
Sorry, loading from FileSystem

**Comment by tischi** [comment]
It could be in fact as I had to change some code there.
Can you provide me with a table such that I could test this?

**Comment by vzinche** [comment]
You can just use the one I shared on G-drive? It's pretty big, so it's easy to notice any difference in loading speed

**Comment by tischi** [comment]
Good point. yes!

**Comment by tischi** [comment]
@vzinche Just to be sure: you are adding these columns to the default table, is it? Because loading this as a primary table is very fast for me (less than 1 second). This makes me suspect that the part of the code that merges this table into the primary table is the culprit.

Could you maybe let me know what exactly you are doing?

**Comment by vzinche** [comment]
Oh, sorry, I forgot the other option even exists :)
I am appending this table to the default one with Table -> Load columns -> Load from FileSystem

**Comment by tischi** [comment]
I found one issue. Now it takes 40 seconds. Is that acceptable?

I think this can be further improved, e.g. I would like to find out whether I can make the UI stay interactive while it is adding the columns.

**Comment by vzinche** [comment]
> I found one issue. Now it takes 40 seconds. Is that acceptable?

I think that's approximately the time it took before, so that would be good!

> I think this can be further improved, e.g. I would like to find out whether I can make the UI stay interactive while it is adding the columns.

That would be even better of course, but waiting these 40 seconds is also manageable

**Comment by tischi** [comment]
I now stays in interactive and adds the columns one by one but it throws an error when one tries to sort the table while it is not done yet.

**Comment by vzinche** [comment]
Will this error be more like a warning, or one of these errors that require you to restart Fiji because nothing works afterwards? :)

**Comment by tischi** [comment]
It keeps working. I leave the issue open to see whether I can fix this at some point.

Maybe one could disable table sorting while it is loading...

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
	at java.util.Arrays.sort(Arrays.java:1246)
	at javax.swing.DefaultRowSorter.sort(DefaultRowSorter.java:607)
	at javax.swing.DefaultRowSorter.setSortKeys(DefaultRowSorter.java:319)
	at javax.swing.DefaultRowSorter.toggleSortOrder(DefaultRowSorter.java:480)
	at javax.swing.plaf.basic.BasicTableHeaderUI$MouseInputHandler.mouseClicked(BasicTableHeaderUI.java:112)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vzinche** [comment]
What do you think of just disabling the whole table while loading? It also gives a clearer sign when the loading is finished

**Comment by tischi** [comment]
> What do you think of just disabling the whole table while loading?

Yes, and in fact I just managed to implement the code for this 🥳
