### ISSUE TITLE
Open MoBIE project Expert mode issues in spec-v2

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#389]
Hi,

Is the expert mode already fully supported in spec-v2?

I try to open a local project with image data from S3 and end up with:

```
[ERROR] Module threw exception
java.lang.IllegalArgumentException: No enum constant de.embl.cba.mobie.source.ImageDataFormat.S3
	at java.lang.Enum.valueOf(Enum.java:238)
	at de.embl.cba.mobie.source.ImageDataFormat.valueOf(ImageDataFormat.java:5)
	at de.embl.cba.mobie.command.OpenMoBIEProjectAdvancedCommand.run(OpenMoBIEProjectAdvancedCommand.java:43)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Note that this is a new project, so it could well be that there is an issue with the data format as well.

**Comment by martinschorb** [comment]
What Do I need to put for "image location" there? Is it the S3 path? I just tried with the covid-tomo-datasets and run into the same error.

**Comment by constantinpape** [comment]
This probably doesn't work with the new MoBIE version yet, but we def. want to support this for test purposes.
cc @tischi

**Comment by tischi** [comment]
I guess that will fix it?
https://github.com/mobie/mobie-viewer-fiji/commit/038428c8ff14172b2c6fbff51017651d5b5bf80e

**Comment by tischi** [comment]
@martinschorb can we close this?

**Comment by martinschorb** [comment]
Looks like it works now.
