### ISSUE TITLE
Volume viewer not working

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#410]
On the current MoBIE-beta the volume viewer is not working for me. When I try to show a segmented object in it it fails with:
```
com.jogamp.opengl.GLException: Not a GL2 implementation
	at jogamp.opengl.es1.GLES1Impl.getGL2(GLES1Impl.java:4929)
	at org.scijava.java3d.JoglPipeline.createNewContext(JoglPipeline.java:6429)
	at org.scijava.java3d.Canvas3D.createNewContext(Canvas3D.java:4602)
	at org.scijava.java3d.Canvas3D.createNewContext(Canvas3D.java:2376)
	at org.scijava.java3d.Renderer.doWork(Renderer.java:881)
	at org.scijava.java3d.J3dThread.run(J3dThread.java:271)
J3dI18N: Error looking up: Renderer7
Exception occurred in RenderingErrorListener:
java.lang.RuntimeException
	at ij3d.ImageWindow3D$ErrorListener.errorOccurred(ImageWindow3D.java:351)
	at org.scijava.java3d.VirtualUniverse.notifyRenderingErrorListeners(VirtualUniverse.java:1198)
	at org.scijava.java3d.NotificationThread.processNotifications(NotificationThread.java:86)
	at org.scijava.java3d.NotificationThread.run(NotificationThread.java:104)

```

**Comment by tischi** [comment]
close this?

**Comment by constantinpape** [comment]
Yes, this issue is specific to my laptop and we can close it.
