### ISSUE TITLE
ReadOnlyCachedCellImgFactory expects only positive dimension

### ISSUE THREAD

**Issue by KateMoreva** [mobie/mobie-viewer-fiji#417]
Got an exception while trying to open  `kreshuk/pape/Work/mobie/covid-if-project/data`

```
Exception in thread "main" net.imglib2.exception.InvalidDimensionsException: Expected only positive dimensions but got: [3684, 3348, 0]
	at net.imglib2.Dimensions.verifyAllPositive(Dimensions.java:166)
	at net.imglib2.Dimensions.verify(Dimensions.java:208)
	at net.imglib2.cache.img.ReadOnlyCachedCellImgFactory.createCellGrid(ReadOnlyCachedCellImgFactory.java:156)
	at net.imglib2.cache.img.ReadOnlyCachedCellImgFactory.createInternal(ReadOnlyCachedCellImgFactory.java:130)
	at net.imglib2.cache.img.ReadOnlyCachedCellImgFactory.create(ReadOnlyCachedCellImgFactory.java:88)
	at de.embl.cba.mobie.transform.MergedGridSource.createMergedRandomAccessibleIntervals(MergedGridSource.java:83)
	at de.embl.cba.mobie.transform.MergedGridSource.<init>(MergedGridSource.java:52)
	at de.embl.cba.mobie.transform.GridSourceTransformer.createMergedSourceAndConverter(GridSourceTransformer.java:110)
	at de.embl.cba.mobie.transform.GridSourceTransformer.transform(GridSourceTransformer.java:34)
	at de.embl.cba.mobie.view.ViewManager.show(ViewManager.java:216)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:226)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:160)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:96)
	at projects.OpenLocalOmeZarr.main(OpenLocalOmeZarr.java:14)
```

**Comment by constantinpape** [comment]
@KateMoreva could you explain how exactly you encounter this and how to reproduce this bug?
Is this something we (probably @tischi who would know best what might be going on) should have a look at or are you looking into it yourself?

**Comment by KateMoreva** [comment]
> @KateMoreva could you explain how exactly you encounter this and how to reproduce this bug?
> Is this something we (probably @tischi who would know best what might be going on) should have a look at or are you looking into it yourself?

I was tying to open  with MoBIE (current master and  on fork brunch) : `  new MoBIE( "/home/katerina/Documents/embl/mnt2/kreshuk/pape/Work/mobie/covid-if-project/data", MoBIESettings.settings().imageDataFormat( ImageDataFormat.OmeZarr ) );`

**Comment by constantinpape** [comment]
@tischi can you double check this? This should work, maybe something went wrong in the latest mobie main.

**Comment by tischi** [comment]
I think with the latest master this should work now. For me works:

```
new MoBIE("/g/kreshuk/pape/Work/mobie/covid-if-project/data", MoBIESettings.settings().imageDataFormat( ImageDataFormat.OmeZarr ));
```

**Comment by constantinpape** [comment]
@KateMoreva did you have a chance already to check if this works for you now?
Feel free to close this issue if it does work.

**Comment by KateMoreva** [comment]
It finally works, thanks @tischi, @constantinpape!
