### ISSUE TITLE
Opening projects from s3 fails in latest MoBIE beta

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#423]
With the latest MoBIE beta opening data from s3 fails. Opening local data works as expected, but I tried opening several projects from s3 and they all fail:
the MoBIE GUI opens, but no data is loaded in the viewer and there is a long exception thrown (see stacktrace below).
To reproduce:
- "MoBIE->Open->Advanced->OpenMoBIEProjectBranch..."
- `Project Location` https://github.com/mobie/platybrowser-datasets
- `Project Branch` spec-v2

```
Exception in thread "PainterThread" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:78)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:230)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:222)
	at bdv.viewer.render.VisibilityUtils.computeVisibleSourcesOnScreen(VisibilityUtils.java:97)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:428)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:473)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:145)
	at net.imglib2.cache.ref.BoundedSoftRefLoaderCache.get(BoundedSoftRefLoaderCache.java:87)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:74)
	... 6 more
Caused by: java.lang.NullPointerException
	at de.embl.cba.n5.util.loaders.SetupImgLoader.prepareCachedImage(SetupImgLoader.java:106)
	at de.embl.cba.n5.util.loaders.SetupImgLoader.getImage(SetupImgLoader.java:57)
	at bdv.SpimSource.getImage(SpimSource.java:59)
	at bdv.AbstractSpimSource.lambda$new$0(AbstractSpimSource.java:163)
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:135)
	... 9 more
[ERROR] Module threw exception
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:78)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:230)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:222)
	at sc.fiji.bdvpg.bdv.navigate.ViewerTransformAdjuster.getTransform(ViewerTransformAdjuster.java:96)
	at sc.fiji.bdvpg.bdv.navigate.ViewerTransformAdjuster.run(ViewerTransformAdjuster.java:64)
	at de.embl.cba.mobie.view.ViewManager.adjustViewerTransform(ViewManager.java:245)
	at de.embl.cba.mobie.view.ViewManager.show(ViewManager.java:230)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:226)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:160)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:96)
	at de.embl.cba.mobie.command.OpenMoBIEProjectBranchCommand.run(OpenMoBIEProjectBranchCommand.java:25)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:145)
	at net.imglib2.cache.ref.BoundedSoftRefLoaderCache.get(BoundedSoftRefLoaderCache.java:87)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:74)
	... 19 more
Caused by: java.lang.NullPointerException
	at de.embl.cba.n5.util.loaders.SetupImgLoader.prepareCachedImage(SetupImgLoader.java:106)
	at de.embl.cba.n5.util.loaders.SetupImgLoader.getImage(SetupImgLoader.java:57)
	at bdv.SpimSource.getImage(SpimSource.java:59)
	at bdv.AbstractSpimSource.lambda$new$0(AbstractSpimSource.java:163)
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:135)
	... 22 more
```

**Comment by tischi** [comment]
I could not figure it out. Maybe somethings wrong with the S3? I will ping EMBL IT.

**Comment by tischi** [comment]
I had a look and we can open the data from MoBIE(-alpha). Thus it is not an issue with the S3.
@KateMoreva would you have time to look into this? It feels like as if the issue might be within bdv-imgloader, but I am not sure.

To reproduce the error:

- go to the develop branch of mobie-viewer-fiji
- in the tests run: OpenRemotePlatynereis

```
                final ImageJ imageJ = new ImageJ();
		imageJ.ui().showUI();

		try {
			new MoBIE("https://github.com/platybrowser/platybrowser",
					MoBIESettings.settings().gitProjectBranch("spec-v2").imageDataFormat( ImageDataFormat.BdvN5S3 ) );
		} catch (IOException e) {
			e.printStackTrace();
		}
```

**Comment by KateMoreva** [comment]
It seems that the loading of Source (`this.source.getSpimSource().getSource(timepoint, 0);` _timepiont = 0_) produce `NullPointerException`. 

![Screenshot from 2021-09-06 11-07-46](https://user-images.githubusercontent.com/48569608/132183061-1bca7732-ac23-47ac-9f47-3eb497f18776.png)

**Comment by tischi** [comment]
Yes, I also got that far. But I could not figure out why. The data should be there, as I could open the same source using the official MoBIE release.

**Comment by KateMoreva** [comment]
On which commit does MoBIE(-alpha) is based?

**Comment by tischi** [comment]
I would have to dig into it, but I feel it would probably be enough to first go back to a commit where we did not yet use  bdv-imgloader. Could you find such a commit and try there?

**Comment by KateMoreva** [comment]
So far I can open it from the commit `Merge branch 'master' of github.com:mobie/mobie-viewer-fiji into master ` `af608333` `Christian Tischer <christian.tischer@embl.de> on 09.08.2021 at 16:41`.

**Comment by tischi** [comment]
@KateMoreva OK. That's great! Do you think you can try to debug what's going on? I assume something with the BdvN5S3 ImageLoader might be the culprit?

**Comment by KateMoreva** [comment]
> @KateMoreva OK. That's great! Do you think you can try to debug what's going on? I assume something with the BdvN5S3 ImageLoader might be the culprit?

I can debug it a bit later today.

**Comment by tischi** [comment]
Thanks! I would recommend to first try to open the corresponding SpimData (default image called "raw" of the platybrowser) just in bdv-imgloader and do a `BdvFunctions.show` on it. If that works than the issue most be within the fiji-viewer repo.

**Comment by KateMoreva** [comment]
Seems like I messed something up in bigdataviewer-imageloader as the error appears with the version change from 1.0.1 to 1.0.2-SNAPSHOT.

**Comment by tischi** [comment]
OK! Should we wait for you to figure it out? I could also ship MoBIE beta with 1.0.1, but for @constantinpape to properly use the grid view, I need this commit: https://github.com/mobie/bigdataviewer-imageloader/commit/df9aeac48639cd92da2754b46b3f295c465e05d1

**Comment by constantinpape** [comment]
I don't mind waiting a day or 2, if we can solve it in a clean fashion.

**Comment by KateMoreva** [comment]
> OK! Should we wait for you to figure it out? I could also ship MoBIE beta with 1.0.1, but for @constantinpape to properly use the grid view, I need this commit: [mobie/bigdataviewer-imageloader@df9aeac](https://github.com/mobie/bigdataviewer-imageloader/commit/df9aeac48639cd92da2754b46b3f295c465e05d1)

Found the problem. 
I will make a fix in `bigdataviewer-imageloader master`.

**Comment by constantinpape** [comment]
> Found the problem.
> I will make a fix in `bigdataviewer-imageloader master`.

Awesome! Let us know when this is there so that we can make a new MoBIE beta release.

**Comment by KateMoreva** [comment]
> > Found the problem.
> > I will make a fix in `bigdataviewer-imageloader master`.
> 
> Awesome! Let us know when this is there so that we can make a new MoBIE beta release.

@constantinpape, please try this brunch https://github.com/mobie/mobie-viewer-fiji/pull/425 it should be working.

**Comment by constantinpape** [comment]
Thanks, @KateMoreva. I am very busy today and don't have time to test this. @tischi if you have time today, could you give it a try and release MoBIE beta if everything works? Otherwise I have time to look into this tomorrow.

**Comment by tischi** [comment]
I am already on it...

**Comment by KateMoreva** [comment]
> I am already on it...

Please make sure that you have the last version of `bigdataviewer-imageloader`.

**Comment by tischi** [comment]
Works!
Thanks for the fix!

**Comment by tischi** [comment]
@constantinpape I uploaded to Fiji, hope everything works now!

**Comment by constantinpape** [comment]
Yes, it works now, thanks!
