### ISSUE TITLE
deploy to Fiji

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#449]
@K-Meech when I do  `mvn clean install "-Dscijava.app.directory=/Users/tischer/Desktop/Fiji/Fiji-MoBIE-beta.app"` on the current develop branch and then try to open the platybrowser in my Fiji I am getting below error. Is this the same for you? 

The develop branch from within IntelliJ works without any issues.

```
(Fiji Is Just) ImageJ 2.2.0/1.53d; Java 1.8.0_202 [64-bit]; Mac OS X 10.14.6; 98MB of 8857MB (1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.IllegalArgumentException: types and labels must be unique
	at sc.fiji.persist.RuntimeTypeAdapterFactory.registerSubtype(RuntimeTypeAdapterFactory.java:212)
	at sc.fiji.persist.RuntimeTypeAdapterFactory.registerSubtype(RuntimeTypeAdapterFactory.java:227)
	at sc.fiji.persist.ScijavaGsonHelper$ClassTypesAndSubTypes.lambda$getRunTimeAdapterFactory$0(ScijavaGsonHelper.java:159)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at sc.fiji.persist.ScijavaGsonHelper$ClassTypesAndSubTypes.getRunTimeAdapterFactory(ScijavaGsonHelper.java:157)
	at sc.fiji.persist.ScijavaGsonHelper.lambda$getGsonBuilder$1(ScijavaGsonHelper.java:110)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at sc.fiji.persist.ScijavaGsonHelper.getGsonBuilder(ScijavaGsonHelper.java:110)
	at sc.fiji.persist.ScijavaGsonHelper.getGson(ScijavaGsonHelper.java:62)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.setDefaultBdvSupplier(SourceAndConverterBdvDisplayService.java:129)
```

**Comment by K-Meech** [comment]
It works for me in intellij and inside Fiji. Although, I did have to manually delete the old 'mobie' jar. The issue is that we've renamed it to match the repo 'mobie-viewer-fiji', so now the old and the new can co-exist... Could be causing issues?

**Comment by tischi** [comment]
>  The issue is that we've renamed it to match the repo 'mobie-viewer-fiji', so now the old and the new can co-exist... Could be causing issues?

That's it! Thanks!!!
