### ISSUE TITLE
beta: grid properties dialog crash

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#453]
Hi,

when closing the grid properties dialog and then upon every further call of it, I get:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at de.embl.cba.tables.Utils.parseDouble(Utils.java:114)
	at de.embl.cba.tables.plot.TableRowKDTreeSupplier.initialiseDataPoints(TableRowKDTreeSupplier.java:117)
	at de.embl.cba.tables.plot.TableRowKDTreeSupplier.<init>(TableRowKDTreeSupplier.java:67)
	at org.embl.mobie.viewer.plot.ScatterPlotViewer.updateScatterPlotSource(ScatterPlotViewer.java:161)
	at org.embl.mobie.viewer.plot.ScatterPlotViewer.show(ScatterPlotViewer.java:133)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$11(UserInterfaceHelper.java:653)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by tischi** [comment]
> the grid properties dialog 

@KateMoreva is this about your new interactive grid dialog?

**Comment by KateMoreva** [comment]
> > the grid properties dialog
> 
> @KateMoreva is this about your new interactive grid dialog?

No, the implementation is still unmerged.

**Comment by martinschorb** [comment]
It's the `|_| P` checkbox to the very right of the grid item.

**Comment by tischi** [comment]
Could you post a screenshot? Normally the `[ ] P` checkbox is for creating a scatter plot of the data shown in the table. If that's what's crashing then it is my fault 😄

**Comment by martinschorb** [comment]
<img width="1039" alt="Screenshot 2021-09-21 at 09 31 36" src="https://user-images.githubusercontent.com/35071867/134130036-dc2c6565-7c11-4d78-a491-b78b3283811b.png">

and when closing that dialog it crashes.

**Comment by tischi** [comment]
OK, then that's a bug on my end. Could you let me know which view I need to open from which project to reproduce this?

**Comment by martinschorb** [comment]
Our favourite centrioles branch `grid-test2` - any of the grids.
