### ISSUE TITLE
Interpretation of nullpointer exception EMBL s3 migration)

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#480]
The EMBL IT is migrating the s3 storage and I tried out loading the platybrowser from the new storage (https://github.com/mobie/platybrowser-datasets, branch: `new-s3`).  Loading the project works, but adding the cell segmentation (`sbem-segmentation -> cells -> view`) fails with the exception below.
The same steps work with the old s3 storage (branch: `spec-v2`), so it looks like there is some issue with the data on the new storage.

I tried to check this manually but could not find anything wrong with the file structure of the segmentation n5 file on the new storage.
I can't make much sense of the NullPointerException, @tischi is there any chance we can throw a more meaningful error message to help pinpoint the problem here?

```
java.lang.NullPointerException
	at de.embl.cba.n5.util.loaders.N5ImageLoader.createSetupImgLoader(N5ImageLoader.java:164)
	at de.embl.cba.n5.util.loaders.N5ImageLoader.open(N5ImageLoader.java:112)
	at de.embl.cba.n5.util.loaders.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:156)
	at de.embl.cba.n5.util.loaders.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:73)
	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.createSourceAndConverters(SourceAndConverterFromSpimDataCreator.java:91)
	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.<init>(SourceAndConverterFromSpimDataCreator.java:61)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:302)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-31" java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.view.SegmentationSliceView.asLabelSources(SegmentationSliceView.java:86)
	at org.embl.mobie.viewer.bdv.view.SegmentationSliceView.show(SegmentationSliceView.java:55)
	at org.embl.mobie.viewer.bdv.view.SegmentationSliceView.<init>(SegmentationSliceView.java:41)
	at org.embl.mobie.viewer.view.ViewManager.showInSliceViewer(ViewManager.java:449)
	at org.embl.mobie.viewer.view.ViewManager.showSegmentationDisplay(ViewManager.java:405)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:314)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:265)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:460)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tischi** [comment]
@constantinpape 
For me, at home, it does not open at all (also now the raw).
Do I maybe have to be in intranet to test this?

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: s4.embl.de
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1416)
	at de.embl.cba.tables.S3Utils.getS3Client(S3Utils.java:67)
	at de.embl.cba.n5.util.loaders.N5S3ImageLoader$N5AmazonS3ReaderCreator.create(N5S3ImageLoader.java:72)
	at de.embl.cba.n5.util.loaders.N5S3ImageLoader.<init>(N5S3ImageLoader.java:46)
	at de.embl.cba.n5.util.loaders.xml.XmlIoN5S3ImageLoader.fromXml(XmlIoN5S3ImageLoader.java:82)
	at de.embl.cba.n5.util.loaders.xml.XmlIoN5S3ImageLoader.fromXml(XmlIoN5S3ImageLoader.java:44)
	at mpicbg.spim.data.generic.sequence.XmlIoAbstractSequenceDescription.fromXml(XmlIoAbstractSequenceDescription.java:111)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.fromXml(XmlIoAbstractSpimData.java:153)
	at de.embl.cba.bdv.utils.CustomXmlIoSpimData.loadFromStream(CustomXmlIoSpimData.java:71)
	at de.embl.cba.bdv.utils.BdvUtils.openSpimData(BdvUtils.java:1280)
	at org.embl.mobie.viewer.source.SpimDataOpener.openSpimData(SpimDataOpener.java:64)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:299)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: s4.embl.de
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy13.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1330)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	... 25 more
Exception in thread "main" java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.adaptConverter(ImageSliceView.java:92)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.show(ImageSliceView.java:62)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.<init>(ImageSliceView.java:47)
	at org.embl.mobie.viewer.view.ViewManager.showImageDisplay(ViewManager.java:345)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:312)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:267)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:215)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:149)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:85)
	at projects.OpenRemotePlatynereisBranch.main(OpenRemotePlatynereisBranch.java:15)
```
