### ISSUE TITLE
Selecting segment in image doesn't work

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#499]
Selecting a segment from the image via "Ctrl + Left Click" doesn't work in the current MoBIE-beta:
```
Exception in thread "Thread-50" java.lang.ClassCastException: de.embl.cba.tables.imagesegment.DefaultImageSegment cannot be cast to de.embl.cba.tables.tablerow.TableRowImageSegment
	at org.embl.mobie.viewer.segment.BdvSegmentSelector.toggleSelectionAtMousePosition(BdvSegmentSelector.java:58)
	at org.embl.mobie.viewer.segment.BdvSegmentSelector.run(BdvSegmentSelector.java:82)
	at org.embl.mobie.viewer.bdv.view.SliceViewer.lambda$null$5(SliceViewer.java:119)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by constantinpape** [comment]
Fixed
