### ISSUE TITLE
3d viewer does not work

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#501]
3d viewer does not work in the current mobie-beta; when pressing `V` the following error appears:
```
com.jogamp.opengl.GLException: Not a GL2 implementation
	at jogamp.opengl.es1.GLES1Impl.getGL2(GLES1Impl.java:4929)
	at org.scijava.java3d.JoglPipeline.createNewContext(JoglPipeline.java:6429)
	at org.scijava.java3d.Canvas3D.createNewContext(Canvas3D.java:4602)
	at org.scijava.java3d.Canvas3D.createNewContext(Canvas3D.java:2376)
	at org.scijava.java3d.Renderer.doWork(Renderer.java:881)
	at org.scijava.java3d.J3dThread.run(J3dThread.java:271)
J3dI18N: Error looking up: Renderer7
Exception occurred in RenderingErrorListener:
java.lang.RuntimeException
	at ij3d.ImageWindow3D$ErrorListener.errorOccurred(ImageWindow3D.java:351)
	at org.scijava.java3d.VirtualUniverse.notifyRenderingErrorListeners(VirtualUniverse.java:1198)
	at org.scijava.java3d.NotificationThread.processNotifications(NotificationThread.java:86)
	at org.scijava.java3d.NotificationThread.run(NotificationThread.java:104)
```

**Comment by tischi** [comment]
@constantinpape 

I cannot reproduce this...for example in the platybrowser the bookmark `Figure 2B: Epithelial cell segmentation` works for me. Does this work for you?

What do you mean by "pressing `V`"?

**Comment by constantinpape** [comment]
> I cannot reproduce this...for example in the platybrowser the bookmark `Figure 2B: Epithelial cell segmentation` works for me. Does this work for you?

This doesn't work for me and throws the same error as above.
I am on Linux; I will try on another Linux machine in a second to see if this is a general problem or if it's just something on my notebook.

> What do you mean by "pressing `V`"?

I mean clicking on the `V` checkbox for activating the 3d viewer.

**Comment by tischi** [comment]
I just found that what I have in IntelliJ is very different from what I am deploying to Fiji. I don't understand why yet, but am working on it...

**Comment by constantinpape** [comment]
I tried on a Linux VM now and there I see a different error when trying to open `Figure 2B`:
```
Exception in thread "Thread-21" java.lang.UnsupportedOperationException: An image segment from cells did not have a corresponding image source.
	at org.embl.mobie.viewer.volume.SegmentsVolumeViewer.getSource(SegmentsVolumeViewer.java:226)
	at org.embl.mobie.viewer.volume.SegmentsVolumeViewer.updateSelectedSegments(SegmentsVolumeViewer.java:203)
	at org.embl.mobie.viewer.volume.SegmentsVolumeViewer.lambda$updateView$0(SegmentsVolumeViewer.java:172)
	at java.lang.Thread.run(Thread.java:748)
```

> I just found that what I have in IntelliJ is very different from what I am deploying to Fiji. I don't understand why yet, but am working on it...

Ok, sounds like a good idea to fix this in any case.

**Comment by constantinpape** [comment]
It works on the linux VM now.
(My laptop still fails, but this looks like an issue with my openGL so we  can ignore that for now.)
