### ISSUE TITLE
Loading a transformedGrid does not work on current MoBIE beta

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#510]
Loading a dataset that contains a `transformedGrid` fails with:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.RuntimeException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0][1]
	at org.embl.mobie.viewer.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:53)
	at org.embl.mobie.viewer.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:38)
	at org.embl.mobie.viewer.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:14)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at org.embl.mobie.viewer.serialize.DatasetJsonParser.parseDataset(DatasetJsonParser.java:24)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:220)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:160)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:96)
	at org.embl.mobie.viewer.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:25)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0][1]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.embl.mobie.viewer.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:48)
	... 27 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.sources[0][1]
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginArray(JsonTreeReader.java:72)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:174)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 31 more
```

To reproduce: open https://github.com/mobie/zebrafish-lm-project. Note that I merged the new spec onto the main branch already and made sure that the json is up to date with the latest spec.

**Comment by tischi** [comment]
Thanks! I will work on this this today!

This worked for me in IntelliJ yesterday:

```
			new MoBIE("https://github.com/mobie/covid-tomo-datasets",
					MoBIESettings.settings().gitProjectBranch( "new-spec" ).imageDataFormat( ImageDataFormat.BdvN5S3 ) );
```

Are we using the same syntax there in the JSON?

**Comment by constantinpape** [comment]
> ```
> 			new MoBIE("https://github.com/mobie/covid-tomo-datasets",
> 					MoBIESettings.settings().gitProjectBranch( "new-spec" ).imageDataFormat( ImageDataFormat.BdvN5S3 ) );
> ```
> 
> 
>     
>   
> 
> Are we using the same syntax there in the JSON?

No, I think this is not updated to the latest spec syntax yet.

**Comment by tischi** [comment]
OK, it works for me locally. Thus the issue probably simply is that I pushed the wrong branch to MoBIE-beta. I will upload later and let you know.

**Comment by martinschorb** [comment]
Hi,

I guess this is the same problem...?

- newest Beta
- open `centrioles-tomo-datasets`, `main` branch
- open the first `crop` source


```
Exception in thread "Thread-18" java.lang.NoSuchMethodError: bdv.tools.transformation.TransformedSource.<init>(Lbdv/viewer/Source;Ljava/lang/String;)V
	at org.embl.mobie.viewer.playground.SourceAffineTransformer.getTransformedSource(SourceAffineTransformer.java:119)
	at org.embl.mobie.viewer.playground.SourceAffineTransformer.apply(SourceAffineTransformer.java:99)
	at org.embl.mobie.viewer.transform.AffineSourceTransformer.transform(AffineSourceTransformer.java:32)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:217)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:456)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martinschorb** [comment]
or do I need to update that repo to the new spec as well first?

**Comment by constantinpape** [comment]
@martinschorb yes, that is probably a related problem; and we will need to update the repository to the new spec. Let's wait till @tischi has updated MoBIE-beta first.

**Comment by tischi** [comment]
@martinschorb @constantinpape I updated MoBIE-beta. Please check which of the issues still persist.

@K-Meech I am currently populating MoBIE-beta with this https://github.com/mobie/mobie-viewer-fiji/pull/507 
It would be great if you could check it an merge it into develop...

**Comment by constantinpape** [comment]
This works now and the grid features also seem to all work as expected

**Comment by constantinpape** [comment]
@martinschorb I will create a separae issue about updating the centrioles tomo project.
