### ISSUE TITLE
Loading a mergedGrid does not work in current MoBIE-beta

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#511]
Loading a dataset that contains a mergedGrid fails with:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.RuntimeException: Unknown class: mergedGrid
	at org.embl.mobie.viewer.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:45)
	at org.embl.mobie.viewer.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:38)
	at org.embl.mobie.viewer.serialize.SourceTransformerListAdapter.deserialize(SourceTransformerListAdapter.java:14)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at org.embl.mobie.viewer.serialize.DatasetJsonParser.parseDataset(DatasetJsonParser.java:24)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:220)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:160)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:96)
	at org.embl.mobie.viewer.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:25)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
```

To reproduce: open the project at /g/kreshuk/pape/Work/mobie/covid-if-project (data is not uploaded to s3 yet)

**Comment by KateMoreva** [comment]
It is because at some point some sources started to contain `grid` instead of `mergedGrid` in metadata.
The current version is using a `grid.`

**Comment by constantinpape** [comment]
> It is because at some point some sources started to contain `grid` instead of `mergedGrid` in metadata.
> The current version is using a `grid.`

@tischi and me decided a while ago that the two grids should be called `mergedGrid` and `transformedGrid`. Maybe this has not been updated properly here yet?

**Comment by KateMoreva** [comment]
I'll fix it in the code now, but some sources will not work.

**Comment by constantinpape** [comment]
@KateMoreva please wait before you change too much; maybe @tischi is working on this already.

**Comment by KateMoreva** [comment]
> I'll fix it in the code now, but some sources will not work.
@constantinpape
Done.
Please try it with the current `develop.`

**Comment by constantinpape** [comment]
> I'll fix it in the code now, but some sources will not work.
> @constantinpape
> Done.
> Please try it with the current `develop.`

Thanks. I will wait till this is deployed to MoBIE-beta though in order to properly test if this works in Fiji.

**Comment by constantinpape** [comment]
@tischi this issue is still there on MoBIE-beta

**Comment by tischi** [comment]
and now?

**Comment by constantinpape** [comment]
Now there's a different error:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.embl.mobie.viewer.MoBIE.getSource(MoBIE.java:289)
	at org.embl.mobie.viewer.MoBIE.loadImageSegmentsTable(MoBIE.java:366)
	at org.embl.mobie.viewer.MoBIE.loadPrimarySegmentsTables(MoBIE.java:414)
	at org.embl.mobie.viewer.MoBIE.loadPrimarySegmentsTables(MoBIE.java:487)
	at org.embl.mobie.viewer.view.ViewManager.loadTablesAndCreateImageSegments(ViewManager.java:452)
	at org.embl.mobie.viewer.view.ViewManager.showSegmentationDisplay(ViewManager.java:407)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:338)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:289)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:215)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:149)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:85)
	at org.embl.mobie.viewer.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:25)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
```

**Comment by tischi** [comment]
At some point it tries to load but then cannot find this source: `plate_cell_segmentation`
Does that help to understand what's going on?
Maybe some issue with sources that change their name?

**Comment by constantinpape** [comment]
> At some point it tries to load but then cannot find this source: `plate_cell_segmentation`
> Does that help to understand what's going on?
> Maybe some issue with sources that change their name?

Ok, this might be an issue in the json then. I will have a look at this on Sunday or Monday.

**Comment by tischi** [comment]
OK, Thanks!
I had a look at the code an in principle it should also work for transformed sources with name changes.
Maybe the JSON is referring to a source that does not exist...

**Comment by constantinpape** [comment]
> Maybe the JSON is referring to a source that does not exist...

I will check and let you know.

**Comment by constantinpape** [comment]
@tischi I have checked this out now and I am pretty sure that the json is correct, but I think I know what's going wrong in the viewer:
- the source `plate_cell_segmentation` is added through `mergedGridSourceName` here: https://gist.github.com/constantinpape/814327089f1a75ef31d366295138dd82#file-view-json-L477 (I copied the view to a gist because the dataset.json is too large to be rendered by github)
-  It's then used here: https://gist.github.com/constantinpape/814327089f1a75ef31d366295138dd82#file-view-json-L57

So I think that you forget to add the new sources resulting from `mergedGridSourceName` to the list of available sources in the viewer. Let me know if you need more information to fix this, or when I can try this again.

**Comment by tischi** [comment]
I am confused....

It tries to find the `plate_cell_segmentation` in the `sources` field of this data structure:

```
public class Dataset
{
	public boolean is2D = false;
	public int timepoints = 1;
	public Map< String, SourceSupplier> sources;
	public Map< String, View> views;
}
```

There it cannot find it, because the `plate_cell_segmentation` is only created on the fly in one of the views.

Note that the `public Map< String, SourceSupplier> sources` is populated directly from the dataset.json. This is different from the map `private Map< String, SourceAndConverter< ? > > sourceNameToSourceAndConverter` that we populate for each `View` while actually loading and transforming the sources.

In the dataset.sources we have the notion of a `SegmentationSource`, e.g.

```
"cell_segmentation_WellE10_0000": {
      "segmentation": {
        "imageData": {
          "ome.zarr": {
            "relativePath": "images/ome-zarr/cell_segmentation_WellE10_0000.ome.zarr"
          }
        },
        "tableData": {
          "tsv": {
            "relativePath": "tables/cell_segmentation_WellB06_0003"
          }
        }
      }
    },
```

...while in `mobie.sourceNameToSourceAndConverter` I think we do not have a logic of a source being a segmentation source with an associated table but we handle this via the `segmentationDisplay`, which can look like this:

```
"segmentationDisplay": {
            "lut": "glasbey",
            "name": "cell_segmentation",
            "opacity": 0.5,
            "showTable": false,
            "sources": [
              "plate_cell_segmentation"
            ],
            "tables": [
              "default.tsv"
            ],
            "visible": false
          }
```

...thus I am confused now as it seems we have two different ways of specifying that a source is a segmentation source and also what the name of the table is.

In fact, maybe this is OK, but for the `plate_cell_segmentation` we might in fact be missing information like this: 

```
"tableData": {
          "tsv": {
            "relativePath": "tables/plate_cell_segmentation"
          }
```

Maybe we have not thought of this use-case where a derived segmentation source is created? And thus we do not have a way to fully specify where the table data lives?

**Comment by constantinpape** [comment]
@tischi in this case, `plate_cell_segmentation` merges some other segmentations into one source. The other segmentations have tables, which should be merged into a single one. Note that the same happens when multiple segmentations are listed in a `transformedGrid`, e.g. [here](https://github.com/mobie/zebrafish-lm-project/blob/main/data/actin/dataset.json#L2331-L2342). This case works as expected already:
![Screenshot from 2021-11-08 11-13-19](https://user-images.githubusercontent.com/4263537/140724276-cb3e3939-efb5-44eb-85a9-5dd1173a6e36.png)

**Comment by tischi** [comment]
Yes, but [here](https://github.com/mobie/zebrafish-lm-project/blob/eed520982568ab36c73127d0440660dc00ae9ef1/data/actin/dataset.json#L2331-L2342) the individual segmentation sources **exist in dataset.json**.

whereas here they don't:

```
        "segmentationDisplay": {
          "lut": "glasbey",
          "name": "cell_segmentation",
          "opacity": 0.5,
          "showTable": false,
          "sources": [
            "plate_cell_segmentation"
          ],
          "tables": [
            "default.tsv"
          ],
          "visible": false
        }
      },
```

because `plate_cell_segmentation` is not a "SegmentationSource" in the sense that it is specified like this in dataset.json

**Comment by constantinpape** [comment]
The individual segmentations (https://gist.github.com/constantinpape/814327089f1a75ef31d366295138dd82#file-view-json-L489-L490) **do** exist in the dataset.json.

**Comment by tischi** [comment]
This is the code:
```
public void loadPrimarySegmentsTables( SegmentationSourceDisplay segmentationDisplay )
	{
		segmentationDisplay.tableRows = new ArrayList<>();
		final ArrayList< List< TableRowImageSegment > > primaryTables = loadPrimarySegmentsTables( segmentationDisplay, segmentationDisplay.getTables().get( 0 ) );

		for ( List< TableRowImageSegment > primaryTable : primaryTables )
		{
			segmentationDisplay.tableRows.addAll( primaryTable );
		}
	}
```

and

```
private ArrayList< List< TableRowImageSegment > > loadPrimarySegmentsTables(SegmentationSourceDisplay segmentationDisplay, String table )
	{
		final ArrayList< List< TableRowImageSegment > > primaryTables = new ArrayList<>();

		// TODO: make parallel
		for ( String sourceName : segmentationDisplay.getSources() )
		{
			final List< TableRowImageSegment > primaryTable = loadImageSegmentsTable( sourceName, table );
			primaryTables.add( primaryTable );
		}

		return primaryTables;
	}
```

The issue now is that `loadImageSegmentsTable( sourceName, table );` does not work for `plate_cell_segmentation` because it cannot find the table...

**Comment by tischi** [comment]
I think what I need to do is amend this code:

```
        private ArrayList< List< TableRowImageSegment > > loadPrimarySegmentsTables(SegmentationSourceDisplay segmentationDisplay, String table )
	{
		final ArrayList< List< TableRowImageSegment > > primaryTables = new ArrayList<>();

		// TODO: make parallel
		for ( String sourceName : segmentationDisplay.getSources() )
		{
                        // TODO: make also work for derived sources
                        //    i.e. find the derived source(s) and their tables
			final List< TableRowImageSegment > primaryTable = loadImageSegmentsTable( sourceName, table );
			primaryTables.add( primaryTable );
		}

		return primaryTables;
	}
```

**Comment by tischi** [comment]
...see the 2nd TODO in above code.

What do you think?

**Comment by constantinpape** [comment]
> ...see the 2nd TODO in above code.
> 
> What do you think?

Yes, I think that's exactly what needs to be done. More concretely, I think there are 2 cases that currently wouldn't work:
- If we have a new segmentationSource that results from a `mergedGrid`; then you somehow need to merge all the tables of the sources in the grid (as in this example)
- If we have a segmentation that changes its name due to `sourceNameAfterTransform` in the current view.

**Comment by constantinpape** [comment]
@tischi I have created two example views as we have discussed now, see https://github.com/mobie/zebrafish-lm-project/issues/10 for details.

**Comment by tischi** [comment]
I updated MoBIE-beta. Does it work now?

**Comment by constantinpape** [comment]
Yes it works now! I still need to test everything properly once I am at EMBL (my internet here is a bit too slow for that...)
But looking good so far and I will make new issues if something else there comes up.
