### ISSUE TITLE
Crop sources fail to open incurrent beta

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#512]
Hi,

This is still happening:
-  newest Beta
-  open centrioles-tomo-datasets, main branch
-  open the first crop source

```
Exception in thread "Thread-18" java.lang.NoSuchMethodError: bdv.tools.transformation.TransformedSource.<init>(Lbdv/viewer/Source;Ljava/lang/String;)V
	at org.embl.mobie.viewer.playground.SourceAffineTransformer.getTransformedSource(SourceAffineTransformer.java:119)
	at org.embl.mobie.viewer.playground.SourceAffineTransformer.apply(SourceAffineTransformer.java:99)
	at org.embl.mobie.viewer.transform.AffineSourceTransformer.transform(AffineSourceTransformer.java:32)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:217)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:456)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tischi** [comment]
@martinschorb could you please try again? and check that you have bigdataviewer-core-10.2.1?

**Comment by martinschorb** [comment]
now it got shipped  with the most recent update...

and it works!
I just have the feeling that the performance is rather poor at the moment. But it feels a bit like the S3 is slow. Takes forever to load a source...

**Comment by tischi** [comment]
> I just have the feeling that the performance is rather poor at the moment. But it feels a bit like the S3 is slow. Takes forever to load a source...

Not sure, I also changed some of the multi-threading to make it more stable. 
We could still tweak some stuff there...
