### ISSUE TITLE
Beta: opening new project fails

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#514]
Hi,

I just created a new project using @K-Meech 's creator and it fails to load the sources:

```
/g/emcf/santarel/projects/ries_jervis_alphasynuclein_filaments/Jervis_F30_210308/mobie/
```

```
Exception in thread "pool-5-thread-1" Fetched 0 image source(s) in 77 ms, using 3 thread(s).java.lang.NullPointerException

	at org.embl.mobie.io.n5.loaders.N5ImageLoader.getSequenceDescription(N5ImageLoader.java:173)
	at org.embl.mobie.io.n5.openers.N5Opener.readFile(N5Opener.java:30)
	at org.embl.mobie.io.n5.openers.N5Opener.openFile(N5Opener.java:22)
	at org.embl.mobie.viewer.source.SpimDataOpener.openBDV(SpimDataOpener.java:92)
	at org.embl.mobie.viewer.source.SpimDataOpener.openSpimData(SpimDataOpener.java:65)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:298)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-14" java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.adaptConverter(ImageSliceView.java:92)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.show(ImageSliceView.java:62)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.<init>(ImageSliceView.java:47)
	at org.embl.mobie.viewer.view.ViewManager.showImageDisplay(ViewManager.java:367)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:334)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:289)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:456)
	at java.lang.Thread.run(Thread.java:748)
```

confirmed with current beta on Windows and Mac.

**Comment by constantinpape** [comment]
I think this is the exact same issue as #513

**Comment by martinschorb** [comment]
agree, let's use the original...
