### ISSUE TITLE
Loading platybrowser from disc does not work

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#526]
Loading the platybrowser data () from disc does not work

```
java.nio.file.NoSuchFileException: /g/arendt/EM_6dpf_segmentation/platy-browser-data/data/1.0.1/images/local/sbem-6dpf-1-whole-raw.n5/attributes.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at org.janelia.saalfeldlab.n5.N5FSReader$LockedFileChannel.<init>(N5FSReader.java:69)
	at org.janelia.saalfeldlab.n5.N5FSReader$LockedFileChannel.openForReading(N5FSReader.java:58)
	at org.janelia.saalfeldlab.n5.N5FSReader.getAttributes(N5FSReader.java:161)
	at org.janelia.saalfeldlab.n5.AbstractGsonReader.getAttribute(AbstractGsonReader.java:128)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.getMultiscale(N5ImageLoader.java:338)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.initSetups(N5ImageLoader.java:350)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.fetchSequenceDescriptionAndViewRegistrations(N5ImageLoader.java:396)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.<init>(N5ImageLoader.java:120)
	at org.embl.mobie.io.n5.loaders.N5FSImageLoader.<init>(N5FSImageLoader.java:53)
	at org.embl.mobie.io.n5.openers.N5Opener.readFile(N5Opener.java:24)
	at org.embl.mobie.io.n5.openers.N5Opener.openFile(N5Opener.java:20)
	at org.embl.mobie.viewer.source.SpimDataOpener.openBDV(SpimDataOpener.java:92)
	at org.embl.mobie.viewer.source.SpimDataOpener.openSpimData(SpimDataOpener.java:65)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:289)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:184)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Note that the error indicates that it tries to load the file from `/g/arendt/EM_6dpf_segmentation/platy-browser-data/data/1.0.1/images/local/sbem-6dpf-1-whole-raw.n5`. However, that is not where the raw data is located, see the xml: https://github.com/mobie/platybrowser-project/blob/spec-v2/data/1.0.1/images/local/sbem-6dpf-1-whole-raw.xml#L5.

@tischi @KateMoreva are you maybe not passing the xml correctly and just assuming that the n5 is in the same place?

**Comment by KateMoreva** [comment]
Oh, yes, I was testing on the projects where the paths were the same. I am really sorry for this mistake. 
@constantinpape 
Please try to test this functionality with **mobie-viewer-fiji 2.0.5**

**Comment by constantinpape** [comment]
Also working now, thanks @KateMoreva
