### ISSUE TITLE
Scrolling across time does not work in data-set loaded from disc

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#527]
Scrolling across time fails in a dataset loaded from disc (tested with `/g/kreshuk/pape/Work/mobie/arabidopsis-root-lm-datasets`):
```
Exception in thread "PainterThread" java.lang.NullPointerException
	at bdv.AbstractSpimSource.loadTimepoint(AbstractSpimSource.java:194)
	at bdv.AbstractSpimSource.getSourceTransform(AbstractSpimSource.java:253)
	at bdv.tools.transformation.TransformedSource.getSourceTransform(TransformedSource.java:239)
	at bdv.util.MipmapTransforms.getPixelSourceSize(MipmapTransforms.java:131)
	at bdv.util.MipmapTransforms.getBestMipMapLevel(MipmapTransforms.java:171)
	at bdv.viewer.render.VisibilityUtils.computeVisibleSourcesOnScreen(VisibilityUtils.java:93)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:428)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:473)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
```
Scrolling across time works without issue when loading the same dataset from github / s3 (https://github.com/mobie/arabidopsis-root-lm-project).

**Comment by KateMoreva** [comment]
@constantinpape
Please try to test this functionality with **mobie-viewer-fiji 2.0.5**

**Comment by constantinpape** [comment]
@tischi can you make a new release so I can test with MoBIE-beta?

**Comment by tischi** [comment]
done

**Comment by constantinpape** [comment]
It's working now, thanks for the quick fix, @KateMoreva!
