### ISSUE TITLE
Multi-threading bug

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#558]
```
https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/well/default.tsv
14:37:50.025 [main] DEBUG sc.fiji.bdvpg.sourceandconverter.SourceAndConverterHelper - Unsupported ConverterSetup for Converters of class class org.embl.mobie.viewer.color.ListItemsARGBConverter
Exception in thread "pool-19-thread-1" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-19-thread-2" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-19-thread-3" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

To reproduce:

```
new MoBIE("https://github.com/mobie/covid-if-project",
					MoBIESettings.settings().gitProjectBranch( "main" ).imageDataFormat( ImageDataFormat.OmeZarrS3 ).view( "full_grid" ) );
```

**Comment by tischi** [comment]
It's the Fetcher threads...why?...I thought I fixed this...

**Comment by tischi** [comment]
@KateMoreva The issue is that we do not yet have the sharedQueue for `OmeZarrS3`:

```
public SpimData openSpimData(String imagePath, ImageDataFormat imageDataFormat, SharedQueue sharedQueue ) {
        SpimData spimData = null;
        switch ( imageDataFormat ) {
            case BdvN5:
                spimData = openBDV( imagePath, sharedQueue );
                break;
            case BdvN5S3:
                spimData = openBDVS3( imagePath, sharedQueue );
                break;
            case OmeZarr:
                spimData = openOmeZarrData( imagePath, sharedQueue );
                break;
            case OmeZarrS3:
                spimData = openOmeZarrS3Data( imagePath ); // <-- HERE
                break;
            case BdvOmeZarrS3:
                spimData = openBdvOmeZarrS3Data( imagePath ); // <-- HERE
                break;
            case BdvOmeZarr:
                spimData = openBdvZarrData( imagePath );
                break;
            case OpenOrganelleS3:
                spimData = openOpenOrganelleData( imagePath );
        }

        return spimData;
    }
```

Is that something that could be added? I would be super important, in fact 😃 !

**Comment by KateMoreva** [comment]
> @KateMoreva The issue is that we do not yet have the sharedQueue for `OmeZarrS3`:
> 
> ```
> public SpimData openSpimData(String imagePath, ImageDataFormat imageDataFormat, SharedQueue sharedQueue ) {
>         SpimData spimData = null;
>         switch ( imageDataFormat ) {
>             case BdvN5:
>                 spimData = openBDV( imagePath, sharedQueue );
>                 break;
>             case BdvN5S3:
>                 spimData = openBDVS3( imagePath, sharedQueue );
>                 break;
>             case OmeZarr:
>                 spimData = openOmeZarrData( imagePath, sharedQueue );
>                 break;
>             case OmeZarrS3:
>                 spimData = openOmeZarrS3Data( imagePath ); // <-- HERE
>                 break;
>             case BdvOmeZarrS3:
>                 spimData = openBdvOmeZarrS3Data( imagePath ); // <-- HERE
>                 break;
>             case BdvOmeZarr:
>                 spimData = openBdvZarrData( imagePath );
>                 break;
>             case OpenOrganelleS3:
>                 spimData = openOpenOrganelleData( imagePath );
>         }
> 
>         return spimData;
>     }
> ```
> 
> Is that something that could be added? I would be super important, in fact smiley !

Yes sure, I'll implement this.
I am deeply sorry for my long reply (pre-exam time, got a bit busy with all that staff).

**Comment by tischi** [comment]
> Yes sure, I'll implement this.
I am deeply sorry for my long reply (pre-exam time, got a bit busy with all that staff).

No need to be sorry! It is very clear to us that you have other priorities! We are super happy to have you at all in the team!

**Comment by constantinpape** [comment]
> I am deeply sorry for my long reply (pre-exam time, got a bit busy with all that staff).

Yes, all good! Just let us know when you have time to work on it or have any questions ;).

**Comment by constantinpape** [comment]
I think this is implemented now (OmeZarrS3 with shared queue in mobie-io). Correct, @KateMoreva?

**Comment by tischi** [comment]
Yes it is implemented now.
