### ISSUE TITLE
How do I find out where the problem is...(BDV-N5-S3)

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#567]
Hi,

I have some trouble loading a new dataset (https://github.com/mobie/pag-dapex2-fibsem).

the metadata pointing to the bucket looks good. When I check the contents of the s3, it lso seems OK.
(something like https://s3.embl.de/pag-dapex2-fibsem/Sample_3/images/local/Sample3_image.n5/setup0/timepoint0/s0/1/1/1 or https://s3.embl.de/pag-dapex2-fibsem/Sample_3/images/local/Sample3_image.n5/setup0/timepoint0/attributes.json works...)

Still I get:

```
java.lang.NullPointerException
	at com.amazonaws.services.s3.internal.ServiceUtils.isS3AccelerateEndpoint(ServiceUtils.java:500)
	at com.amazonaws.services.s3.AmazonS3Client.setEndpoint(AmazonS3Client.java:725)
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:453)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at de.embl.cba.tables.S3Utils.getS3Client(S3Utils.java:62)
	at org.embl.mobie.io.n5.loaders.N5S3ImageLoader$N5AmazonS3ReaderCreator.create(N5S3ImageLoader.java:81)
	at org.embl.mobie.io.n5.loaders.N5S3ImageLoader.<init>(N5S3ImageLoader.java:55)
```

Does this mean that the data on S3 is somehow corrupt? How can I find out what exactly is the problem?

**Comment by constantinpape** [comment]
For me https://s3.embl.de/pag-dapex2-fibsem/Sample_3/images/local/Sample3_image.n5/setup0/timepoint0/attributes.json  does not work. It says `The specified key does not exist` under `<Error>/<Message>`. (This might be an issue due to missing permissions, but I think that in that case the error message should be different.)
To help more I would need access to the `pag-dapex2-fibsem` bucket, I can't see it right now.

**Comment by martinschorb** [comment]
Thanks for having a look.

I went through a series of checks with MoBIE and clearly found that the data in the S3 was indeed the problem.
I will now first try to re-upload the data from Rome to that bucket (that's why I emptied it to not run into duplicates) and if it then still fails, we need to check the N5 structure.

**Comment by martinschorb** [comment]
OK,

we re-uploaded the data and it still gives the exact same error.

**Comment by martinschorb** [comment]
OK, so manually moving the N5 into the local folder that contains the project (in new MoBIE format) and then trying to open it yields:
```
NoSuchFileException: ...: <project>/data/Sample_3/images/bdv-n5/Sample_3_image.n5/setup0/attributes.json
...
```

However that file exists!

It contains (generated with Fiji/the "old" MoBIE project creator):
```
{"downsamplingFactors":[[1,1,1],[2,2,2],[4,4,4],[8,8,8],[16,16,16]],"dataType":"uint8"}
```

**Comment by martinschorb** [comment]
Forget about that one...

Typo in the XML file!

**Comment by martinschorb** [comment]
Still, even with the fixed XML.

```
java.lang.NullPointerException
	at com.amazonaws.services.s3.internal.ServiceUtils.isS3AccelerateEndpoint(ServiceUtils.java:500)
	at com.amazonaws.services.s3.AmazonS3Client.setEndpoint(AmazonS3Client.java:725)
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:453)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at de.embl.cba.tables.S3Utils.getS3Client(S3Utils.java:62)
```

**Comment by constantinpape** [comment]
I am pretty sure that this is due to an incorrect file path. To help you more I would need to have read access to the s3 bucket.

**Comment by martinschorb** [comment]
it should be world-readable

**Comment by martinschorb** [comment]
OK, I see. World-readable does not give you browse access in the console. I filed a request with ITS...

**Comment by constantinpape** [comment]
Ok, I figured it out from the xml dump of https://s3.embl.de/pag-dapex2-fibsem/ in the meantime:
The issue is that it says `.../images/local` here: https://github.com/mobie/pag-dapex2-fibsem/blob/main/data/Sample_6/images/bdv-n5-s3/Sample6_image.xml#L5
But it should be `images/bdv-n5` (see xml dump).

**Comment by martinschorb** [comment]
OK, cool. Thanks. That explains it.
Still the error message is not really helpful in this respect. I would have expected something like "path not found"

**Comment by constantinpape** [comment]
Yes, I agree that this error message can be improved. cc @tischi

**Comment by martinschorb** [comment]
In fact, the proper remote (bdv.n5.s3) entries were also missing in the `dataset.json`s. So this was probably triggering the error.

Now at least the default view works from remote...
When I try to load `Sample_4`, I get:
```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:78)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:230)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:222)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:252)
	at sc.fiji.bdvpg.bdv.navigate.ViewerTransformAdjuster.getTransform(ViewerTransformAdjuster.java:120)
	at sc.fiji.bdvpg.bdv.navigate.ViewerTransformAdjuster.run(ViewerTransformAdjuster.java:80)
	at org.embl.mobie.viewer.view.ViewManager.adjustViewerTransform(ViewManager.java:324)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:309)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:208)
	at org.embl.mobie.viewer.MoBIE.setDataset(MoBIE.java:307)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$7(UserInterfaceHelper.java:573)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:145)
	at net.imglib2.cache.ref.BoundedSoftRefLoaderCache.get(BoundedSoftRefLoaderCache.java:87)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:74)
	... 24 more
Caused by: java.lang.NullPointerException
	at org.embl.mobie.io.n5.loaders.N5ImageLoader$SetupImgLoader.prepareCachedImage(N5ImageLoader.java:390)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader$SetupImgLoader.getImage(N5ImageLoader.java:348)
	at bdv.SpimSource.getImage(SpimSource.java:59)
	at bdv.AbstractSpimSource.lambda$new$0(AbstractSpimSource.java:163)
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:135)
	... 27 more
Exception in thread "PainterThread" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:78)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:230)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:222)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:252)
	at bdv.viewer.render.VisibilityUtils.computeVisibleSourcesOnScreen(VisibilityUtils.java:97)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:428)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:473)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:145)
	at net.imglib2.cache.ref.BoundedSoftRefLoaderCache.get(BoundedSoftRefLoaderCache.java:87)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:74)
	... 7 more
Caused by: java.lang.NullPointerException
	at org.embl.mobie.io.n5.loaders.N5ImageLoader$SetupImgLoader.prepareCachedImage(N5ImageLoader.java:390)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader$SetupImgLoader.getImage(N5ImageLoader.java:348)
	at bdv.SpimSource.getImage(SpimSource.java:59)
	at bdv.AbstractSpimSource.lambda$new$0(AbstractSpimSource.java:163)
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:135)
	... 10 more
```

Does that now mean some data is missing remotely? I am pretty sure the remote metadata is correct as I created it the exact same way as for `Sample_3` using https://github.com/mobie/mobie-utils-python/blob/b19c6d1725814a599022d74752220a5f5a80a84e/mobie/metadata/remote_metadata.py#L115 .

**Comment by constantinpape** [comment]
Hmm, I can tell you more once I have browse access to the bucket. Debugging this further purely from the xml dumps is not possible.

**Comment by constantinpape** [comment]
So the issue is that the `attributes.json` file is missing for `embl/pag-dapex2-fibsem/Sample_4/images/bdv-n5/Sample4_image.n5/setup0/timepoint0/s0`.
See 
```
$ mc ls embl/pag-dapex2-fibsem/Sample_4/images/bdv-n5/Sample4_image.n5/setup0/timepoint0/s0`
[2022-01-11 12:45:24 CET]     0B 0/                                                                                           
[2022-01-11 12:45:24 CET]     0B 1/
[2022-01-11 12:45:24 CET]     0B 10/
.... 
```
versus
```
mc ls embl/pag-dapex2-fibsem/Sample_3/images/bdv-n5/Sample3_image.n5/setup0/timepoint0/s0              
[2022-01-10 18:07:20 CET]   132B attributes.json                                                                              
[2022-01-11 12:45:38 CET]     0B 0/
[2022-01-11 12:45:38 CET]     0B 1/                                                                                           [
[2022-01-11 12:45:38 CET]     0B 10/
...
```
