### ISSUE TITLE
Occasional SdkClientException when browsing the data from s3

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#60]
When browsing the data from s3, sometimes a `SdkClientException` is triggered.
(So far this happened to me once, once to Yannick).

@igorpisarev @axtimwalde this might be related to n5-s3, has any of you seen this before or some idea about it?

```
java.util.concurrent.ExecutionException: com.amazonaws.SdkClientException: Data read has a different length than the expected: dataLength=200550; expectedLength=201861; includeSkipped=true; in.getClass()=class com.amazonaws.services.s3.AmazonS3Client$2; markedSupported=false; marked=0; resetSinceLastMarked=false; markCount=0; resetCount=0
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:111)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:20)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:362)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:19)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:409)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:386)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:180)
Caused by: com.amazonaws.SdkClientException: Data read has a different length than the expected: dataLength=200550; expectedLength=201861; includeSkipped=true; in.getClass()=class com.amazonaws.services.s3.AmazonS3Client$2; markedSupported=false; marked=0; resetSinceLastMarked=false; markCount=0; resetCount=0
	at com.amazonaws.util.LengthCheckInputStream.checkLength(LengthCheckInputStream.java:151)
	at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:93)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:84)
	at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:99)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:84)
	at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader$S3ObjectInputStreamDrain.read(N5AmazonS3Reader.java:88)
	at java.io.InputStream.read(InputStream.java:170)
	at org.apache.commons.compress.utils.CountingInputStream.read(CountingInputStream.java:51)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:301)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.janelia.saalfeldlab.n5.DefaultBlockReader.read(DefaultBlockReader.java:51)
	at org.janelia.saalfeldlab.n5.DefaultBlockReader.readBlock(DefaultBlockReader.java:87)
	at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader.readBlock(N5AmazonS3Reader.java:235)
	at bdv.img.n5.N5GenericImageLoader$N5CacheArrayLoader.loadArray(N5GenericImageLoader.java:318)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$1(VolatileGlobalCellCache.java:247)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:22)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:101)
	... 7 more
	Suppressed: com.amazonaws.SdkClientException: Data read has a different length than the expected: dataLength=200550; expectedLength=201861; includeSkipped=true; in.getClass()=class com.amazonaws.services.s3.AmazonS3Client$2; markedSupported=false; marked=0; resetSinceLastMarked=false; markCount=0; resetCount=0
		at com.amazonaws.util.LengthCheckInputStream.checkLength(LengthCheckInputStream.java:151)
		at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:93)
		at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:84)
		at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:99)
		at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:84)
		at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader$S3ObjectInputStreamDrain.read(N5AmazonS3Reader.java:88)
		at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader$S3ObjectInputStreamDrain.close(N5AmazonS3Reader.java:95)
		at java.io.FilterInputStream.close(FilterInputStream.java:181)
		at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
		at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.close(GzipCompressorInputStream.java:394)
		at org.janelia.saalfeldlab.n5.DefaultBlockReader.read(DefaultBlockReader.java:52)
		... 13 more
	Suppressed: com.amazonaws.SdkClientException: Data read has a different length than the expected: dataLength=200550; expectedLength=201861; includeSkipped=true; in.getClass()=class com.amazonaws.services.s3.AmazonS3Client$2; markedSupported=false; marked=0; resetSinceLastMarked=false; markCount=0; resetCount=0
		at com.amazonaws.util.LengthCheckInputStream.checkLength(LengthCheckInputStream.java:151)
		at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:93)
		at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:84)
		at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:99)
		at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:84)
		at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader$S3ObjectInputStreamDrain.read(N5AmazonS3Reader.java:88)
		at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader$S3ObjectInputStreamDrain.close(N5AmazonS3Reader.java:95)
		at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader.readBlock(N5AmazonS3Reader.java:236)
		... 11 more
```

**Comment by igorpisarev** [comment]
I haven't seen this exception yet, but it definitely looks related to n5-aws-s3. Do you only browse the data, or is it also being written to S3 at the same time? Also, does it consistently occur for the same block or is it rather random?

**Comment by constantinpape** [comment]
> Do you only browse the data, or is it also being written to S3 at the same time?

Only browsing, there is no write to the s3 Dataset at the same time. (There might be writes to the same bucket though, but the datasets loaded are definitely static).

> Also, does it consistently occur for the same block or is it rather random?

It seems rather random. We will do some more thorough testing in the next few days, maybe we'll be able to see some more systematic in this error then.

**Comment by igorpisarev** [comment]
It may be also helpful for diagnosing to wrap `N5AmazonS3Reader.readBlock()` in try-catch and output the block grid index or S3 key when the exception occurs.

**Comment by axtimwalde** [comment]
I think we will have to consider this, remote sources aren't as reliable as local sources.  Ideas how to deal with it?
[] Try again until successful (for a parameterizable number of times)
[] Load the broken data.
[] Return null .

**Comment by constantinpape** [comment]
I ran into this issue again, and it seems like this happened when I ran out of RAM on my notebook.
Might be just a coincidence though.

**Comment by constantinpape** [comment]
I haven't seen any "bad consequences" of this exception; i.e. the viewer state does not seem to be affected (much). Of course we should fix the general issue here, but I think in the meantime we can hide this exception from the users.
@tischi Do we have different log levels? Then this could be pushed to DEBUG.

**Comment by tischi** [comment]
Maybe I can add a `try{} catch{}` here:

```
at bdv.img.n5.N5GenericImageLoader$N5CacheArrayLoader.loadArray(N5GenericImageLoader.java:318)``

**Comment by tischi** [comment]
@constantinpape 
Is this still an issue?

**Comment by constantinpape** [comment]
No, I haven't seen this in a while, gonna close.
