### ISSUE TITLE
Relative table paths for CustomBrowser don't work on Windows

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#62]
Viewing segmentations that have 'default.csv' files as relative paths do not work on Windows (works fine if the full table is present in that version). e.g. viewing the chromatin segmentation on version 0.6.6 does not work

Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Could not identify table delimiter.
	at de.embl.cba.tables.Tables.autoDelim(Tables.java:228)
	at de.embl.cba.tables.TableColumns.stringColumnsFromTableFile(TableColumns.java:85)
	at de.embl.cba.tables.TableColumns.stringColumnsFromTableFile(TableColumns.java:75)
	at de.embl.cba.platynereis.utils.Utils.createAnnotatedImageSegmentsFromTableFile(Utils.java:285)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.showAnnotatedLabelsSource(PlatyBrowserSourcesPanel.java:402)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToViewer(PlatyBrowserSourcesPanel.java:327)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToPanelAndViewer(PlatyBrowserSourcesPanel.java:309)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToPanelAndViewer(PlatyBrowserSourcesPanel.java:274)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserActionPanel.lambda$addSourceSelectionComboBoxAndButton$6(PlatyBrowserActionPanel.java:410)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by K-Meech** [comment]
Actually, this works fine on the remote version 'Open Platybrowser', but not for 'Open Platybrowser Advanced'  (there I'm using the image data location as the arendt lab server & the table data location as a local clone of my fork of the platybrowser-backend repo)

**Comment by tischi** [comment]
I added more error message to make it easier to debug.
Please try again tomorrow and paste the errors here.

**Comment by K-Meech** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Could not identify table delimiter.
	at de.embl.cba.tables.Tables.autoDelim(Tables.java:228)
	at de.embl.cba.tables.TableColumns.stringColumnsFromTableFile(TableColumns.java:85)
	at de.embl.cba.tables.TableColumns.stringColumnsFromTableFile(TableColumns.java:75)
	at de.embl.cba.platynereis.utils.Utils.createAnnotatedImageSegmentsFromTableFile(Utils.java:285)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.showAnnotatedLabelsSource(PlatyBrowserSourcesPanel.java:389)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToViewer(PlatyBrowserSourcesPanel.java:322)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToPanelAndViewer(PlatyBrowserSourcesPanel.java:304)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToPanelAndViewer(PlatyBrowserSourcesPanel.java:269)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserActionPanel.lambda$addSourceSelectionComboBoxAndButton$6(PlatyBrowserActionPanel.java:404)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by tischi** [comment]
OK. I am surprised! Maybe really the problem is: ` Could not identify table delimiter.`?
Could you please paste the first 2 rows of this table here?

**Comment by K-Meech** [comment]
The file from that version is just the relative path:
../../../rawdata/tables/sbem-6dpf-1-whole-segmented-chromatin/default.csv

I wonder if on windows it's trying to literally read this as the table (and hence not understanding the delimiter) rather than following the path? Could it be an issue that windows uses \ rather than /?

**Comment by tischi** [comment]
...**not** the path to the table but the _content_ of the table, first two rows please 😃

**Comment by constantinpape** [comment]
This is the file at hand: https://github.com/platybrowser/platybrowser-backend/blob/master/data/rawdata/tables/sbem-6dpf-1-whole-segmented-chromatin/default.csv

**Comment by tischi** [comment]
> I wonder if on windows it's trying to **literally read this as the table** (and hence not understanding the delimiter) rather than following the path?

@K-Meech Ok. Now I got it. This is indeed a very good hypothesis! I will look into this.

**Comment by constantinpape** [comment]
@K-Meech is this working now?

**Comment by K-Meech** [comment]
No - it still doesn't work. Although, as this is only on the Custom Browser, I guess it is lower priority.

**Comment by tischi** [comment]
> Although, as this is only on the Custom Browser, I guess it is lower priority.

Yes, let's fix this after submission. OK?

**Comment by K-Meech** [comment]
Sure - no problem

**Comment by tischi** [comment]
@K-Meech 
Is this still an issue?

**Comment by K-Meech** [comment]
Having a quick look on the arendt share - it seems like the default.csv files that had relative paths in them, are now full tables. @constantinpape - are you still using any relative paths in the default.csv files?

**Comment by constantinpape** [comment]
@K-Meech yes, we still have some relative paths, for example
```
/g/arendt/EM_6dpf_segmentation/platy-browser-data/data/1.0.1/tables/sbem-6dpf-1-whole-segmented-nuclei/default.csv ->
/g/arendt/EM_6dpf_segmentation/platy-browser-data/data/1.0.0/tables/sbem-6dpf-1-whole-segmented-nuclei/default.csv
```

**Comment by K-Meech** [comment]
Just checked - this is still an issue. Viewing the nuclei segmentation gives this error:

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Could not identify table delimiter.
	at de.embl.cba.tables.Tables.autoDelim(Tables.java:242)
	at de.embl.cba.tables.TableColumns.stringColumnsFromTableFile(TableColumns.java:113)
	at de.embl.cba.tables.TableColumns.stringColumnsFromTableFile(TableColumns.java:104)
	at de.embl.cba.mobie.utils.Utils.createAnnotatedImageSegmentsFromTableFile(Utils.java:302)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.showAnnotatedLabelsSource(SourcesPanel.java:467)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:355)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:339)
	at de.embl.cba.mobie.ui.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:296)
	at de.embl.cba.mobie.ui.viewer.ActionPanel.lambda$null$12(ActionPanel.java:428)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by tischi** [comment]
@K-Meech 
Since you are by now quite deep in the code and probably have an IDE on windows, could you try to debug this?

**Comment by K-Meech** [comment]
Yeah sure - I can take a look later in the week

**Comment by K-Meech** [comment]
This is already fixed
