### ISSUE TITLE
N5 projects made with project creator can't be opened from S3 (private bucket)

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#621]
Trying to open a private project with N5 images directly from S3, with a command like so:
```
new MoBIE("https://s3.embl.de/...",
                    MoBIESettings.settings().imageDataFormat( ImageDataFormat.BdvN5S3 ).s3AccessAndSecretKey( user, key))
```

gives 403 exceptions as below. This doesn't happen if exactly the same project is made with OME-ZARR images instead. @tischi - have you seen the same issues with N5 projects?

```
Error while trying to read spimDataServer returned HTTP response code: 403 for URL
```

**Comment by tischi** [comment]
Nope. I don't even know what `spimDataServer` is ...
I think we have to debug into where exactly this error happens. 
Can you post more of the error message?

**Comment by K-Meech** [comment]
I looked into this a bit more - and it can read the project.json / dataset.json, but fails when it tries to read the image xml. It errors at this line: https://github.com/mobie/mobie-io/blob/develop/src/main/java/org/embl/mobie/io/n5/openers/N5S3Opener.java#L103 . I think because it doesn't use the access key/code.

The full error is below:
```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: mpicbg.spim.data.SpimDataException: Error while trying to read spimDataServer returned HTTP response code: 403 for URL: https://s3.embl.de/meechan-user/test/images/bdv-n5-s3/mri-stack.xml
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.embl.mobie.viewer.ThreadUtils.waitUntilFinished(ThreadUtils.java:30)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverters(MoBIE.java:230)
	at org.embl.mobie.viewer.view.ViewManager.openAndTransformViewSources(ViewManager.java:285)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:264)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:247)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:176)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:83)
	at run.Temp.main(Temp.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:64)
Caused by: java.lang.RuntimeException: mpicbg.spim.data.SpimDataException: Error while trying to read spimDataServer returned HTTP response code: 403 for URL: https://s3.embl.de/meechan-user/test/images/bdv-n5-s3/mri-stack.xml
	at org.embl.mobie.viewer.MoBIE.tryOpenSpimData(MoBIE.java:356)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:330)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: mpicbg.spim.data.SpimDataException: Error while trying to read spimDataServer returned HTTP response code: 403 for URL: https://s3.embl.de/meechan-user/test/images/bdv-n5-s3/mri-stack.xml
	at org.embl.mobie.io.SpimDataOpener.openBdvN5S3(SpimDataOpener.java:110)
	at org.embl.mobie.io.SpimDataOpener.openSpimData(SpimDataOpener.java:69)
	at org.embl.mobie.viewer.MoBIE.tryOpenSpimData(MoBIE.java:351)
	... 8 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:64)
Caused by: java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.adaptConverter(ImageSliceView.java:89)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.show(ImageSliceView.java:59)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.<init>(ImageSliceView.java:44)
	at org.embl.mobie.viewer.view.ViewManager.showImageDisplay(ViewManager.java:383)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:350)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:270)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:247)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:176)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:83)
	at run.Temp.main(Temp.java:45)
	... 5 more
```

**Comment by K-Meech** [comment]
Yes - I think that's it (the bucket is protected with keys). I think this is something that would need to be fixed in the SpimDataOpener in the mobie-io repo. I'll make an issue there.

**Comment by KateMoreva** [comment]
@K-Meech, could you please try again with 1.2.6-SNAPSHOT mobie-io?

**Comment by K-Meech** [comment]
Thanks @KateMoreva - it gets further now, but errors with this:
```
Caused by: java.lang.NullPointerException
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.createSetupImgLoader(N5ImageLoader.java:233)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.open(N5ImageLoader.java:179)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.getCacheControl(N5ImageLoader.java:260)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:322)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:312)
	at run.Temp.main(Temp.java:62)
	... 5 more
```
It's getting to this line: https://github.com/mobie/mobie-io/blob/develop/src/main/java/org/embl/mobie/io/n5/loaders/N5ImageLoader.java#L232 and then erroring because the ```dataType``` comes back as null.

**Comment by K-Meech** [comment]
This is fixed now - thanks @KateMoreva!
