### ISSUE TITLE
Test failure for loading bdv n5 from s3

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#636]
This test throws an error when running with the current `develop` branch: `TestRemotePlanktonS3`

`https://s3.embl.de/plankton-fibsem/emiliania/images/bdv-n5-s3/raw.xml`

```
java.lang.NullPointerException
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.createSetupImgLoader(N5ImageLoader.java:233)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.open(N5ImageLoader.java:179)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:226)
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.getSetupImgLoader(N5ImageLoader.java:81)
	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.createSourceAndConverters(SourceAndConverterFromSpimDataCreator.java:91)
	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.<init>(SourceAndConverterFromSpimDataCreator.java:61)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:335)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:226)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error opening: https://s3.embl.de/plankton-fibsem/emiliania/images/bdv-n5-s3/raw.xml
```

ping @constantinpape

**Comment by K-Meech** [comment]
This looks very similar to the issue I'm having here: https://github.com/mobie/mobie-viewer-fiji/issues/621 @KateMoreva - would you have time to take a look with ```https://s3.embl.de/plankton-fibsem/emiliania/images/bdv-n5-s3/raw.xml```?

**Comment by KateMoreva** [comment]
TestRemotePlanktonS3 should be able to open again.

**Comment by tischi** [comment]
@KateMoreva Could you please add opening of `https://s3.embl.de/plankton-fibsem/emiliania/images/bdv-n5-s3/raw.xml` as a test to mobie-io?

**Comment by tischi** [comment]
@constantinpape Or is that a project that could change? Not sure how stable this project is... In fact, the platybrowser project also is `bdv-n5-s3`, isn't it? Isn't there a test in mobie-io for opening on of those images?

**Comment by constantinpape** [comment]
> @constantinpape Or is that a project that could change?

It's stable and can be used for testing.

> In fact, the platybrowser project also is `bdv-n5-s3`, isn't it?

Yes it is.

**Comment by constantinpape** [comment]
Closed in favor of https://github.com/mobie/mobie-io/issues/87
