### ISSUE TITLE
Serialization exception

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#645]
@NicoKiaru normally the below issue is solved by a `mvn clean compile`, but now it was not even working then for me. Do you have an idea how to avoid this error message in some more reliable way? We could actually also do _without_ the serialization, but somehow I remember we needed this to be compatible with the playground?

```
Exception in thread "main" com.google.gson.JsonParseException: cannot serialize org.embl.mobie.viewer.bdv.MobieBdvSupplier; did you forget to register a subtype?
	at sc.fiji.persist.RuntimeTypeAdapterFactory$1.write(RuntimeTypeAdapterFactory.java:275)
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:191)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:638)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.setDefaultBdvSupplier(SourceAndConverterBdvDisplayService.java:130)
	at org.embl.mobie.viewer.bdv.view.SliceViewer.createBdv(SliceViewer.java:176)
	at org.embl.mobie.viewer.bdv.view.SliceViewer.<init>(SliceViewer.java:61)
	at org.embl.mobie.viewer.view.ViewManager.<init>(ViewManager.java:88)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:243)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:175)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:82)
	at projects.OpenRemotePlatynereis.main(OpenRemotePlatynereis.java:19)
```

**Comment by NicoKiaru** [comment]
That's weird, because it means that the class MobieBdvSupplier is accessible but not its serializer.

I can try to catch this error in https://github.com/bigdataviewer/bigdataviewer-playground/blob/94c947c2b908d8def28281c3706e0b5bca459a53/src/main/java/sc/fiji/bdvpg/scijava/services/SourceAndConverterBdvDisplayService.java#L130
