### ISSUE TITLE
Context Menu for Screenshot Hangs

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#658]
VisualVM gives this:

```
"AWT-EventQueue-0" #14 prio=6 os_prio=31 tid=0x00007fe05185a800 nid=0xcd03 waiting for monitor entry [0x000070000e002000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.awt.Component.invalidate(Component.java:2929)
        - waiting to lock <0x0000000541a016d0> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.invalidate(Container.java:1590)
        at javax.swing.JComponent.revalidate(JComponent.java:4848)
        at javax.swing.plaf.basic.BasicTextUI$RootView.preferenceChanged(BasicTextUI.java:1406)
        at javax.swing.text.View.preferenceChanged(View.java:288)
        at javax.swing.text.BoxView.preferenceChanged(BoxView.java:286)
        at javax.swing.text.View.preferenceChanged(View.java:288)
        at javax.swing.text.BoxView.preferenceChanged(BoxView.java:286)
        at javax.swing.text.View.preferenceChanged(View.java:288)
        at javax.swing.text.BoxView.preferenceChanged(BoxView.java:286)
        at javax.swing.text.View.preferenceChanged(View.java:288)
        at javax.swing.text.View.preferenceChanged(View.java:288)
        at javax.swing.text.html.InlineView.changedUpdate(InlineView.java:96)
        at javax.swing.text.View.forwardUpdateToView(View.java:1231)
        at javax.swing.text.FlowView$LogicalView.forwardUpdateToView(FlowView.java:795)
        at javax.swing.text.View.forwardUpdate(View.java:1162)
        at javax.swing.text.FlowView$LogicalView.forwardUpdate(FlowView.java:805)
        at javax.swing.text.View.changedUpdate(View.java:792)
        at javax.swing.text.FlowView.changedUpdate(FlowView.java:283)
        at javax.swing.text.ParagraphView.changedUpdate(ParagraphView.java:788)
        at javax.swing.text.View.forwardUpdateToView(View.java:1231)
        at javax.swing.text.View.forwardUpdate(View.java:1162)
        at javax.swing.text.BoxView.forwardUpdate(BoxView.java:240)
        at javax.swing.text.View.changedUpdate(View.java:792)
        at javax.swing.text.html.BlockView.changedUpdate(BlockView.java:341)
        at javax.swing.text.View.forwardUpdateToView(View.java:1231)
        at javax.swing.text.View.forwardUpdate(View.java:1162)
        at javax.swing.text.BoxView.forwardUpdate(BoxView.java:240)
        at javax.swing.text.View.changedUpdate(View.java:792)
        at javax.swing.text.html.BlockView.changedUpdate(BlockView.java:341)
        at javax.swing.plaf.basic.BasicTextUI$RootView.changedUpdate(BasicTextUI.java:1638)
        at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.changedUpdate(BasicTextUI.java:1899)
        at javax.swing.text.AbstractDocument.fireChangedUpdate(AbstractDocument.java:230)
        at javax.swing.text.html.HTMLDocument.fireChangedUpdate(HTMLDocument.java:1738)
        at javax.swing.text.DefaultStyledDocument$ChangeUpdateRunnable.run(DefaultStyledDocument.java:2738)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

   Locked ownable synchronizers:
        - None
```

**Comment by tischi** [comment]
@NicoKiaru I am launching a `DynamicCommand` here. My best guess is that it hangs in the `initialize()` method. When running in debug mode in IntellIj everything works find. But in Fiji it hangs. Do you have any experience with this?

**Comment by tischi** [comment]
It is weird, because this used to work. 

@NicoKiaru Did you change anything how the Commands are launched from the context menu?

@K-Meech Could you please try whether `Take Screenshot` works for you in Fiji (on your Windows computer)?

**Comment by K-Meech** [comment]
@tischi It works for me (on the latest mobie-beta)

**Comment by tischi** [comment]
Ok, it hangs for me (MacOS).

**Comment by tischi** [comment]
@K-Meech I also added the `Take Screenshot` context menu for `Open OME-Zarr...`. Could you please try whether it works there for you as well?

**Comment by K-Meech** [comment]
@tischi - yes that works too on Windows

**Comment by tischi** [comment]
I removed `Initializable` from the `Take Screenshot`, but it still sometimes hangs :-(
I will try to remove the `DynamicCommand` and see whether that helps...

**Comment by tischi** [comment]
Ok, also that does not help.
Now the only thing that remains special for this command is that it has
```
    @Parameter
    public BdvHandle bdvh;
```
@NicoKiaru Could it be that the preprocessing of this can hang?

**Comment by tischi** [comment]
OK, there was another thing. I was having two messages showing:
```
    @Parameter( visibility = MESSAGE, required = false )
    String message = CAPTURE_SIZE_PIXELS +"";

    @Parameter( visibility = MESSAGE, required = false )
    String scaleBarMessage = "Add Scale Bar: [ Analyze > Tools > Scale Bar... ]";
```
Commenting this out seems to fix it 🤞

**Comment by NicoKiaru** [comment]
Looks annyoing... Do you have the full thread dump from visual vm?

**Comment by tischi** [comment]
At the top of the issue I have posted the thread that (I think) was hanging...
I can try to put a full one later (right now I am hoping that it works without the `visibility = MESSAGE` guys...

**Comment by NicoKiaru** [comment]
If it's a standard thread deadlock, normally two threads are involved. So maybe the full dump can tell us something interesting... fingers crossed

**Comment by tischi** [comment]
@K-Meech I updated MoBIE-beta.
Could you please have a quick check whether the Screenshot works for you?

**Comment by K-Meech** [comment]
@tischi - yes it works for me
