### ISSUE TITLE
Exception when switching between views

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#700]
When switching between views, I now often get similar exceptions to this one:
```
Exception in thread "Thread-13" java.lang.ClassCastException: org.embl.mobie.viewer.display.AnnotatedSourceDisplay cannot be cast to org.embl.mobie.viewer.display.SegmentationSourceDisplay
	at org.embl.mobie.viewer.view.ViewManager.removeSourceDisplay(ViewManager.java:530)
	at org.embl.mobie.viewer.view.ViewManager.removeAllSourceDisplays(ViewManager.java:375)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:259)
	at org.embl.mobie.viewer.ui.UserInterfaceHelpers.lambda$null$7(UserInterfaceHelpers.java:493)
	at java.lang.Thread.run(Thread.java:748)
```

To reproduce this particular example:
- https://github.com/mobie/clem-example-project/, branch: `more-views`
- select the `all_sources_with_table` view, wait till it has loaded
- select the `highmag_tomos` view, this will produce the above error

Tested with most recent MoBIE-beta

**Comment by tischi** [comment]
I tried it and it works on `develop`.

**Comment by constantinpape** [comment]
(this is probably the same issue as #693)

**Comment by constantinpape** [comment]
This is fixed now in the most recent MoBIE-beta.
