### ISSUE TITLE
Esception when changing table color

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#705]
- `more-views` branch of the CLEM dataset, `Fig2_a` view.
- `Color -> Color by Column...`
- `argbColumn`

leads to:

```
Exception in thread "Thread-11" java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at de.embl.cba.tables.color.ColumnColoringModelCreator.populateColoringModelFromArgbColumn(ColumnColoringModelCreator.java:199)
	at de.embl.cba.tables.color.ColumnColoringModelCreator.createCategoricalColoringModel(ColumnColoringModelCreator.java:243)
	at de.embl.cba.tables.color.ColumnColoringModelCreator.createColoringModel(ColumnColoringModelCreator.java:161)
	at de.embl.cba.tables.color.ColumnColoringModelCreator.showDialog(ColumnColoringModelCreator.java:113)
	at org.embl.mobie.viewer.table.TableViewer.showColorByColumnDialog(TableViewer.java:997)
	at org.embl.mobie.viewer.table.TableViewer.lambda$null$29(TableViewer.java:989)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by martinschorb** [comment]
other color maps work.

**Comment by constantinpape** [comment]
This is expected, ARGB columns need a special format, see https://github.com/mobie/clem-example-project/issues/20#issuecomment-1119418861.
