### ISSUE TITLE
Saving views with merged grid fails

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#712]
Saving a view with a merged grid currently fails, see the error message below.
To reproduce: 
- open the project at https://github.com/mobie/covid-if-project
- wait till the default view has loaded, then save it via the context menu

Error message:
```
Exception in thread "Thread-13" java.lang.UnsupportedOperationException: Could not serialise SourceTransformer of type: class org.embl.mobie.viewer.transform.MergedGridSourceTransformer
	at org.embl.mobie.viewer.serialize.SourceTransformerListAdapter.serialize(SourceTransformerListAdapter.java:58)
	at org.embl.mobie.viewer.serialize.SourceTransformerListAdapter.serialize(SourceTransformerListAdapter.java:14)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at org.embl.mobie.viewer.serialize.AdditionalViewsJsonParser.saveViews(AdditionalViewsJsonParser.java:33)
	at org.embl.mobie.viewer.view.saving.ViewSavingHelpers.writeAdditionalViewsJson(ViewSavingHelpers.java:34)
	at org.embl.mobie.viewer.view.saving.ViewsSaver.saveNewViewToAdditionalViewsJson(ViewsSaver.java:297)
	at org.embl.mobie.viewer.view.saving.ViewsSaver.lambda$saveNewViewToFileSystem$0(ViewsSaver.java:161)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.io.IOException: Incomplete document
		at com.google.gson.stream.JsonWriter.close(JsonWriter.java:558)
		at org.embl.mobie.viewer.serialize.AdditionalViewsJsonParser.saveViews(AdditionalViewsJsonParser.java:34)
		... 4 more
```

**Comment by K-Meech** [comment]
@constantinpape - I can look into this.

**Comment by K-Meech** [comment]
This is fixed on the current develop branch
