### ISSUE TITLE
Loading additional views from project fails

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#714]
See error message below. To reproduce:
- Open platybrowser
- Context menu -> load additional views -> from project

```
Unexpected response code: 404
null.
404 Not Found
X-RateLimit-Resource: core
Server: GitHub.com
X-RateLimit-Used: 2
Access-Control-Allow-Origin: *
X-Content-Type-Options: nosniff
X-RateLimit-Reset: 1652271787
Date: Wed, 11 May 2022 12:01:53 GMT
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
X-Frame-Options: deny
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
X-RateLimit-Remaining: 58
X-GitHub-Media-Type: unknown, github.v3
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-RateLimit-Limit: 60
Content-Length: 113
X-XSS-Protection: 0
X-GitHub-Request-Id: F602:29EC:31F663:32CD42:627BA5B0
Content-Type: application/json; charset=utf-8

java.lang.RuntimeException
Exception in thread "Thread-12" java.lang.RuntimeException: java.lang.RuntimeException
	at org.embl.mobie.io.github.RESTCaller.get(RESTCaller.java:102)
	at org.embl.mobie.io.github.GitHubContentGetter.getContent(GitHubContentGetter.java:66)
	at org.embl.mobie.io.github.GitHubUtils.getFilePaths(GitHubUtils.java:91)
	at org.embl.mobie.io.github.GitHubUtils.getFileNames(GitHubUtils.java:85)
	at org.embl.mobie.io.util.FileAndUrlUtils.getFileNames(FileAndUrlUtils.java:239)
	at org.embl.mobie.viewer.MoBIEHelper.selectPathFromProject(MoBIEHelper.java:237)
	at org.embl.mobie.viewer.view.additionalviews.AdditionalViewsLoader.lambda$loadAdditionalViewsDialog$0(AdditionalViewsLoader.java:31)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException
	at org.embl.mobie.io.github.RESTCaller.parseResponse(RESTCaller.java:113)
	at org.embl.mobie.io.github.RESTCaller.get(RESTCaller.java:99)
	... 7 more
```

**Comment by constantinpape** [comment]
Yep, that has fixed it.
