### ISSUE TITLE
Loading additional views from file fails

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#715]
see error message beow.
To reproduce:
- open https://github.com/mobie/covid-if-project
- Select "Load additional views -> FileSystem"
- Navigate to [this file](https://github.com/mobie/covid-if-project/blob/main/data/20200406_164555_328/misc/bookmarks/mobie-paper.json) and press ok

Note: opening from project does not work due to #714 

```
Exception in thread "Thread-15" java.lang.NullPointerException
	at java.util.AbstractMap.putAll(AbstractMap.java:280)
	at org.embl.mobie.viewer.view.additionalviews.AdditionalViewsLoader.loadViews(AdditionalViewsLoader.java:50)
	at org.embl.mobie.viewer.view.additionalviews.AdditionalViewsLoader.lambda$loadAdditionalViewsDialog$0(AdditionalViewsLoader.java:38)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by K-Meech** [comment]
I'll look into these 'load additional views' errors too @constantinpape

**Comment by K-Meech** [comment]
This works for other files, so I think it's an issue with this specific file. @constantinpape -I think everything has to go inside a "views" layer according to https://github.com/mobie/mobie.github.io/blob/master/schema/views.schema.json like:
```
{
  "views": {
    "view1": {}
    }
}
```
Maybe that's the issue?
