### ISSUE TITLE
MoBIE-beta: opening covid-if-project fails

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#734]
Opening the covid-if project (https://github.com/mobie/covid-if-project) fails with the latest beta with:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.RuntimeException: Unknown class: regionDisplay
	at org.embl.mobie.viewer.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:45)
	at org.embl.mobie.viewer.serialize.SourceDisplayListAdapter.deserialize(SourceDisplayListAdapter.java:36)
	at org.embl.mobie.viewer.serialize.SourceDisplayListAdapter.deserialize(SourceDisplayListAdapter.java:14)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at org.embl.mobie.viewer.serialize.DatasetJsonParser.parseDataset(DatasetJsonParser.java:25)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:241)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:175)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:82)
	at org.embl.mobie.viewer.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:25)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
```

**Comment by constantinpape** [comment]
Same issue for https://github.com/mobie/plankton-fibsem-project when opening the `micromonas` dataset.

The issue seems to occur when a regionDisplay is in the default view. It works fine when it's in a view that is selected after the viewer has fully started.

**Comment by tischi** [comment]
Hm, I get a different error:

```
new MoBIE( "https://github.com/mobie/covid-if-project" );
```

```
13:02:57.500 [main] DEBUG sc.fiji.bdvpg.sourceandconverter.SourceAndConverterHelper - Unsupported ConverterSetup for Converters of class class org.embl.mobie.viewer.color.ListItemsARGBConverter
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
	at de.embl.cba.tables.TableColumns.stringColumnsFromTableFile(TableColumns.java:155)
	at de.embl.cba.tables.TableColumns.stringColumnsFromTableFile(TableColumns.java:125)
	at org.embl.mobie.viewer.MoBIE.loadAnnotatedMaskTables(MoBIE.java:662)
	at org.embl.mobie.viewer.view.ViewManager.showAnnotatedMaskDisplay(ViewManager.java:393)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:344)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:254)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:291)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:183)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:89)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:72)
	at projects.OpenRemoteCovidIF.main(OpenRemoteCovidIF.java:20)
```

**Comment by tischi** [comment]
> Same issue for https://github.com/mobie/plankton-fibsem-project when opening the micromonas dataset.

I get 
```
13:07:37.384 [main] DEBUG sc.fiji.bdvpg.scijava.services.SourceAndConverterService - Source already registered
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Unknown class: sourceAnnotationDisplay
```

The JSON spec is the old one, should be `regionDisplay`.

**Comment by constantinpape** [comment]
> I get
> 
> ```
> 13:07:37.384 [main] DEBUG sc.fiji.bdvpg.scijava.services.SourceAndConverterService - Source already registered
> Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Unknown class: sourceAnnotationDisplay
> ```
> 
> The JSON spec is the old one, should be `regionDisplay`.

No, it's correctly set to `regionDisplay`, see https://github.com/mobie/plankton-fibsem-project/blob/main/data/micromonas/dataset.json#L285.

**Comment by tischi** [comment]
Maybe some github issue. 
Sometimes it takes a while till they update the raw githubuser content.
I will try again later.

**Comment by constantinpape** [comment]
FWIW it's correct (i.e. using `regionDisplay`) in the raw file already, see https://raw.githubusercontent.com/mobie/plankton-fibsem-project/main/data/micromonas/dataset.json

**Comment by tischi** [comment]
super weird. something is caching here.

**Comment by tischi** [comment]
ah, I was opening: https://s3.embl.de/plankton-fibsem

**Comment by tischi** [comment]
But now it works:

```
# MoBIE
Opening project: https://github.com/mobie/plankton-fibsem-project
Opening dataset: micromonas
Opening view: default
 
Opening (1/1): https://raw.githubusercontent.com/mobie/plankton-fibsem-project/main/data/micromonas/images/bdv-n5-s3/cell1-raw.xml
Opening image:
https://raw.githubusercontent.com/mobie/plankton-fibsem-project/main/data/micromonas/images/bdv-n5-s3/cell1-raw.xml
Opened 1 image(s) in 4570 ms, using 16 thread(s).
 
Opened view: default, in 5082 ms.
 ```

There does not seem to be a `regionDisplay` in the default view?
https://github.com/mobie/plankton-fibsem-project/blob/be6f31750f75a073d951f4b92e7bd12b42354f87/data/micromonas/dataset.json#L651

**Comment by tischi** [comment]
@constantinpape 

You seems to have some columns without values:

https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/sites/default.tsv

There are 9 columns, but initially there are only 8 entries, well one seems to be an empty String.
I am not sure we support this. I could have a look.

```
  1 region_id>------well>---score>--is_outlier>-----n_outlier_cells>n_infected_cells>-------n_non_infected_cells>-    --serum_background_intensity>-----serum_background_variance$
  2 A01_0000>-------A01>---->-------1>------12>-----11>-----603>----3571.913>-------127.71118$
  3 A01_0001>-------A01>---->-------1>------20>-----7>------627>----3535.7656>------126.48584$
```

**Comment by tischi** [comment]
I had a look in the Java code and I think we don't support empty Strings as a table cell...do we?

**Comment by constantinpape** [comment]
micronomas view also works for me now.
I will look into updating the project on s3.

**Comment by constantinpape** [comment]
> I had a look in the Java code and I think we don't support empty Strings as a table cell...do we?

I see, I understand what's going wrong there now (it's because I had to resave the table and the standard way of pandas to treat nans is not compatible with MoBIE.) I will fix it later, I am busy with other things for now.

**Comment by constantinpape** [comment]
I fixed the issue with the table now, but there is another issue with loading the project, but I will create a separate one for it.
The issues discussed here are fixed now.
