### ISSUE TITLE
crash when annotating crops

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#740]
Hi,

I like to annotate crop views with a boundary.
This is in `Figure2a` of `crop1` branch in the CLEM project.

I get:
```
Exception in thread "Thread-9" java.lang.NullPointerException
	at org.embl.mobie.viewer.annotate.AnnotatedMaskCreator.lambda$createAnnotatedMasks$0(AnnotatedMaskCreator.java:43)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.embl.mobie.viewer.annotate.AnnotatedMaskCreator.createAnnotatedMasks(AnnotatedMaskCreator.java:43)
	at org.embl.mobie.viewer.annotate.AnnotatedMaskCreator.<init>(AnnotatedMaskCreator.java:30)
	at org.embl.mobie.viewer.MoBIE.loadAnnotatedMaskTables(MoBIE.java:671)
	at org.embl.mobie.viewer.view.ViewManager.showAnnotatedMaskDisplay(ViewManager.java:393)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:344)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:254)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$createViewSelectionPanel$7(UserInterfaceHelper.java:488)
	at java.lang.Thread.run(Thread.java:748)
```

the view and project is validated correctly in Python.

Is it because the annotation
https://github.com/mobie/clem-example-project/blob/7a5679d47cc076b463fae7becb71571e52ebd806/data/hela/dataset.json#L783

```
{
          "regionDisplay": {
            "boundaryThickness": 3.0,
            "colorByColumn": "annotationColor",
            "lut": "argbColumn",
            "name": "em-crop-annotations",
            "opacity": 1.0,
            "showAsBoundaries": true,
            "sources": {
              "0": [
                "em-detail-a1-A_crop"
              ],
              "1": [
                "em-detail-a2-A_cropshift"
              ]
            },
            "tableData": {
              "tsv": {
                "relativePath": "tables/em-crop"
              }
            },
            "tables": [
              "default.tsv"
            ]
          }
        }
```

references `sourceName`s that are only generated as a crop in this view?

**Comment by tischi** [comment]
I think slight mix-up in the JSON:

You are referring to `em-detail-a2-A_cropshift`, in the region display but you are only defining:  ["em-detail-a1-A_cropshift"](https://github.com/mobie/clem-example-project/blob/7a5679d47cc076b463fae7becb71571e52ebd806/data/hela/dataset.json#L2092)

**Comment by tischi** [comment]
I upated MoBIE-beta just now, could you try again?

**Comment by martinschorb** [comment]
the solid annotation still appears with the crop. On top, I now also get:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at javax.swing.border.EmptyBorder.<init>(EmptyBorder.java:74)
	at javax.swing.plaf.BorderUIResource$EmptyBorderUIResource.<init>(BorderUIResource.java:139)
	at com.formdev.flatlaf.ui.FlatEmptyBorder.<init>(FlatEmptyBorder.java:43)
	at com.formdev.flatlaf.ui.FlatLineBorder.<init>(FlatLineBorder.java:46)
	at com.formdev.flatlaf.ui.FlatLineBorder.<init>(FlatLineBorder.java:42)
	at com.formdev.flatlaf.ui.FlatTableCellBorder.<init>(FlatTableCellBorder.java:39)
	at com.formdev.flatlaf.ui.FlatTableCellBorder$Default.<init>(FlatTableCellBorder.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.formdev.flatlaf.UIDefaultsLoader.lambda$parseInstance$5(UIDefaultsLoader.java:441)
	at javax.swing.UIDefaults.getFromHashtable(UIDefaults.java:216)
	at javax.swing.UIDefaults.get(UIDefaults.java:264)
	at javax.swing.MultiUIDefaults.get(MultiUIDefaults.java:82)
	at javax.swing.UIManager.get(UIManager.java:971)
	at sun.swing.DefaultLookup.get(DefaultLookup.java:99)
	at sun.swing.DefaultLookup.getBorder(DefaultLookup.java:202)
	at sun.swing.DefaultLookup.getBorder(DefaultLookup.java:210)
	at javax.swing.table.DefaultTableCellRenderer.getNoFocusBorder(DefaultTableCellRenderer.java:117)
	at javax.swing.table.DefaultTableCellRenderer.getTableCellRendererComponent(DefaultTableCellRenderer.java:254)
	at org.embl.mobie.viewer.table.TableViewer$2.getTableCellRendererComponent(TableViewer.java:198)
	at javax.swing.JTable.prepareRenderer(JTable.java:5729)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1978)
	at java.awt.Window.paint(Window.java:3906)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by martinschorb** [comment]
huh, funny...

boundary thickness:
- 1 -> works
- 1<d<5 -> solid
- 5 -> works
![Screenshot 2022-05-23 at 12 17 40](https://user-images.githubusercontent.com/35071867/169798611-3132ad8c-9b69-4220-96e0-dd473dfe5605.png)
![Screenshot 2022-05-23 at 12 17 54](https://user-images.githubusercontent.com/35071867/169798618-add4eb65-b8fa-4462-8617-3c30cdf8ed0c.png)
![Screenshot 2022-05-23 at 12 18 07](https://user-images.githubusercontent.com/35071867/169798627-ee5c15c2-3f94-44e2-805b-3b2defc75f33.png)

**Comment by martinschorb** [comment]
`Ctrl Click` gives me

```
Exception in thread "Thread-10" java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.view.SliceViewer.lambda$installContextMenuAndKeyboardShortCuts$0(SliceViewer.java:86)
	at org.embl.mobie.viewer.segment.SliceViewRegionSelector.toggleSelectionAtMousePosition(SliceViewRegionSelector.java:59)
	at org.embl.mobie.viewer.segment.SliceViewRegionSelector.run(SliceViewRegionSelector.java:192)
	at org.embl.mobie.viewer.bdv.view.SliceViewer.lambda$installContextMenuAndKeyboardShortCuts$4(SliceViewer.java:135)
	at java.lang.Thread.run(Thread.java:748)
```

But that could be due to the error state I get before.

**Comment by martinschorb** [comment]
Update:

I also get that error

```
Exception in thread "Thread-10" java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.view.SliceViewer.lambda$installContextMenuAndKeyboardShortCuts$0(SliceViewer.java:86)
	at org.embl.mobie.viewer.segment.SliceViewRegionSelector.toggleSelectionAtMousePosition(SliceViewRegionSelector.java:59)
	at org.embl.mobie.viewer.segment.SliceViewRegionSelector.run(SliceViewRegionSelector.java:192)
	at org.embl.mobie.viewer.bdv.view.SliceViewer.lambda$installContextMenuAndKeyboardShortCuts$4(SliceViewer.java:135)
	at java.lang.Thread.run(Thread.java:748)
```

when `ctrl click` in another view without the other error. Also then, the color does not change.

**Comment by tischi** [comment]
Question:
Is it on purpose that the two regions have a very different size?
<img width="600" alt="image" src="https://user-images.githubusercontent.com/2157566/169804280-69367a11-6438-41e0-b98f-945a2097bafb.png">

**Comment by martinschorb** [comment]
yes, it is a Zoom-in of the small region (duplicating the crop and then shifting and scaling it). I thought I could handle this in one annotation. I will try splitting it into two (with only one source each).

**Comment by martinschorb** [comment]
Now this behaves exactly as expected.
No errors.

**Comment by martinschorb** [comment]
So I cannot use differently-sized sources in one annotation? I thought we did exactly that with the centrioles.

**Comment by tischi** [comment]
> So I cannot use differently-sized sources in one annotation? I thought we did exactly that with the centrioles.

I don't know ;-)
I have to understand my own code for that....
Can you please open an issue for that scenario with an example view?

**Comment by tischi** [comment]
1. I created an issue for ☝️ 
2. You seem to have one region annotation twice:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/2157566/169816174-f0d95565-826d-4ebd-81f2-701269b15f72.png">

**Comment by martinschorb** [comment]
> You seem to have one region annotation twice:

yes, I just duplicated the one and removed one source in each. Forgot about the name...

**Comment by tischi** [comment]
I updated MoBIE-beta, I hope the coloring upon region selection works now.

**Comment by tischi** [comment]
Can we close this issue now?
We can open a new one when something related pops up.
