### ISSUE TITLE
Loading large grid views in covid-if project fails

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#743]
E.g. loading the `plate->full grid` view now fails with a very long error message (see just last part of it below).
The error looks like some of the files are not accessible via S3, but I checked in python and from there they can all be loaded.

```
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy13.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1330)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	... 25 more
java.util.concurrent.ExecutionException: java.lang.RuntimeException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.embl.mobie.viewer.MultiThreading.waitUntilFinished(MultiThreading.java:40)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverters(MoBIE.java:245)
	at org.embl.mobie.viewer.view.ViewManager.openAndTransformSources(ViewManager.java:269)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:248)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$createViewSelectionPanel$7(UserInterfaceHelper.java:488)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:400)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:241)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
java.util.concurrent.ExecutionException: java.lang.RuntimeException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.embl.mobie.viewer.MultiThreading.waitUntilFinished(MultiThreading.java:40)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverters(MoBIE.java:245)
	at org.embl.mobie.viewer.view.ViewManager.openAndTransformSources(ViewManager.java:269)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:248)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$createViewSelectionPanel$7(UserInterfaceHelper.java:488)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:400)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:241)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
java.util.concurrent.ExecutionException: java.lang.RuntimeException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.embl.mobie.viewer.MultiThreading.waitUntilFinished(MultiThreading.java:40)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverters(MoBIE.java:245)
	at org.embl.mobie.viewer.view.ViewManager.openAndTransformSources(ViewManager.java:269)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:248)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$createViewSelectionPanel$7(UserInterfaceHelper.java:488)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:400)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:241)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Exception in thread "Thread-13" java.lang.NullPointerException
	at org.embl.mobie.viewer.transform.MergedGridSourceTransformer.lambda$transform$0(MergedGridSourceTransformer.java:53)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.embl.mobie.viewer.transform.MergedGridSourceTransformer.transform(MergedGridSourceTransformer.java:53)
	at org.embl.mobie.viewer.view.ViewManager.openAndTransformSources(ViewManager.java:277)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:248)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$createViewSelectionPanel$7(UserInterfaceHelper.java:488)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by constantinpape** [comment]
(and I am using the latest MoBIE-beta)

**Comment by constantinpape** [comment]
It crashes when loading the images.

**Comment by tischi** [comment]
For me it works.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/2157566/169777586-2e74709b-c7f4-46f3-a6fd-2fa577b3da1e.png">

Maybe your internet?

**Comment by tischi** [comment]
Can you try with a VM within EMBL?

**Comment by constantinpape** [comment]
I tried again and now it also works for me. I suspect it was a transient issue with EMBL S3 (probably not my internet, I did a speedtest right when the error occured and got 100 MB/s download, 10 MB/s upload).
I will try again this afternoon and close the issue if it doesn't occur again.

**Comment by tischi** [comment]
FWIW, I also updated MoBIE-beta again.
