### ISSUE TITLE
Load column -> From project fails in covid-if

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#748]
"Load column" -> "From Project" fails in current MoBIE-beta in the covid-if project (see error message below):
- Open covid-if project
- Go to "sites" table
- Select "Load column" -> "From project"

Note that I tried in a different project where it works (platybrowser, loading a column in the cell table). But I can't find anything wrong for the sites tables.

```
Exception in thread "Thread-13" java.lang.NullPointerException
	at org.embl.mobie.viewer.ui.SwingHelper.selectionDialog(SwingHelper.java:53)
	at org.embl.mobie.viewer.MoBIEHelper.selectCommonFileNameFromProject(MoBIEHelper.java:223)
	at org.embl.mobie.viewer.table.TableViewer.loadColumnsFromProject(TableViewer.java:431)
	at org.embl.mobie.viewer.table.TableViewer.lambda$createLoadColumnsMenuItem$4(TableViewer.java:503)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tischi** [comment]
Interesting. In my code it looks like as if we never supported loading additional tables for regions (only for segmentation). I will try to make it work.

**Comment by constantinpape** [comment]
> Interesting. In my code it looks like as if we never supported loading additional tables for regions (only for segmentation). I will try to make it work.

Ok, that would explain the error :D
