### ISSUE TITLE
Problem with nan values when reading view with "colorByColumn"

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#751]
Loading a view which has "colorByColumn" with a column that contains a `nan` fails, see the error below.
Note that doing coloring with this column via the table menu works without issues.
To reproduce:
- open covid-if-project
- select view `mobie-paper->Figure3b`

```
Exception in thread "Thread-13" java.lang.NumberFormatException: For input string: "nan"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at de.embl.cba.tables.TableRows.minMax(TableRows.java:182)
	at de.embl.cba.tables.color.ColumnColoringModelCreator.getValueRange(ColumnColoringModelCreator.java:318)
	at de.embl.cba.tables.color.ColumnColoringModelCreator.createLinearColoringModel(ColumnColoringModelCreator.java:261)
	at de.embl.cba.tables.color.ColumnColoringModelCreator.createColoringModel(ColumnColoringModelCreator.java:127)
	at org.embl.mobie.viewer.view.ViewManager.configureMoBIEColoringModel(ViewManager.java:104)
	at org.embl.mobie.viewer.view.ViewManager.showAnnotatedMaskDisplay(ViewManager.java:381)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:328)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:238)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$createViewSelectionPanel$7(UserInterfaceHelper.java:488)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tischi** [comment]
I think I fixed it, will upload to MoBIE-beta tomorrow.
