### ISSUE TITLE
bdv-playground error

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#816]
@NicoKiaru 

Any idea what this could be?

```
Exception in thread "main" java.lang.IllegalArgumentException: types and labels must be unique
	at sc.fiji.persist.RuntimeTypeAdapterFactory.registerSubtype(RuntimeTypeAdapterFactory.java:212)
	at sc.fiji.persist.RuntimeTypeAdapterFactory.registerSubtype(RuntimeTypeAdapterFactory.java:227)
	at sc.fiji.persist.ScijavaGsonHelper$ClassTypesAndSubTypes.lambda$getRunTimeAdapterFactory$0(ScijavaGsonHelper.java:159)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at sc.fiji.persist.ScijavaGsonHelper$ClassTypesAndSubTypes.getRunTimeAdapterFactory(ScijavaGsonHelper.java:157)
	at sc.fiji.persist.ScijavaGsonHelper.lambda$getGsonBuilder$1(ScijavaGsonHelper.java:110)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at sc.fiji.persist.ScijavaGsonHelper.getGsonBuilder(ScijavaGsonHelper.java:110)
	at sc.fiji.persist.ScijavaGsonHelper.getGson(ScijavaGsonHelper.java:62)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.setDefaultBdvSupplier(SourceAndConverterBdvDisplayService.java:129)
	at mobie3.viewer.bdv.view.SliceViewer.createBdv(SliceViewer.java:196)
	at mobie3.viewer.bdv.view.SliceViewer.<init>(SliceViewer.java:94)
	at mobie3.viewer.view.ViewManager.<init>(ViewManager.java:116)
	at mobie3.viewer.MoBIE3.openDataset(MoBIE3.java:282)
	at mobie3.viewer.MoBIE3.openDataset(MoBIE3.java:218)
	at mobie3.viewer.MoBIE3.<init>(MoBIE3.java:144)
	at projects.OpenRemotePlatynereis.main(OpenRemotePlatynereis.java:43)
```

triggered here:

```
IBdvSupplier bdvSupplier = new MobieBdvSupplier( sOptions );
SourceAndConverterServices.getBdvDisplayService().setDefaultBdvSupplier( bdvSupplier );
```

**Comment by tischi** [comment]
I had twice a class with the same name.
