### ISSUE TITLE
update failure

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#819]
Hi,

something is wrong with the update site.

- I can update normal Fiji installations 
- while downloading `mobie-viewer-fiji-2.1.10.jar` from the MoBIE update site, I consistently run into this:

```
 [ERROR] javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:596)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3386)
	at net.imagej.updater.util.Downloader.download(Downloader.java:128)
	at net.imagej.updater.util.Downloader.start(Downloader.java:98)
	at net.imagej.updater.Installer.start(Installer.java:154)
	at net.imagej.ui.swing.updater.UpdaterFrame.install(UpdaterFrame.java:616)
	at net.imagej.ui.swing.updater.UpdaterFrame$13.run(UpdaterFrame.java:553)
```

leading to empty jars and a broken update.

**Comment by martinschorb** [comment]
update:

- beta is not affected
- same problem occurs when trying to install MoBIE into a fresh Fiji

**Comment by martinschorb** [comment]
This is the displayed error message:
![Screenshot 2022-08-03 at 10 58 49](https://user-images.githubusercontent.com/35071867/182568454-078ffe7f-d359-4083-bc14-0c8c95cef12b.png)

**Comment by imagejan** [comment]
Cannot reproduce right now... maybe it was a temporary issue on `sites.imagej.net`?

In any case, it's likely not an issue with `mobie-viewer-fiji` but with the ImageJ/Fiji infrastructure, hence I'd suggest discussing/troubleshooting issues like this on the forum (https://forum.image.sc) or the zulip chat (https://imagesc.zulipchat.com).

**Comment by martinschorb** [comment]
it has worked now trying it for like 8 times. I noticed that the mobie `.jar` is rather big, so maybe there was some traffic limitation or timeout involved.
