### ISSUE TITLE
new mobie beta not working

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#831]
It fails with a very long error message (see below).
I tried for the following project: https://github.com/mobie/covid-if-project. (But I guess that it would fail for any project since this seems to be a dependency issue related to https://github.com/jtablesaw/tablesaw/issues/1155)

```
(Fiji Is Just) ImageJ 2.9.0/1.53t; Java 1.8.0_172 [64-bit]; Linux 5.14.0-1051-oem; 154MB of 20589MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntIterable
	at org.embl.mobie.viewer.ThreadHelper.waitUntilFinished(ThreadHelper.java:79)
	at org.embl.mobie.viewer.MoBIE.initDataSources(MoBIE.java:522)
	at org.embl.mobie.viewer.view.ViewManager.initData(ViewManager.java:336)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:268)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:268)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:195)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:141)
	at org.embl.mobie.viewer.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:54)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntIterable
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.embl.mobie.viewer.ThreadHelper.waitUntilFinished(ThreadHelper.java:71)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntIterable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.embl.mobie.viewer.table.saw.TableSawHelper.readTable(TableSawHelper.java:18)
	at org.embl.mobie.viewer.MoBIE.initDataSource(MoBIE.java:556)
	at org.embl.mobie.viewer.MoBIE.lambda$initDataSources$0(MoBIE.java:517)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.ints.IntIterable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
```

**Comment by constantinpape** [comment]
(I am not sure about your workflow here, but it probably makes most sense if you test yourself that it runs first and ping me again when it works from the mobie-beta update site for you, so that we don't need to go back and forth on the hopefully trivial dependency issues)

**Comment by tischi** [comment]
ok, that works. 
now I can load the cells table without crashing.

**Comment by constantinpape** [comment]
Should I try again?

**Comment by tischi** [comment]
yes, for me it works now in a setup of which I think it should mimic yours.

**Comment by tischi** [comment]
Thanks! I will investigate later... maybe only Thursday...

Could you make one issue per different crash (as far as you can tell)?

**Comment by tischi** [comment]
@constantinpape by the way: You have to _explicitly_ say that you want the **mobie3** branch!
I did not hardcode this, because, e.g. the platybrowser in fact opens with the current main branch.

**Comment by constantinpape** [comment]
> Thanks!
> Could you make one issue per different crash (as far as you can tell)?

Ok. (I probably don't have much time for this tomorrow though, but will make separate issues if I run intuo them)

**Comment by constantinpape** [comment]
> @constantinpape by the way: You have to _explicitly_ say that you want the **mobie3** branch!
> I did not hardcode this, because, e.g. the platybrowser in fact opens with the current main branch.

I see, that might be the issue....
I will investigate later.

**Comment by tischi** [comment]
If you 

1. update your Fiji again
2. open the mobie3 branch from covid-if, it should work now.

**Comment by constantinpape** [comment]
Yes, works now.
