### ISSUE TITLE
MoBIE3-beta: opening segmentations fails

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#843]
Opening a segmentation now fails with the following error:
```
Exception in thread "PainterThread" java.lang.ArrayStoreException
	at java.util.ArrayList.toArray(ArrayList.java:411)
	at org.embl.mobie.viewer.bdv.render.AccumulateAlphaBlendingProjectorARGB.<init>(AccumulateAlphaBlendingProjectorARGB.java:60)
	at org.embl.mobie.viewer.bdv.render.AccumulateAlphaBlendingProjectorARGBFactory.createProjector(AccumulateAlphaBlendingProjectorARGBFactory.java:55)
	at bdv.viewer.render.ProjectorFactory.createProjector(ProjectorFactory.java:191)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:668)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:478)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:452)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:464)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
```
(I tried for `platybrowser->cell segmentation`)

**Comment by constantinpape** [comment]
Trying to open a spotDisplay fails with the same error.

**Comment by tischi** [comment]
Fixed and uploaded to MoBIE-beta.
