### ISSUE TITLE
MoBIE3-beta: opening spot source fails due to bounding box

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#844]
Opening a project with a spot source (here: spatial transcriptomics example project) now fails with the following error message:
``` 
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Unknown class: boundingBoxMax
	at org.embl.mobie.viewer.serialize.JsonHelper.createObjectFromJsonValue(JsonHelper.java:53)
	at org.embl.mobie.viewer.serialize.DataSourceMapAdapter.deserialize(DataSourceMapAdapter.java:67)
	at org.embl.mobie.viewer.serialize.DataSourceMapAdapter.deserialize(DataSourceMapAdapter.java:44)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at com.google.gson.Gson.fromJson(Gson.java:905)
	at org.embl.mobie.viewer.serialize.DatasetJsonParser.parseDataset(DatasetJsonParser.java:45)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:256)
	at org.embl.mobie.viewer.MoBIE.setDataset(MoBIE.java:412)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$18(UserInterfaceHelper.java:839)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by constantinpape** [comment]
This was an issue in the project and is fixed now.
