### ISSUE TITLE
Grid view with spot sources does not work

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#854]
Loading spot sources in a grid view does not work; it fails with the error below.
@tischi I added an example view for this to https://github.com/mobie/spatial-transcriptomics-example-project: `bookmarks->grid-view`. (It is a 2 x 1 grid view with an image and spot source for each position).

(Also note that I cleaned up that project a bit: it only has the dataset `pos42` now, which contains the spot data as well now.)

```
Exception in thread "Thread-26" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException
	at org.embl.mobie.viewer.ThreadHelper.waitUntilFinished(ThreadHelper.java:79)
	at org.embl.mobie.viewer.transform.image.ImageTransformer.gridTransform(ImageTransformer.java:96)
	at org.embl.mobie.viewer.view.ViewManager.initData(ViewManager.java:452)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:269)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$13(UserInterfaceHelper.java:755)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.embl.mobie.viewer.ThreadHelper.waitUntilFinished(ThreadHelper.java:71)
	... 5 more
Caused by: java.lang.RuntimeException
	at org.embl.mobie.viewer.image.SpotLabelImage.transform(SpotLabelImage.java:173)
	at org.embl.mobie.viewer.image.DefaultAnnotatedLabelImage.transform(DefaultAnnotatedLabelImage.java:67)
	at org.embl.mobie.viewer.transform.image.ImageTransformer.transform(ImageTransformer.java:36)
	at org.embl.mobie.viewer.transform.image.ImageTransformer.translate(ImageTransformer.java:111)
	at org.embl.mobie.viewer.transform.image.ImageTransformer.lambda$gridTransform$0(ImageTransformer.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by constantinpape** [comment]
> I think I fixed it.

Great!

> I find it a bit confusing that the image names and the table names don't match at all.
> Could that be improved?

This is just a small example for you to enable debugging. It will make sense in the actual project (I can share that with you later). If you want more meaningful names here feel free to change it.
