### ISSUE TITLE
Viewer crashes

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#855]
Hi,

tried to compare the new beta with the release and found the following problem (release version):

- newest release MoBIE updates (MacOS)
- open CLEM example project from Github
- load view `all_sources`
- it seems to load all sources, `Opened 22 image(s) in 3745 ms, using up to 16 thread(s).`
 
but then:

```
Exception in thread "PainterThread" java.lang.IndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:485)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:452)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:464)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.embl.mobie.viewer.bdv.render.AccumulateOccludingProjectorARGB.getArgbIndex(AccumulateOccludingProjectorARGB.java:123)
	at org.embl.mobie.viewer.bdv.render.AccumulateOccludingProjectorARGB.accumulate(AccumulateOccludingProjectorARGB.java:103)
	at org.embl.mobie.viewer.bdv.render.AccumulateOccludingProjectorARGB.accumulate(AccumulateOccludingProjectorARGB.java:45)
	at bdv.viewer.render.AccumulateProjector.mapAccumulate(AccumulateProjector.java:167)
	at bdv.viewer.render.AccumulateProjector.map(AccumulateProjector.java:137)
	at bdv.viewer.render.TiledProjector.lambda$null$0(TiledProjector.java:112)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:851)
	at bdv.viewer.render.TiledProjector.map(TiledProjector.java:110)
	at bdv.viewer.render.MultiResolutionRenderer.lambda$paintFullFrame$0(MultiResolutionRenderer.java:485)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by martinschorb** [comment]
same problem with the `detail_area` views.

**Comment by martinschorb** [comment]
OK,

it seems to be the `fluorescence_a2` source.

```
Exception in thread "PainterThread" java.lang.IndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:485)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:452)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:464)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
Caused by: java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.embl.mobie.viewer.bdv.render.AccumulateOccludingProjectorARGB.getArgbIndex(AccumulateOccludingProjectorARGB.java:123)
	at org.embl.mobie.viewer.bdv.render.AccumulateOccludingProjectorARGB.accumulate(AccumulateOccludingProjectorARGB.java:103)
	at org.embl.mobie.viewer.bdv.render.AccumulateOccludingProjectorARGB.accumulate(AccumulateOccludingProjectorARGB.java:45)
	at bdv.viewer.render.AccumulateProjector.mapAccumulate(AccumulateProjector.java:167)
	at bdv.viewer.render.AccumulateProjector.map(AccumulateProjector.java:137)
	at bdv.viewer.render.TiledProjector.lambda$null$0(TiledProjector.java:112)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:851)
	at bdv.viewer.render.TiledProjector.map(TiledProjector.java:110)
	at bdv.viewer.render.MultiResolutionRenderer.lambda$paintFullFrame$0(MultiResolutionRenderer.java:485)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by martinschorb** [comment]
I just tried with a brand new Fiji installation (MoBIE being the only additional update site) and it behaves the same.
It's not 100% consistent when it happens. Sometimes adding a single source i sufficient to trigger the problem. Maybe it is a memory issue once a certain number of sources are loaded.

**Comment by tischi** [comment]
I think this works now. I will upload new version in 10 minutes.
There is a bunch of other things that don't work with the `all_sources` though, you will see ;-)

**Comment by constantinpape** [comment]
> The problems described above occur with the MoBIE release version and the main branch of the CLEM example project.

I don't think we will fix issues on the main MoBIE channel any more since we plan to change to the mobie3 implementation (the current mobie-beta) next week.

**Comment by martinschorb** [comment]
Have there been any changes to the main branch of the CLEM example that could have broken these views? It was clearly working before...

Also, something seems to be wrong with the updates in general.
When trying to install MoBIE release on a fresh Fiji (Windows), I get an `incorrect file size` error for `mobie-viewer-fiji-2.2.1.jar`.

**Comment by martinschorb** [comment]
But I will focus on testing the Beta channel if that's what will be used soon ;-)

**Comment by martinschorb** [comment]
OK, seems like the update server has some issues. No chance to get any MoBIE installed or updated... Getting loads of SSL timeout and file size errors.
In the long run, distributing hundreds of jars through a single site probably will no longer scale. Updating Fiji is more a gamble than a joy nowadays.

**Comment by tischi** [comment]
Updating Fiji works fine for me...

**Comment by constantinpape** [comment]
Also works fine for me.

**Comment by martinschorb** [comment]
Yes, now the update server seems to be able to breathe again.
