### ISSUE TITLE
Bookmarks that require additional tables don't open

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#875]
Possibly related to https://github.com/mobie/mobie-viewer-fiji/issues/872

Bookmarks that need additional tables don't load e.g.

Open platybrowser (mobie3 branch)
View bookmark 'Figure 3B: morphology clustering full body'
Errors with:

```
Exception in thread "Thread-19" java.lang.IllegalArgumentException: Column morphologyColourScheme is not present in table cells
	at tech.tablesaw.api.Table.columnIndex(Table.java:437)
	at org.embl.mobie.viewer.table.saw.AbstractTableSawAnnotation.getValue(AbstractTableSawAnnotation.java:19)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:601)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:271)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$14(UserInterfaceHelper.java:772)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by constantinpape** [comment]
The issue seems to be that the table "morphology_clusters.tsv" is not loaded, which contains the required column.

**Comment by tischi** [comment]
It was loaded, but it contains less rows than the default table, which I did not properly handle.
Should be fixed now.

**Comment by tischi** [comment]
Could you please update Fiji an try again?

**Comment by constantinpape** [comment]
Yep, it works now.
