### ISSUE TITLE
Opacity and Blending Mode not saved in bookmarks

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#878]
Opacity and blending mode aren't saved properly for segmentations in bookmarks e.g.

Open platybrowser (mobie3 branch)
Save a bookmark to the filesystem showing the raw + cell segmentation
View saved bookmark

The opacity is saved as 1.0 (when it should be 0.5), and I think the blending mode is also wrong

**Comment by constantinpape** [comment]
> and I think the blending mode is also wrong

SegmentationDisplays should in fact not have a blendingMode: https://github.com/mobie/mobie.github.io/blob/master/schema/view.schema.json#L191-L273

**Comment by K-Meech** [comment]
Ah ok - then this is definitely wrong. Currently gets saved as: ```"blendingMode": "sum"``` in the segmentationDisplay

**Comment by tischi** [comment]
Should be fixed.

**Comment by K-Meech** [comment]
Thanks! Looks like the opacity/blending mode is saved properly now.
Although, I do get an error if I save a view, then find it in the menu and 'view' it:
```
Exception in thread "PainterThread" java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.render.AccumulateAlphaBlendingProjectorARGB.getAlphaBlending(AccumulateAlphaBlendingProjectorARGB.java:91)
	at org.embl.mobie.viewer.bdv.render.AccumulateAlphaBlendingProjectorARGB.<init>(AccumulateAlphaBlendingProjectorARGB.java:67)
	at org.embl.mobie.viewer.bdv.render.AccumulateAlphaBlendingProjectorARGBFactory.createProjector(AccumulateAlphaBlendingProjectorARGBFactory.java:55)
	at bdv.viewer.render.ProjectorFactory.createProjector(ProjectorFactory.java:191)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:668)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:478)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:452)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:464)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
```
This doesn't happen if I close and re-open mobie, then ```Load additonal views...```
