### ISSUE TITLE
Load Colums ...  From Project is not working

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#879]
It fails with
```
Exception in thread "Thread-15" java.util.NoSuchElementException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.availableTablePaths(TableSawAnnotationTableModel.java:224)
	at org.embl.mobie.viewer.table.TableView.lambda$null$3(TableView.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

(Not a high priority for me, since From FileSystem is working, but would still be nice to fix eventually)

**Comment by vzinche** [comment]
Even better, when one first loads From FileSystem, then From Project offers the contents of the last selected folder in the file system :)

**Comment by tischi** [comment]
I fixed it that at least it works for the `cells` in the platybrowser:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/2157566/206019533-8be2772a-bcc8-4d7f-beee-af7f817c4ae5.png">

It may look a bit clumsy as is shows that full path, but that's the current logic of the mobie3 code. 
In some way I actually like it as it really shows where the data comes from.
This probably needs more work, also related to: https://github.com/mobie/mobie-viewer-fiji/issues/876

**Comment by constantinpape** [comment]
> It may look a bit clumsy as is shows that full path, but that's the current logic of the mobie3 code.
> In some way I actually like it as it really shows where the data comes from.

I think I would prefer if it just shows the table name without the full address.

And do you think this could be fixed and merged into main and put on the update site soon? Would be nice to have this working.

**Comment by tischi** [comment]
I uploaded a new version to MoBIE-beta. 
Could you please check whether that works for you?
If yes, I would cut a release.

**Comment by constantinpape** [comment]
Yes, it works for me. You can go ahead with a release from my side.
