### ISSUE TITLE
Color by column not working (for missing values?)

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#880]
Sometimes "colorByColumn" is not working and is failing with a very long error message (see parts of it below).
My guess: this happens for partial data (i.e. not all rows have values for the column that is used for coloring).
To reproduce:
- Open platybrowser
- Load cell segmentation
- Load the "gene_clusters" table (https://github.com/mobie/platybrowser-project/blob/main/data/1.0.1/tables/sbem-6dpf-1-whole-segmented-cells/gene_clusters.tsv)
- Select "ColorByColumn"-> "clusters" -> "glasbey"

```
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.embl.mobie.viewer.color.CategoricalAnnotationColoringModel.convert(CategoricalAnnotationColoringModel.java:68)
	at org.embl.mobie.viewer.color.CategoricalAnnotationColoringModel.convert(CategoricalAnnotationColoringModel.java:41)
	at org.embl.mobie.viewer.color.MobieColoringModel.convert(MobieColoringModel.java:65)
	at org.embl.mobie.viewer.table.TableView.getColor(TableView.java:751)
	at org.embl.mobie.viewer.table.TableView.access$200(TableView.java:65)
	at org.embl.mobie.viewer.table.TableView$6.getTableCellRendererComponent(TableView.java:717)
	at javax.swing.JTable.prepareRenderer(JTable.java:5729)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
	at com.formdev.flatlaf.ui.FlatTableUI.paint(FlatTableUI.java:399)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at 
```

**Comment by tischi** [comment]
You are right and I fixed it:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/2157566/197830470-297641ea-b6bd-41de-8fa9-ecbba3713a14.png">

**Comment by tischi** [comment]
uploaded a version where this should be fixed.

**Comment by constantinpape** [comment]
Yep, it's working. Thanks!
