### ISSUE TITLE
mobie-paper bookmark doesn't open

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#898]
The 'Figure1a' bookmark in the 'mobie-paper' group of the platy project no longer opens. It errors with the message below:

```
java.lang.IllegalArgumentException: Cannot add column with duplicate name gene_umap_x to table cells
	at tech.tablesaw.api.Table.validateColumn(Table.java:276)
	at tech.tablesaw.api.Table.addColumns(Table.java:244)
	at tech.tablesaw.joining.DataFrameJoiner.emptyTableFromColumns(DataFrameJoiner.java:832)
	at tech.tablesaw.joining.DataFrameJoiner.joinInternal(DataFrameJoiner.java:209)
	at tech.tablesaw.joining.DataFrameJoiner.leftOuter(DataFrameJoiner.java:569)
	at tech.tablesaw.joining.DataFrameJoiner.leftOuter(DataFrameJoiner.java:553)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.joinTable(TableSawAnnotationTableModel.java:121)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.update(TableSawAnnotationTableModel.java:81)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.annotations(TableSawAnnotationTableModel.java:270)
	at org.embl.mobie.viewer.annotation.DefaultAnnotationAdapter.getAnnotation(DefaultAnnotationAdapter.java:69)
	at org.embl.mobie.viewer.annotation.DefaultAnnotationAdapter.lambda$getAnnotations$0(DefaultAnnotationAdapter.java:138)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.embl.mobie.viewer.annotation.DefaultAnnotationAdapter.getAnnotations(DefaultAnnotationAdapter.java:138)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:583)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:275)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$14(UserInterfaceHelper.java:772)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-88" java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot add column with duplicate name gene_umap_x to table cells
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.joinTable(TableSawAnnotationTableModel.java:126)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.update(TableSawAnnotationTableModel.java:81)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.annotations(TableSawAnnotationTableModel.java:270)
	at org.embl.mobie.viewer.annotation.DefaultAnnotationAdapter.getAnnotation(DefaultAnnotationAdapter.java:69)
	at org.embl.mobie.viewer.annotation.DefaultAnnotationAdapter.lambda$getAnnotations$0(DefaultAnnotationAdapter.java:138)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.embl.mobie.viewer.annotation.DefaultAnnotationAdapter.getAnnotations(DefaultAnnotationAdapter.java:138)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:583)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:275)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$14(UserInterfaceHelper.java:772)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Cannot add column with duplicate name gene_umap_x to table cells
	at tech.tablesaw.api.Table.validateColumn(Table.java:276)
	at tech.tablesaw.api.Table.addColumns(Table.java:244)
	at tech.tablesaw.joining.DataFrameJoiner.emptyTableFromColumns(DataFrameJoiner.java:832)
	at tech.tablesaw.joining.DataFrameJoiner.joinInternal(DataFrameJoiner.java:209)
	at tech.tablesaw.joining.DataFrameJoiner.leftOuter(DataFrameJoiner.java:569)
	at tech.tablesaw.joining.DataFrameJoiner.leftOuter(DataFrameJoiner.java:553)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.joinTable(TableSawAnnotationTableModel.java:121)
	... 17 more
```

**Comment by tischi** [comment]
Will work in `3.0.5`.

```
There are duplicate columns: [gene_umap_x, gene_umap_y]
Those columns will be replaced by the columns in the newly loaded table.
```

**Comment by constantinpape** [comment]
I checked and it works now in the 3.0.5 beta release.
