### ISSUE TITLE
Color by column: blueWhiteRed not working

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#903]
For the covid if project ColorByColumn: blueWhiteRed does not work in some cases and throws a long error message (see part of the error at the end of the issue).

To reproduce:
- Open the project from https://github.com/mobie/covid-if-project 
- Select the view `full_grid`
- In the `wells` table:
    - `Color By Column` -> `Column: score`, `Coloring: blueWhiteRed` 

Tested with latest release on MoBIE-beta. May be related to #887. 

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.embl.mobie.viewer.color.NumericAnnotationColoringModel.convert(NumericAnnotationColoringModel.java:56)
	at org.embl.mobie.viewer.color.NumericAnnotationColoringModel.convert(NumericAnnotationColoringModel.java:37)
	at org.embl.mobie.viewer.color.MobieColoringModel.convert(MobieColoringModel.java:65)
	at org.embl.mobie.viewer.table.TableView.getColor(TableView.java:751)
	at org.embl.mobie.viewer.table.TableView.access$200(TableView.java:65)
	at org.embl.mobie.viewer.table.TableView$4.getTableCellRendererComponent(TableView.java:674)
	at javax.swing.JTable.prepareRenderer(JTable.java:5729)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
	at com.formdev.flatlaf.ui.FlatTableUI.paint(FlatTableUI.java:399)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by tischi** [comment]
Should be fixed with `3.0.5`.
