### ISSUE TITLE
BDV HDF5: supported data types

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#916]
@constantinpape trying to open the data from Jonas' project I am getting:

```
Caused by: hdf.hdf5lib.exceptions.HDF5DatatypeInterfaceException: Can't convert datatypes ["H5Tconv.c line 5236 in H5T__conv_ushort_short(): can't handle conversion exception"]
	at hdf.hdf5lib.H5.H5Dread_short(Native Method)
	at hdf.hdf5lib.H5.H5Dread(H5.java:1568)
	at hdf.hdf5lib.H5.H5Dread(H5.java:1517)
	at bdv.img.hdf5.HDF5AccessHack.readShortMDArrayBlockWithOffset(HDF5AccessHack.java:207)
	at bdv.img.hdf5.HDF5AccessHack.readShortMDArrayBlockWithOffset(HDF5AccessHack.java:192)
	at bdv.img.hdf5.Hdf5VolatileShortArrayLoader.loadArray(Hdf5VolatileShortArrayLoader.java:46)
	at bdv.img.hdf5.Hdf5VolatileShortArrayLoader.loadArray(Hdf5VolatileShortArrayLoader.java:34)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$0(VolatileGlobalCellCache.java:195)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:55)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:135)
	... 7 more
```

Could it be that we have to save it as `short`? Here is seems to be `ushort`?

**Comment by constantinpape** [comment]
Yes, this seems to be one of the typical problems with hdf5 in java. This is probably fixed by saving the data as short, but you need to be aware of overflows.

**Comment by tischi** [comment]
I don't remember how we dealt with this in the beginning of MoBIE....
Anyway, can Jonas somehow change the script to save it as short?

**Comment by constantinpape** [comment]
> Anyway, can Jonas somehow change the script to save it as short?

Yes, he has full control over this since he loads the data into memory. I think he knows what to do already.

**Comment by tischi** [comment]
OK, I am investigation here: https://imagesc.zulipchat.com/#narrow/stream/327326-BigDataViewer/topic/XML.2FHDF5.20specification

I think once we figured this out, we should hard-code this in the mobie-python code, because the BDV.H5 "specification" (as defined by the current implementation in Fiji) does only support a very limited number of data types. Saving HDF5 files with other data types will thus not work in MoBIE. Thus I think our library should not support this, but rather throw an error (possibly with a suggestion how to convert the current data type to a supported one without loosing too much information).
