### ISSUE TITLE
Error launching ImageJ from IDE

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#930]
@ctrueden @nicokiaru Does that look familiar?

```
[ERROR] java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1                                              
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)                                       
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)                             
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)                                       
        at java.base/java.util.Objects.checkIndex(Objects.java:372)                                                           
        at java.base/java.util.ArrayList.get(ArrayList.java:459)                                                              
        at net.imagej.legacy.IJ1Helper$IJ1MenuWrapper.getParentMenu(IJ1Helper.java:1025)                                      
        at net.imagej.legacy.IJ1Helper$IJ1MenuWrapper.create(IJ1Helper.java:984)                                              
        at net.imagej.legacy.IJ1Helper$IJ1MenuWrapper.access$700(IJ1Helper.java:956)                                          
        at net.imagej.legacy.IJ1Helper.addMenuItems(IJ1Helper.java:941)                                                       
        at net.imagej.legacy.LegacyService.initialize(LegacyService.java:507)                                                 
        at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:352)                                 
        at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)                                       
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)                                              
        at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)                                              
        at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)                                             
        at org.scijava.Context.<init>(Context.java:285)                                                                       
        at org.scijava.Context.<init>(Context.java:234)                                                                       
        at org.scijava.Context.<init>(Context.java:174)                                                                       
        at org.scijava.Context.<init>(Context.java:160)                                                                       
        at net.imagej.ImageJ.<init>(ImageJ.java:75)                                                                           
        at org.embl.mobie.cmd.MoBIECommandLineInterface.run(MoBIECommandLineInterface.java:31)                                
        at org.embl.mobie.cmd.MoBIECommandLineInterface.call(MoBIECommandLineInterface.java:25)                               
        at org.embl.mobie.cmd.MoBIECommandLineInterface.call(MoBIECommandLineInterface.java:13)                               
        at picocli.CommandLine.executeUserObject(CommandLine.java:1853)                                                       
        at picocli.CommandLine.access$1100(CommandLine.java:145)                                                              
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)                 
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)                                                          
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)                                                          
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)                                      
        at picocli.CommandLine.execute(CommandLine.java:1978)                                     
```

I am getting this "almost always" when running `final ImageJ imageJ = new net.imagej.ImageJ();` 
It does not seem to do any harm, thus I ignore it.
Any suspicion what this could be due to? 
If it helps I can try to produce a minimal example.

**Comment by NicoKiaru** [comment]
I never got it...

Do you show the ui or not ?

**Comment by ctrueden** [comment]
@tischi We solved this on [this Zulip thread](https://imagesc.zulipchat.com/#narrow/stream/327238-Fiji/topic/.E2.9C.94.20Error.20when.20launching.20from.20command.20line), no?
