### ISSUE TITLE
Loading tables columns from project is broken.

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#937]
`Table->Load Columns ...->Load From: Project` fails with:

```
Exception in thread "Thread-14" java.util.NoSuchElementException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at org.embl.mobie.viewer.table.saw.TableSawAnnotationTableModel.availableTablePaths(TableSawAnnotationTableModel.java:255)
	at org.embl.mobie.viewer.table.TableView.lambda$null$3(TableView.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

I tried for a couple of MoBIE projects, with the current MoBIE version from the main update site, and it fails for all of them. Easiest way to reproduce:
- Open platybrowser
- Add the cell segmentation
- Try to load a column from the project

**Comment by tischi** [comment]
@constantinpape we had this issue already: https://github.com/mobie/mobie-viewer-fiji/issues/879
It is fixed in the `develop` branch.
