### ISSUE TITLE
HCS Opener: out-of-bounds error 

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#983]
@ThomasMicroscopy  reported:

```
Exception in thread "PainterThread" java.lang.ClassCastException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:485)
at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:452)
at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:464)
at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
Caused by: java.lang.ClassCastException: net.imglib2.type.volatiles.VolatileUnsignedByteType$WrappedUnsignedByteType cannot be cast to net.imglib2.type.numeric.integer.GenericShortType
at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:54)
at net.imglib2.type.volatiles.AbstractVolatileRealType.set(AbstractVolatileRealType.java:189)
at net.imglib2.type.volatiles.AbstractVolatileRealType.set(AbstractVolatileRealType.java:51)
at org.embl.mobie.lib.image.StitchedImage$StitchedLocationToValueSupplier$StitchedLocationToValue.accept(StitchedImage.java:511)
at org.embl.mobie.lib.image.StitchedImage$StitchedLocationToValueSupplier$StitchedLocationToValue.accept(StitchedImage.java:455)
at net.imglib2.position.FunctionRandomAccessible$FunctionRandomAccess.get(FunctionRandomAccessible.java:84)
at net.imglib2.outofbounds.OutOfBoundsConstantValue.get(OutOfBoundsConstantValue.java:74)
at net.imglib2.view.TranslationRandomAccess.get(TranslationRandomAccess.java:223)
at net.imglib2.RandomAccess.setPositionAndGet(RandomAccess.java:129)
at net.imglib2.RandomAccessible.getAt(RandomAccessible.java:163)
at org.embl.mobie.lib.image.StitchedImage$StitchedLocationToValueSupplier$StitchedLocationToValue.accept(StitchedImage.java:510)
at org.embl.mobie.lib.image.StitchedImage$StitchedLocationToValueSupplier$StitchedLocationToValue.accept(StitchedImage.java:455)
at net.imglib2.position.FunctionRandomAccessible$FunctionRandomAccess.get(FunctionRandomAccessible.java:84)
at net.imglib2.outofbounds.OutOfBoundsConstantValue.get(OutOfBoundsConstantValue.java:74)
at net.imglib2.interpolation.randomaccess.ClampingNLinearInterpolatorVolatileRealType.get(ClampingNLinearInterpolatorVolatileRealType.java:90)
at net.imglib2.interpolation.randomaccess.ClampingNLinearInterpolatorVolatileRealType.get(ClampingNLinearInterpolatorVolatileRealType.java:49)
at net.imglib2.realtransform.AffineRandomAccessible$AffineRandomAccess.get(AffineRandomAccessible.java:180)
at bdv.viewer.render.VolatileHierarchyProjector.map(VolatileHierarchyProjector.java:291)
at bdv.viewer.render.VolatileHierarchyProjector.map(VolatileHierarchyProjector.java:226)
at bdv.viewer.render.AccumulateProjector.lambda$null$1(AccumulateProjector.java:132)
at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
```

@ThomasMicroscopy could it be that your data contains a mix of different data types (8-bit and 16-bit)?

**Comment by ThomasMicroscopy** [comment]
No, I don't think it's a mix of data types.  I am just wondering, if this could be caused by one missing field.  From the full list of images (2112 tiff images) one field (with 2 channels) had to be removed, because the laser AF in that field failed, and the tiff file was essentially empty. I had manually removed these two tiff files into another folder, because another module stalled when reading this faulty tiff file. Not sure if this could be the problem, since in the viewer in the end I can see all fields, and in row 5, column 2, there is a missing field, so in the end the import worked.
<img width="519" alt="Screenshot 2023-03-02 at 13 50 43" src="https://user-images.githubusercontent.com/126269188/222433672-3dcf35fe-dc1d-4abf-a666-ae2a081434a1.png">

**Comment by ThomasMicroscopy** [comment]
As I mentioned already in the other thread (with the pop-up), there is now also the issue of the window with the well images freezing up. It's not just window itself, which is frozen, but the images in the window are not updated and stay frozen. The freezing seems to happen at the point, when the error messages pop up.
Here again, an example of the window with frozen update, I can resize the window, but the images are not updated.
<img width="1714" alt="Screenshot 2023-03-02 at 15 16 50" src="https://user-images.githubusercontent.com/126269188/222462957-ec65384d-6651-4d36-802c-ef226b590e0c.png">


Here the error codes for this one from the console: 
Exception in thread "PainterThread" java.lang.ClassCastException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:485)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:452)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:464)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
Caused by: java.lang.ClassCastException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:930)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:852)
	at bdv.viewer.render.TiledProjector.map(TiledProjector.java:110)
	at bdv.viewer.render.MultiResolutionRenderer.lambda$paintFullFrame$0(MultiResolutionRenderer.java:485)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.lang.ClassCastException: net.imglib2.type.volatiles.VolatileUnsignedByteType$WrappedUnsignedByteType cannot be cast to net.imglib2.type.numeric.integer.GenericShortType
	at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:54)
	at net.imglib2.type.volatiles.AbstractVolatileRealType.set(AbstractVolatileRealType.java:189)
	at net.imglib2.type.volatiles.AbstractVolatileRealType.set(AbstractVolatileRealType.java:51)
	at org.embl.mobie.lib.image.StitchedImage$StitchedLocationToValueSupplier$StitchedLocationToValue.accept(StitchedImage.java:535)
	at org.embl.mobie.lib.image.StitchedImage$StitchedLocationToValueSupplier$StitchedLocationToValue.accept(StitchedImage.java:479)
	at net.imglib2.position.FunctionRandomAccessible$FunctionRandomAccess.get(FunctionRandomAccessible.java:84)
	at net.imglib2.outofbounds.OutOfBoundsConstantValue.get(OutOfBoundsConstantValue.java:74)
	at net.imglib2.view.TranslationRandomAccess.get(TranslationRandomAccess.java:223)
	at net.imglib2.RandomAccess.setPositionAndGet(RandomAccess.java:129)
	at net.imglib2.RandomAccessible.getAt(RandomAccessible.java:163)
	at org.embl.mobie.lib.image.StitchedImage$StitchedLocationToValueSupplier$StitchedLocationToValue.accept(StitchedImage.java:534)
	at org.embl.mobie.lib.image.StitchedImage$StitchedLocationToValueSupplier$StitchedLocationToValue.accept(StitchedImage.java:479)
	at net.imglib2.position.FunctionRandomAccessible$FunctionRandomAccess.get(FunctionRandomAccessible.java:84)
	at net.imglib2.outofbounds.OutOfBoundsConstantValue.get(OutOfBoundsConstantValue.java:74)
	at net.imglib2.interpolation.randomaccess.ClampingNLinearInterpolatorVolatileRealType.get(ClampingNLinearInterpolatorVolatileRealType.java:90)
	at net.imglib2.interpolation.randomaccess.ClampingNLinearInterpolatorVolatileRealType.get(ClampingNLinearInterpolatorVolatileRealType.java:49)
	at net.imglib2.realtransform.AffineRandomAccessible$AffineRandomAccess.get(AffineRandomAccessible.java:180)
	at bdv.viewer.render.VolatileHierarchyProjector.map(VolatileHierarchyProjector.java:291)
	at bdv.viewer.render.VolatileHierarchyProjector.map(VolatileHierarchyProjector.java:226)
	at bdv.viewer.render.AccumulateProjector.lambda$null$1(AccumulateProjector.java:132)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:851)
	at bdv.viewer.render.AccumulateProjector.map(AccumulateProjector.java:130)
	at bdv.viewer.render.TiledProjector.lambda$null$0(TiledProjector.java:112)
	... 5 more


----------

I had the feeling that with the first Beta version of MoBIE this did not happen, but maybe I was lucky, or didn't look at the right moment, since there was already this error at the top.

There is also one error message which I got so far once, not sure if this helps - the file exists, so not sure what this error is - the "._" before the "r05c09..." is not part of the file name, the real file name is "r05c09....tiff", but then perhaps that comes from the parser ?


<img width="1246" alt="Screenshot 2023-03-02 at 14 25 04" src="https://user-images.githubusercontent.com/126269188/222463812-1d911d7d-2633-4ac1-890c-2871e29ef84d.png">

**Comment by tischi** [comment]
I think this was due to the `.*` files.
