### ISSUE TITLE
new crash with HCS imported images

### ISSUE THREAD

**Issue by ThomasMicroscopy** [mobie/mobie-viewer-fiji#993]
I just had a crash. Images (from HCS import) where loaded fine, I seemed to be able to do things, zoom in, out, move, adjust contrast.  Let it sit in the background a while, came back moving, zoom, suddenly crashed.

Exception in thread "PainterThread" java.lang.ClassCastException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:485)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:452)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:464)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
Caused by: java.lang.ClassCastException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:930)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:852)
	at bdv.viewer.render.TiledProjector.map(TiledProjector.java:110)
	at bdv.viewer.render.MultiResolutionRenderer.lambda$paintFullFrame$0(MultiResolutionRenderer.java:485)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.ClassCastException: net.imglib2.type.volatiles.VolatileUnsignedByteType$WrappedUnsignedByteType cannot be cast to net.imglib2.type.numeric.integer.GenericShortType
	at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:54)
	at net.imglib2.type.volatiles.AbstractVolatileRealType.set(AbstractVolatileRealType.java:189)
	at net.imglib2.type.volatiles.AbstractVolatileRealType.set(AbstractVolatileRealType.java:51)
	at org.embl.mobie.lib.image.StitchedImage$VolatileValueFromTilesFetcherSupplier$VolatileValueFromTilesFetcher.accept(StitchedImage.java:592)
	at org.embl.mobie.lib.image.StitchedImage$VolatileValueFromTilesFetcherSupplier$VolatileValueFromTilesFetcher.accept(StitchedImage.java:541)
	at net.imglib2.position.FunctionRandomAccessible$FunctionRandomAccess.get(FunctionRandomAccessible.java:84)
	at net.imglib2.outofbounds.OutOfBoundsConstantValue.get(OutOfBoundsConstantValue.java:74)
	at net.imglib2.view.TranslationRandomAccess.get(TranslationRandomAccess.java:223)
	at net.imglib2.RandomAccess.setPositionAndGet(RandomAccess.java:129)
	at net.imglib2.RandomAccessible.getAt(RandomAccessible.java:163)
	at org.embl.mobie.lib.image.StitchedImage$VolatileValueFromTilesFetcherSupplier$VolatileValueFromTilesFetcher.accept(StitchedImage.java:591)
	at org.embl.mobie.lib.image.StitchedImage$VolatileValueFromTilesFetcherSupplier$VolatileValueFromTilesFetcher.accept(StitchedImage.java:541)
	at net.imglib2.position.FunctionRandomAccessible$FunctionRandomAccess.get(FunctionRandomAccessible.java:84)
	at net.imglib2.outofbounds.OutOfBoundsConstantValue.get(OutOfBoundsConstantValue.java:74)
	at net.imglib2.interpolation.randomaccess.ClampingNLinearInterpolatorVolatileRealType.get(ClampingNLinearInterpolatorVolatileRealType.java:90)
	at net.imglib2.interpolation.randomaccess.ClampingNLinearInterpolatorVolatileRealType.get(ClampingNLinearInterpolatorVolatileRealType.java:49)
	at net.imglib2.realtransform.AffineRandomAccessible$AffineRandomAccess.get(AffineRandomAccessible.java:180)
	at bdv.viewer.render.VolatileHierarchyProjector.map(VolatileHierarchyProjector.java:291)
	at bdv.viewer.render.VolatileHierarchyProjector.map(VolatileHierarchyProjector.java:226)
	at bdv.viewer.render.AccumulateProjector.lambda$null$1(AccumulateProjector.java:132)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:851)
	at bdv.viewer.render.AccumulateProjector.map(AccumulateProjector.java:130)
	at bdv.viewer.render.TiledProjector.lambda$null$0(TiledProjector.java:112)
	... 5 more

Here the screenshot when it happened. The image window contents was then frozen.

<img width="2019" alt="Screenshot 2023-03-08 at 17 32 22" src="https://user-images.githubusercontent.com/126269188/223775319-18401080-e6eb-44ab-82d6-10645bb6c5ee.png">

**Comment by tischi** [comment]
`
Caused by: java.lang.ClassCastException: net.imglib2.type.volatiles.VolatileUnsignedByteType$WrappedUnsignedByteType cannot be cast to net.imglib2.type.numeric.integer.GenericShortType
`

This smells like as if again, some intruder image managed to sneak in ;-)

Should your data be 16-bit or 8-bit?

The error message suggests that the images should 16-bit but somehow some 8-bit image managed to make its way into the folder...

Do you have any suspicion? Or maybe this is again one of those unfinished small images.

Maybe I could check for this somehow...

**Comment by ThomasMicroscopy** [comment]
hmm,  I thought it was the data  set I sent you.


________________________________
From: Christian Tischer ***@***.***>
Sent: 08 March 2023 18:53
To: mobie/mobie-viewer-fiji
Cc: ThomasMicroscopy; Author
Subject: [EXTERN] Re: [mobie/mobie-viewer-fiji] new crash with HCS imported images (Issue #993)


Caused by: java.lang.ClassCastException: net.imglib2.type.volatiles.VolatileUnsignedByteType$WrappedUnsignedByteType cannot be cast to net.imglib2.type.numeric.integer.GenericShortType

This smells like as if again, some intruder image managed to sneak in ;-)

Should your data be 16-bit or 8-bit?

The error message suggests that the images should 16-bit but somehow some 8-bit image managed to make its way into the folder...

Do you have any suspicion? Or maybe this is again one of those unfinished small images.

Maybe I could check for this somehow...
